### ISSUE TITLE
java.lang.IllegalStateException: TickNextTick list out of synch

### ISSUE THREAD

**Issue by derSchotte** [Shinoow/AbyssalCraft#104]
Hi,

I was playing with your Mod and create a new World, after spawning i get attacked by the AbyssalCraft Pigs and i try to kill them.. After killing a pig, minecraft crashes with this errorlog...

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.4.jar)
  HarmonyPreloader (craftingharmonics-1.9.4-1.4.3.26.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.jar)
  LoadingPlugin (Quark-beta-21.jar)
  LoadingPlugin (NoNausea-MC1.9.4-1.0.jar)
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  MMFMLCorePlugin (MultiMine-1.9.4.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  CoreMod (Aroma1997Core-1.9.4-1.0.6.0.b65.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 02.06.16 11:49
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:696)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:696)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)

-- Affected level --
Details:
	Level name: BOP+Ruins
	All players: 1 total; [EntityPlayerMP['derSchotte'/510, l='BOP+Ruins', x=-73,03, y=68,00, z=226,30]]
	Chunk stats: ServerChunkCache: 763 Drop: 0
	Level seed: 1077666747355240301
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-56,64,220), Chunk: (at 8,4,12 in -4,13; contains blocks -64,0,208 to -49,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3885 game time, 3885 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 21320 (now: false), thunder time: 55061 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1614717824 bytes (1539 MB) / 3592945664 bytes (3426 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 1, tcache: 1, allocated: 3, tallocated: 104
	FML: MCP 9.28 Powered by Forge 12.17.0.1937 120 mods loaded, 119 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1937.jar) 
	UCHIJAAAA	Forge{12.17.0.1937} [Minecraft Forge] (forge-1.9.4-12.17.0.1937.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.0.6.0.b65.jar) 
	UCHIJAAAA	buildingbrickshooks{1.9.4-2.0.4} [Building Bricks Hooks] (minecraft.jar) 
	UCHIJAAAA	cei{1.2} [Chunk Edge Indicator] (1.9.4-chunkedgeindicator-1.2.jar) 
	UCHIJAAAA	JEI{3.4.3.207} [Just Enough Items] (jei_1.9.4-3.4.3.207.jar) 
	UCHIJAAAA	abyssalcraft{1.9.1.6} [AbyssalCraft] (AbyssalCraft-1.9.4-1.9.1.6.jar) 
	UCHIJAAAA	actuallyadditions{1.9.4-r36} [Actually Additions] (ActuallyAdditions-1.9.4-r36.jar) 
	UCHIJAAAA	additionalbanners{1.2.0.17} [Additional Banners] (AdditionalBanners-1.9.4-1.2.0.18.jar) 
	UCHIJAAAA	armorplus{2.4.1} [ArmorPlus] (ArmorPlus2.4.1(1.9.4).jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.6.0.b65} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.0.6.0.b65.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.0.b33} [AromaBackup] (AromaBackup-1.9.4-1.0.1.0.b33.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.0.b33.jar) 
	UCHIJAAAA	bagginses{2.4.2} [Bagginses] (Bagginses-1.9.4-2.4.2.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	BaublesHud{3.0.0} [Baubles-Hud] (BaublesHud-1.9.4-3.0.0.jar) 
	UCHIJAAAA	rarmor{0.8.1} [Rarmor] (Rarmor-0.8.1.jar) 
	UCHIJAAAA	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UCHIJAAAA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCHIJAAAA	bdlib{1.11.0.1} [BD Lib] (bdlib-1.11.0.1-mc1.9.4.jar) 
	UCHIJAAAA	BetterAchievements{0.2.5.24} [Better Achievements] (BetterAchievements-1.9.4-0.2.5.24.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2023} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2023-universal.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.1-40} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-40.jar) 
	UCHIJAAAA	bookshelf{1.2.2.254} [Bookshelf] (Bookshelf-1.9.4-1.2.2.257.jar) 
	UCHIJAAAA	Botania{r1.8-308} [Botania] (Botania-unofficial.r1.8-308.jar) 
	UCHIJAAAA	Quark{beta-21} [Quark] (Quark-beta-21.jar) 
	UCHIJAAAA	buildingbricks{1.9.4-2.0.4} [Building Bricks] (BuildingBricks-1.9.4-2.0.4.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UCHIJAAAA	chiselsandbits{10.2} [Chisels & Bits] (chiselsandbits-10.2.jar) 
	UCHIJAAAA	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar) 
	UCHIJAAAA	colossalchests{1.3.5} [Colossal Chests] (ColossalChests-1.9.4-1.3.5.jar) 
	UCHIJAAAA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9.4.jar) 
	UCHIJAAAA	craftablenametags{1.2} [Craftable Name Tags] (craftablenametags-1.2.jar) 
	UCHIJAAAA	craftingcraft{4.0.3} [CraftingCraft] (craftingcraft-mc1.9.4-4.0.3.jar) 
	UCHIJAAAA	NashornLib{1.9.4-1.8.77-1.3.0} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.0.7.jar) 
	UCHIJAAAA	craftingharmonics{1.9.4-1.4.3} [Crafting Harmonics] (craftingharmonics-1.9.4-1.4.3.26.jar) 
	UCHIJAAAA	craftingtweaks{5.0.6} [Crafting Tweaks] (craftingtweaks-mc1.9.4-5.0.6.jar) 
	UCHIJAAAA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.9.4-2.0.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	DarkUtils{1.1.1.42} [Dark Utilities] (DarkUtilities-1.9.4-1.1.1.43.jar) 
	UCHIJAAAA	ElecCore{1.5.285} [ElecCore] (ElecCore-1.9.4-1.5.285.jar) 
	UCHIJAAAA	deepresonance{1.1.4beta32} [DeepResonance] (deepresonance-1.9.4-1.1.4beta32.jar) 
	UCHIJAAAA	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UCHIJAAAA	endercore{1.9.4-0.4.0.23-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.23-alpha.jar) 
	UCHIJAAAA	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCHIJAAAA	EnderIO{1.9.4-3.0.0.36_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.36_alpha.jar) 
	UCHIJAAAA	enderrift{0.16.3} [Ender-Rift] (EnderRift-1.9.4-0.16.3.jar) 
	UCHIJAAAA	enderthing{0.6.6} [Enderthing] (enderthing-1.9.4-0.6.6.jar) 
	UCHIJAAAA	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UCHIJAAAA	evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2.jar) 
	UCHIJAAAA	ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation] (ExtraBitManipulation-1.9.4-2.1.0.jar) 
	UCHIJAAAA	golems{5.01} [Extra Golems] (ExtraGolems[1.9.4]-5.01.jar) 
	UCHIJAAAA	FFS{1.9.4-1.5.5-b15} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.5.5-b15.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-MC1.9.4-1.7.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.9.4-v3.0} [Flat Colored Blocks] (flatcoloredblocks-mc1.9.4-v3.0.jar) 
	UCHIJAAAA	fluxducts{1.0.4} [Flux Ducts] (fluxducts-mc1.9.4-1.0.4.jar) 
	UCHIJAAAA	forgeanalytics{0.0.0.16} [Forge Analytics] (ForgeAnalytics-1.9-0.0.0.16.jar) 
	UCHIJAAAA	SilentLib{1.0.8} [Silent Lib] (SilentLib-1.9.4-1.0.8-14.jar) 
	UCHIJAAAA	FunOres{1.2.5} [Fun Ores] (FunOres-1.9.4-1.2.5-64.jar) 
	UCHIJAAAA	furnus{1.80} [Furnus] (Furnus-1.9.4-1.80.jar) 
	UCHIJAAAA	pressure{1.3.1.1} [Pressure Pipes] (pressure-1.3.1.1-mc1.9.4.jar) 
	UCHIJAAAA	advgenerators{0.9.20.1} [Advanced Generators] (generators-0.9.20.1-mc1.9.4.jar) 
	UCHIJAAAA	Harvest{1.9.4-1.0.1-5} [Harvest] (Harvest-1.9.4-1.0.1-5.jar) 
	UCHIJAAAA	HelpFixer{1.3.14} [HelpFixer] (HelpFixer-1.9.4-1.3.14.jar) 
	UCHIJAAAA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UCHIJAAAA	IGWMod{1.3.0-5} [In-Game wiki Mod] (IGW-Mod-1.9.4-1.3.0-5-universal.jar) 
	UCHIJAAAA	infotip{1.9.4-1.0} [InfoToolTip] (infotip-1.9.4-1.0.jar) 
	UCHIJAAAA	inventorytweaks{1.61-dev-53-0736dc3} [Inventory Tweaks] (InventoryTweaks-1.61-dev-53.jar) 
	UCHIJAAAA	IronChest{6.0.141.782} [Iron Chest] (ironchest-1.9.4-6.0.141.782.jar) 
	UCHIJAAAA	journeymap{1.9.4-5.2.0} [JourneyMap] (journeymap-1.9.4-5.2.0-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.5.31} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.5.31.jar) 
	UCHIJAAAA	JET{2.1.32} [JustEnoughTooltips] (JustEnoughTooltips-1.9.4-2.1.32.jar) 
	UCHIJAAAA	lteleporters{1.1.2} [Lemon's Simple Teleporters] (LemonsSimpleTeleporters-1.1.2-MC1.9.4.jar) 
	UCHIJAAAA	llor{1.0.7-mc1.9.4} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.9.4.jar) 
	UCHIJAAAA	mantle{1.9.4-0.10.1.jenkins142} [Mantle] (Mantle-1.9.4-0.10.1.jenkins142.jar) 
	UCHIJAAAA	miab{1.4.2} [Meme in a bottle] (MemeInABottle-1.4.2 1.9.4.jar) 
	UCHIJAAAA	minemenu{1.4.3} [MineMenu] (MineMenu-1.9.X-1.4.3.B6-universal.jar) 
	UCHIJAAAA	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	morefood{1.15d} [More Foods] (morefood-1.9.4-1909-1.16.jar) 
	UCHIJAAAA	Morpheus{1.9.4-3.1.3} [Morpheus] (Morpheus-1.9.4-3.1.3.jar) 
	UCHIJAAAA	MouseTweaks{2.6.3} [Mouse Tweaks] (MouseTweaks-2.6.3-mc1.9.4.jar) 
	UCHIJAAAA	AS_MultiMine{1.5.3} [Multi Mine] (MultiMine-1.9.4.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-8.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	NoFov{1.0.1} [No Fov] (NoFov-MC1.9.4-1.0.1.jar) 
	UCHIJAAAA	NoNausea{1.0} [No Nausea] (NoNausea-MC1.9.4-1.0.jar) 
	UCHIJAAAA	notenoughwands{1.3.4} [Not Enough Wands] (notenoughwands-1.9.4-1.3.4.jar) 
	UCHIJAAAA	fodc{1.8.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.2.jar) 
	UCHIJAAAA	packingtape{0.5.1} [Packing Tape] (PackingTape-1.9.4-0.5.1.jar) 
	UCHIJAAAA	planttech{1.5.0} [Planttech] (planttech-1.5.1 - 1.9.4.jar) 
	UCHIJAAAA	playerrugs{1.9.4-1.3.2} [Player Rugs] (PlayerRugs-1.9.4-1.3.2.jar) 
	UCHIJAAAA	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UCHIJAAAA	Psi{beta-33} [Psi] (Psi-beta-33.jar) 
	UCHIJAAAA	randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar) 
	UCHIJAAAA	xreliquary{1.9.4-1.3.2.372} [Reliquary] (Reliquary-1.9.4-1.3.2.372.jar) 
	UCHIJAAAA	ResourceLoader{1.5} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.jar) 
	UCHIJAAAA	rftools{4.50} [RFTools] (rftools-1.9.4-4.50.jar) 
	UCHIJAAAA	rftoolsdim{4.23beta40} [RFTools Dimensions] (rftoolsdim-1.9.4-4.23beta40.jar) 
	UCHIJAAAA	AS_Ruins{16.1} [Ruins Spawning System] (Ruins-1.9.4.jar) 
	UCHIJAAAA	shadowmc{3.3.6} [ShadowMC] (ShadowMC-1.9.4-3.3.6.jar) 
	UCHIJAAAA	simplegrinder{1.245.A194f} [Simple Grinder] (SimpleGrinder-1.245.A194f.jar) 
	UCHIJAAAA	SleepingBag{1.2.0} [Sleeping Bag] (SleepingBag-1.9.4-1.2.0.jar) 
	UCHIJAAAA	soulshardstow{1.9.4-2.4.0-28} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9.4-2.4.0-28.jar) 
	UCHIJAAAA	StellarAPI{0.4.3.2b} [Stellar API] (Stellar API-0.4.3.2b.jar) 
	UCHIJAAAA	stellarsky{0.4.4.1} [Stellar Sky] (Stellar Sky-0.4.4.1.jar) 
	UCHIJAAAA	StorageDrawers{1.9-3.1.7} [Storage Drawers] (StorageDrawers-1.9-3.1.7.jar) 
	UCHIJAAAA	storagenetwork{1.11.1} [Storage Network] (StorageNetwork-1.9.4-1.11.1.jar) 
	UCHIJAAAA	tconstruct{1.9.4-2.3.1.jenkins229} [Tinkers' Construct] (TConstruct-1.9.4-2.3.1.jenkins229.jar) 
	UCHIJAAAA	tellme{0.2.11} [Tell Me] (tellme-1.9.4-0.2.11.jar) 
	UCHIJAAAA	TODOList{1.0.7} [TODO List] (TODOList-1.0.7.jar) 
	UCHIJAAAA	tombmanygraves{1.9.4-2.0.2} [Tomb Many Graves] (TombManyGraves-1.9.4-2.0.2.jar) 
	UCHIJAAAA	underphangables{1.0.2} [Underp Hangables] (underphangables-1.9.4-1.0.2.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.4.jar) 
	UCHIJAAAA	VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UCHIJAAAA	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.190.jar) 
	UCHIJAAAA	wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.190.jar) 
	UD	craftingharmonicsPreloader{1.9.4-1.4.3} [Crafting Harmonics Preloader] (minecraft.jar) 
	Loaded coremods (and transformers): 
LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.4.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
HarmonyPreloader (craftingharmonics-1.9.4-1.4.3.26.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (Quark-beta-21.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (NoNausea-MC1.9.4-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
MMFMLCorePlugin (MultiMine-1.9.4.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreMod (Aroma1997Core-1.9.4-1.0.6.0.b65.jar)
  
EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AbyssalCraftAPI (1.7.1) from AbyssalCraft-1.9.4-1.9.1.6.jar
		* actuallyadditionsapi (15) from ActuallyAdditions-1.9.4-r36.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.9.4-1.0.1.0.b33.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
		* BetterAchievements|API (0.2.5.24) from BetterAchievements-1.9.4-0.2.5.24.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.1-40.jar
		* BotaniaAPI (79) from Botania-unofficial.r1.8-308.jar
		* CapabilityCore|base (1.01) from EnderRift-1.9.4-0.16.3.jar
		* CapabilityCore|energy (1.01) from EnderRift-1.9.4-0.16.3.jar
		* CapabilityCore|tweakable (1.01) from EnderRift-1.9.4-0.16.3.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-10.2.jar
		* CoFHAPI (1.8.9R1.2.0B1) from StorageNetwork-1.9.4-1.11.1.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from fluxducts-mc1.9.4-1.0.4.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from StorageNetwork-1.9.4-1.11.1.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from fluxducts-mc1.9.4-1.0.4.jar
		* compactstorage (v2.0.0a) from compactstorage-2.1-1.9.4.jar
		* CraftingTweaks|API (4.1) from craftingtweaks-mc1.9.4-5.0.6.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.1.4beta32.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.285.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.9.4-3.0.0.36_alpha.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.9.4-3.0.0.36_alpha.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.9.4-3.0.0.36_alpha.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.9.4-3.0.0.36_alpha.jar
		* FunOresAPI (3) from FunOres-1.9.4-1.2.5-64.jar
		* jeresources|API (0.4.5.31) from JustEnoughResources-1.9.4-0.4.5.31.jar
		* journeymap|client-api (1.2) from journeymap-1.9.4-5.2.0-unlimited.jar
		* journeymap|client-api-display (1.2) from journeymap-1.9.4-5.2.0-unlimited.jar
		* journeymap|client-api-event (1.2) from journeymap-1.9.4-5.2.0-unlimited.jar
		* journeymap|client-api-model (1.2) from journeymap-1.9.4-5.2.0-unlimited.jar
		* journeymap|client-api-util (1.2) from journeymap-1.9.4-5.2.0-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9.4-3.4.3.207.jar
		* McJtyLib (1.9.4-1.8.7) from mcjtylib-1.9.4-1.8.7.jar
		* pressureAPI (1.3.1.1) from pressure-1.3.1.1-mc1.9.4.jar
		* PsiAPI (2) from Psi-beta-33.jar
		* rarmorapi (3) from Rarmor-0.8.1.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9.4-2.4.0-28.jar
		* StellarAPI (0.4.3.2b) from Stellar API-0.4.3.2b.jar
		* stellarsky|API (2.5) from Stellar Sky-0.4.4.1.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* VeinMinerApi (0.1) from VeinMiner-1.9_0.31.5.forgePost18010.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: No known problems detected.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['derSchotte'/510, l='BOP+Ruins', x=-73,03, y=68,00, z=226,30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by Shinoow** [comment]
I can't seem to reproduce this, although, it could have something to do with the Forge version in my 1.9.4 workspace... I'll have to do some more investigating on this.

**Comment by Shinoow** [comment]
Closing this issue now. If it's still something that occurs, please re-open it.
