### ISSUE TITLE
incompatibility with Terraqueous

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#107]
I get this crash error while I played to Minecraft when try to go in an AbyssalCraft biome, it seems that there is an icompatibility between your mod and Terraqueous. http://pastebin.com/QEe9pHYL

**Comment by Shinoow** [comment]
Yeah... I don't see how my mod has anything to do with that, as it's triggered by something trying to parse Darkstone as a leaf block (and there's not a single line in AbyssalCraft that tries to parse anything that isn't one of my leaf blocks as a leaf block).
