### ISSUE TITLE
Final 1.7.10 bugfix update

### ISSUE THREAD

**Issue by Shinoow** [Shinoow/AbyssalCraft#109]
This was not something I ever planned on doing, but since people actually started reporting bugs after I dropped 1.7.10, I've decided to do one final bugfix update for that branch. If you have found any bugs in 1.9.1.2, this is the time and place to report said bug. As long as this issue is open, you can report any bugs you find for 1.7.10, and they will be fixed.
**However, once this issue is closed, there will be no 1.7.10 support what so ever, so report your bugs now when you can.**
It should also be noted that this is **ONLY** for bugs, so I won't accept any feature requests or anything of that type, **only bug reports**.

List of things that will be dealt with:
* Staff of rending exceeding the maximum energy value of a type, then just continuing to increase said value.
* Seemingly random crash sometimes happening when hitting the air/a mob/the ground, or any other random occasion.
* Remove the page limit in Necronomicon chapters (there's currently a cap of 20), and the limit on how many rituals can be displayed in a single section (there's currently a cap of 100)
* Boss messages displaying twice in multiplayer
* Brewing recipes are removed (due to adding brewing in 1.7.10 is a mess in itself, and has huge potential for incompatibilities with other mods doing the same thing)
* Staff of Rending not properly syncing when reaching max energy values (resulting in essences not being added to your inventory directly)
* The achievement for reaching Omothol doesn't trigger

If you have something that's not in the aforementioned list, comment with said bug.
## This issue will be closed at June 27, at which the update will be released, so any bug reports after that will be ignored.

**Comment by MikoSphinx** [comment]
when falling off omothol, client dc's; relog puts us in the shadow dimension as intended 
- killing j'zargo doesn't drop the Essence of the Gatekeeper 
- killing j'zargo puts us deep underground in the shadow dimension; should be on surface - killing j'zargo tp makes it look like inventory is empty; relogging fixes this.


Other Problems: - lesser shogoth ooze destroys portals! This is a HUGE problem in multiplayer because there is only one stone available in the second dimension until you beat the omothol boss AND get his drop.... which is impossible at the moment.

**Comment by Shinoow** [comment]
> when falling off omothol, client dc's; relog puts us in the shadow dimension as intended

I will need logs on the dc when falling out (as I've never experienced anything like that).

> killing j'zargo doesn't drop the Essence of the Gatekeeper

The essence drops (as it has ever since it was implemented). I will need an approximation on how far you were from the boss when the death animation finished.

> killing j'zargo puts us deep underground in the shadow dimension; should be on surface - killing j'zargo tp makes it look like inventory is empty; relogging fixes this.

I checked the Y axis after falling out and being teleported, and it was the same, so the only scenario I can see there would be if you ended up being teleported to a set of coordinates where the top block at the Y axis was at a greater height than 80 (as the teleporter is set to teleport the player to that height, something I'm probably going to replace with simply tracking down the top block and using the Y coord above it).
I'm guessing both the dc and inventory oddity occurs in multiplayer only (as I've never encountered those in singleplayer).

> Other Problems: - lesser shogoth ooze destroys portals! This is a HUGE problem in multiplayer because there is only one stone available in the second dimension until you beat the omothol boss AND get his drop.... which is impossible at the moment.

If the stone you're referring to is the Dreadlands Infused Powerstone, there's 3 of them in the first dimension (although, finding more than a single one seems to be quite a nuisance). Since you actually can get the drop, it's not impossible, but complications might arise with the portals if a Lesser Shoggoth by any chance spread ooze on a frame. Due to there currently not being any countermeasures for blocks connected to a portal block, I would advice either blacklisting the stone material in the ooze configs, or add some enforcements around the portal preventing them from approaching it.

As a last thing, it's **J'zahar**, not **J'zargo**.

**Comment by MikoSphinx** [comment]
Where would the log be on the client?

 As for the drop, I was right at the hit box of the boss and my friend was like 2 blocks away, so I would have gotten the drop if he would have dropped it. 
When killing the last boss he only drops a bunch of ingots from Abyssalcraft and a yellow heart when he is first 'killed', before making his speech.

When tp'ed my char is at y53, the top block above ground is at y67. 

Yes we also doing all this in multiplayer, on my server.

**Comment by Shinoow** [comment]
I probably should've gotten back to you here earlier, but I might as well answer the questions now.

> Where would the log be on the client?

That would be logs/latest.log. Anyhow, it turns out that the disconnects might've been the server crashing due to it apparently running client code (noticed that myself on a test server)

> As for the drop, I was right at the hit box of the boss and my friend was like 2 blocks away, so I would have gotten the drop if he would have dropped it. 
When killing the last boss he only drops a bunch of ingots from Abyssalcraft and a yellow heart when he is first 'killed', before making his speech.

This is that one case where corpse-squatting is the wrong thing to do. However, since the current hints at that were very few in 1.7.10 (I implemented a lot more indications for that, since the essence won't be dropped if all nearby players were close enough to be pulled into the Dark Realm, leaving the boss alone), I decided to downport the visual indications shown in 1.8.9 and above to 1.7.10.

> When tp'ed my char is at y53, the top block above ground is at y67.

I went through all forms of teleportation to the Dark Realm on a server, and none put me underground, so I can't replicate this behavior on a server (however, this might have a connection with the disconnecting, possibly displacing the player coordinates).

**Comment by WWDragon** [comment]
Thanks for getting back to us.

After seeing the changes you made to the boss, it becomes evident that getting sent to the shadow realm is a fail, as opposed to just the next step.... especially that room ruining explosion. Heh.

With the update, I can confirm all underground and crash things are gone. :-)

I have noticed 2 minor issues:
1) if you key portal back to the boss world from shadow world, he says the you survived line.

2)  When you do stay away from him at the end, his drop defies gravity, so it's easy to miss it when looking through the other drops (now on the floor below boss room).

**Comment by Shinoow** [comment]
It seems that the boss doesn't have time to complete the speech if you're thrown into the Dark Realm (as the world unloads before the death tick variable reaches it's max value), so there's not that much I can do about that line being spilled after failure.
The gravity defying is there to keep the item in a single spot, instead of it falling down (whereas everything else is affected by gravity).
