### ISSUE TITLE
crash on startup with AbyssalCraft-1.9.4-1.9.2.jar

### ISSUE THREAD

**Issue by SDUBZ** [Shinoow/AbyssalCraft#110]
updated today and got this crash upon loading up
crash log: http://pastebin.com/HbSPaPfK

**Comment by RacerDelux** [comment]
exact same issue

**Comment by Shinoow** [comment]
I did a pretty major refactor in 1.9.2, and some of the internal things (which AbyssalBlocks relies on) has been moved, hence the crash about the file missing. I will have an update out in the next day or so addressing this issue.

**Comment by Morpheus1101** [comment]
Yup same in the 1.9.4 version .. i'll wait for an update :D

**Comment by APolarBaer** [comment]
same 1.9.4 owo

**Comment by Shinoow** [comment]
http://minecraft.curseforge.com/projects/abyssalblocks/files
Latest AbyssalBlocks fixes this, so I'll be closing this issue. AbyssalCraft Integration is covered in #111 (which will be closed when that mod has been updated).
