### ISSUE TITLE
Crash on Startup with 1.8.9 - 1.9.2

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#111]
http://pastebin.com/UVD5Ycdr

Expect it's the same as #110

**Comment by Shinoow** [comment]
More or less. Add-ons will be updated within the next day or so (unless I end up working overtime the next two days, which would delay it even further).

**Comment by Shinoow** [comment]
http://minecraft.curseforge.com/projects/abyssalcraft-integration/files
Latest AbyssalCraft Integration fixes this, so I'll be closing this issue.
