### ISSUE TITLE
1.8.9 (MaybeOthers) Abyssal Zombie Accumulation

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#114]
Because Abyssal Zombies attack normal zombies, they almost all pick up rotten flesh, which prevents them from unspawning. On a server this is starting to become a noticeable source of lag.

**Comment by Shinoow** [comment]
That has potential to become quite the disaster. I will see about perhaps making them simply not pick up rotten flesh, as that is the average drop of zombies, after all.
