### ISSUE TITLE
Feature: Armor upgrades keeps enchantments

### ISSUE THREAD

**Issue by RacerDelux** [Shinoow/AbyssalCraft#115]
I feel that the fact the upgrade does not bring over your enchantments kind of defeats its purpose?

**Comment by Shinoow** [comment]
That should already be a thing... that was among the first things I did after implementing the Upgrade Kits in the first place, making it transfer over enchantments from the old item to the new one when upgrading.

**Comment by RacerDelux** [comment]
One moment - testing again. My last test did not show it working.

**Comment by RacerDelux** [comment]
You are right my apologies - the enchantments just did not show in the crafting window.
