### ISSUE TITLE
[1.9.4] Server crash in Omothol

### ISSUE THREAD

**Issue by EdC94** [Shinoow/AbyssalCraft#116]
Hi,
we got a server crash while exploring Omothol.

[crash-2016-06-25_22.19.34-server.txt](https://github.com/Shinoow/AbyssalCraft/files/333272/crash-2016-06-25_22.19.34-server.txt)

**Comment by Shinoow** [comment]
Hm... might be a few adjustments I didn't make in accordance to the pillar blocks being rotatable. I'm quite certain I know exactly what's triggering this crash, so it will be dealt with.

**Comment by c0rn3j** [comment]
Still an issue in [1.10.2] mod version 1.9.2.1
http://pastebin.com/Z7aCpeBV

**Comment by c0rn3j** [comment]
Fixed in the new version, thank you!
