### ISSUE TITLE
Issue with Monoliths [1.9.4]

### ISSUE THREAD

**Issue by Sansu11** [Shinoow/AbyssalCraft#119]
Just checking to see if this is intended. The in game manual says that when 6 Shoggoths are within 32 blocks of one another, a Monolith will rise out of the slime, with a statue on top.

Tested this. Had exactly 6 running around in an area while I was afk overhead. Wasn't until I had 12+ spawned in that any monoliths started rising.

This is on a 1.9.4 server.

Alternatively, are there any special blocks that Shoggoths can't climb, if not I don't think it'd be a bad idea, offset the utility with a high cost (darkstone bricks around an enderpearl or something=16 Shoggoth-proof blocks). Create a Shoggoth den around a biomass that's walled in so Monoliths can still spawn, but don't get out of hand.

**Comment by Shinoow** [comment]
The monolith isn't created instantly, but the Shoggoths will attempt to create one when there's enough of them around. One will attempt to build one every 90 seconds, and the timer for that resets after those 90 seconds, meaning if the conditions aren't correct, there won't be a monolith, and it'll start over again.

**Comment by MentalMouse** [comment]
I'm pretty sure I've seen them fly, usually when I was already flying.

**Comment by Shinoow** [comment]
There's not a single line in the entity code that makes them fly...

**Comment by MentalMouse** [comment]
Hmmm.  At least one occasion could be explained by climbing, the other I don't remember well enough to know of it could have.
