### ISSUE TITLE
[1.8.9] Coralium Longbow texture becomes errored when drawing back

### ISSUE THREAD

**Issue by Alan19** [Shinoow/AbyssalCraft#122]
Upon right clicking the coralium longbow, the item in your hand becomes the error texture. It goes back to normal after the arrow fires. 
![2016-07-07_20 12 42](https://cloud.githubusercontent.com/assets/11682762/16673791/53c03d9e-447f-11e6-97f5-1b113ded68da.png)

**Comment by Shinoow** [comment]
Huh... I thought that had already been dealt with... I'll have to take a second look at it again...
