### ISSUE TITLE
1.10.2 crash

### ISSUE THREAD

**Issue by DnTheMn** [Shinoow/AbyssalCraft#123]
can u have a look i believe this crash is related to your mod http://pastebin.com/bgTjQd46

**Comment by Shinoow** [comment]
That's my mod, same thing should happen in 1.9.4, 1.9 and 1.8.9 as well (next update will contain a fix for it, since I know what's triggering it).

**Comment by DnTheMn** [comment]
thanks next question do you a rough estimate on the update im not trying to pressure you into releasing im just curious

**Comment by Shinoow** [comment]
The plan was to have it out today, but I might have to post-pone that to tomorrow, unless I can get the last bits I wanna fix done today.

**Comment by DnTheMn** [comment]
no worries thank you

**Comment by McNeillReece98** [comment]
Shinoow, Hello, my name is Reece McNeill, not that it's interesting to know, but I need your help, how do you put a modded Minecraft project into Eclipse without the packages coming up with ALOT of errors all the time? Please help, if you can it would be greatly appreciated :+1:
