### ISSUE TITLE
Crash when updating to Forge 12.18.1.2044

### ISSUE THREAD

**Issue by lilrichy** [Shinoow/AbyssalCraft#127]
http://pastebin.com/nnPa3kbb

**Comment by viper2g1** [comment]
I also have this problem after updating to Forge 1.10.2-12.18.1.2044.

Crash Report: https://gist.github.com/viper2g1/bca770248c2b42f0fd9850420e0bed6e
fml-server-latest: https://gist.github.com/viper2g1/931cf21e2074b39c46eb084054f387f6

**Comment by McJty** [comment]
I also have this problem

**Comment by SDUBZ** [comment]
also happens on forge 1.10.2-2045

**Comment by Shinoow** [comment]
Seems like a fix in Forge exposed the little "hack" I made in order to have more than 16 meta values in a single block. There will be a version out to deal with this soon™, either this week or next week.

**Comment by Sukid** [comment]
Forge 2043 seems to have a lot of bugs so that is quite the undesirable workaround. :(

**Comment by Moustik2002** [comment]
Hi, 2046 won't work as well.

**Comment by Schadrach** [comment]
...which is inconvenient, since recent forge versions break TiCon badly and 2046 is where it's fixed.

**Comment by Moustik2002** [comment]
i confirm it works
