### ISSUE TITLE
demon cows, pigs and chickens fire don't light

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#128]
No it doesn't light. :(

**Comment by Shinoow** [comment]
You need to be more specific. In what way does it not light (light from the block, setting blocks on fire, etc). This description is as vague as it possibly could be.

**Comment by Hypsellis** [comment]
the light from the fire block. There fire that let the demon cows, pigs and chickens behind them when they walk doesn't light.

**Comment by Shinoow** [comment]
It appears the Mimic Fire does indeed not emit any light. That was likely done intentional in order to evade the possible performance hits caused by lightning updates every time the block is created or exstinguished.

**Comment by Shinoow** [comment]
I can add a config option to have them switch to using vanilla Fire instead (at the cost of performance), but other than that the Mimic Fire will not emit light for the sake of reducing the performance impact of the light updates that would occur when the block is placed/removed.

**Comment by Hypsellis** [comment]
It would potentially interest me. Anyway thanks for the change. ;)
