### ISSUE TITLE
API Issues 

### ISSUE THREAD

**Issue by Stuart74** [Shinoow/AbyssalCraft#129]
Not sure if its your issue or machine power craft but as soon as i update forge to the required version i get the below error

Crash Report [GIST](https://gist.github.com/Stuart74/519f6ada9421b5a760802caf16640a29)

Forge version 2046
AbyssalCraft Vers 1.9.2.8

**Comment by Shinoow** [comment]
There's no stacktrace under the error, so I have no possible way to determine if this has anything to do with AbyssalCraft at all, or if something in MachinePowerCraft breaks with the latest Forge.

**Comment by Shinoow** [comment]
Closing this issue now. If it's still something that occurs, please re-open it.
