### ISSUE TITLE
Villages in Darklands Mountains.

### ISSUE THREAD

**Issue by MentalMouse** [Shinoow/AbyssalCraft#131]
You know, there's a reason why villages don't spawn in Extreme Hills.  They probably shouldn't spawn in Darkland Mountains either.

https://www.dropbox.com/s/ihpa4bhnsc62ig3/Dark%20mountain%20village.gif?dl=0

**Comment by Shinoow** [comment]
It's a double edged blade. In some cases they generate really well, in other cases (that picture, for example), the generate as a complete mess. Overall, it's probably for the best to have them not generating in that biome.
