### ISSUE TITLE
[Suggestion] Decrease crafting recipes using Ore Dictionary

### ISSUE THREAD

**Issue by koalalord9999** [Shinoow/AbyssalCraft#132]
I was looking at how to craft a Corlium Chunk, and it came up with like 7 pages of recipes, all being pretty much the same thing, I was thinking, you could reduce the amount of recipes that show up, by using OreDictionary, and naming the Coralium Gem Cluster 1-9 gemCoaliumCluster, then use some way to calculate which is which, and displaying the recipe that way, instead of using 15 different recipes trying to get every possible combination you can do. I don't know how to do this, but I know it's possible as some mods have recipes that change in size, while cycling through NEI/JEI.

But this all is just a suggestion, to make the mod more fluent and less... space takey? xD

**Comment by Shinoow** [comment]
I will look into this. Depending on how the mechanic in NEI/JEI that handles this works, it's a 50/50 that it will display them better or do it the same way (but using the OreDictionary should increase the chance that they don't clutter up pages).
