### ISSUE TITLE
[Bug] Typo in lesser_shoggoth.json

### ISSUE THREAD

**Issue by drakray** [Shinoow/AbyssalCraft#133]
`Couldn't load loot table abyssalcraft:entities/lesser_shoggoth from jar:file:/C:/Users/Utilisateur/AppData/Roaming/.minecraft/1102/mods/AbyssalCraft-1.10.2-1.9.2.9.jar!/assets/abyssalcraft/loot_tables/entities/lesser_shoggoth.json`

`com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 29 column 8`

**Comment by Shinoow** [comment]
Yup, seems like I left a comma in there that shouldn't be there.
