### ISSUE TITLE
Enchantment names and descriptions

### ISSUE THREAD

**Issue by darkhax** [Shinoow/AbyssalCraft#134]
I noticed that the unlocalized names for your enchantments don't seem to include the modid as a prefix. While this usually isn't an issue, it can cause localization conflicts if another mod adds an enchantment with the same name, in a similar way. This has caused some issues in the past for mods like Wawla which attempt to provide in game enchantment descriptions.

As for enchantment descriptions, I was wondering if you would be interested in adding support for enchantment descriptions. Currently I am the only one who makes use of this format (Wawla, Enchanting Plus, and a new mod I am working on), but it's pretty easy to use. Just add `enchantment.MODNAME.ENCHNAME.desc` to your localization file, followed by a short description. The `MODNAME` and `ENCHNAME` bits are pulled from the string based ID used to register the enchantment. The following is a list of localization keys for the enchantments in this mod. 

```
enchantment.abyssalcraft.coralium.desc
enchantment.abyssalcraft.dread.desc
enchantment.abyssalcraft.light_pierce.desc
enchantment.abyssalcraft.iron_wall.desc
```

**Comment by Shinoow** [comment]
I can go into adding Enchantment descriptions. At this point Enchantments and Potions are probably the only things not prefixed with a modid now, so I might as well convert both those over.
