### ISSUE TITLE
[Naming] Crystallized Cluster typo

### ISSUE THREAD

**Issue by drakray** [Shinoow/AbyssalCraft#135]
Crystallized Cluster Molecular formula: Cu is named Crystallized Tin Cluster, should be Copper
Crystallized Cluster Molecular formula: Si is named Crystallized Tin Cluster, should be Silicon
Crystallized Cluster Molecular formula: Mg is named Crystallized Tin Cluster, should be Magnesium
Crystallized Cluster Molecular formula: Al is named Crystallized Tin Cluster, should be Aluminium
Crystallized Cluster Molecular formula: SiO2 is named Crystallized Tin Cluster, should be Silica
Crystallized Cluster Molecular formula: Al2O3 is named Crystallized Tin Cluster, should be Alumina
Crystallized Cluster Molecular formula: MgO is named Crystallized Tin Cluster, should be Magnesia
Crystallized Cluster Molecular formula: Zn is named Crystallized Tin Cluster, should be Zinc

**Comment by Shinoow** [comment]
Seems like I did a minor typo in the code that handles the names.
