### ISSUE TITLE
Performance issue with com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.onLivingUpdate

### ISSUE THREAD

**Issue by ProsperCraft** [Shinoow/AbyssalCraft#138]
https://gyazo.com/c68152756397afdadc516c65575d5b12

[10:49:35] [Server thread/INFO]: Dim -343800852 : Mean tick time: 0.052 ms. Mean TPS: 20.000
[10:49:35] [Server thread/INFO]: Dim -1 : Mean tick time: 0.262 ms. Mean TPS: 20.000
[10:49:35] [Server thread/INFO]: Dim 0 : Mean tick time: 233.319 ms. Mean TPS: 4.286
[10:49:35] [Server thread/INFO]: Overall : Mean tick time: 234.207 ms. Mean TPS: 4.270

Running kill @e[type=!Player]  killed a handful of the the Abyssal Zombies (and everything else) which brought the tps back to 20.

**Comment by ProsperCraft** [comment]
https://gyazo.com/581485144187b7cb03179d6ae00a652d

Its happening again today, some kind of conflict with Malasis doors?

**Comment by Shinoow** [comment]
The only lead I find from that profiler log is that something the raytrace function that Malisis' Core has transformed through their ASM is having troubles when the entity tries to raytrace the nearby blocks searching for a player it can see at it's current position.

**Comment by Ordinastie** [comment]
I made some big refactoring for the next update, and that should (hopefully) fix the performance issue.

**Comment by Shinoow** [comment]
If this is still an issue with the updated Malisis' Doors, reopen the issue.
