### ISSUE TITLE
Recipses with fluids i.e. Antimatter, Coralium to use other containers than just buckets!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Shinoow/AbyssalCraft#139]
Having various tech mods, I'd appreciate it if I could use cans, cells, etc. from other mods filled with corallium, antimatter in recipes and machines etc.

**Comment by Shinoow** [comment]
Since I only use those liquids in buckets for a select few occasions, I have no reason to add other containers with them.

**Comment by Shinoow** [comment]
Closing this. This would be more fitting as a modpack thing, so utilizing mods that adds in additional fluid containers with CraftTweaker scripts for recipes will produce the desired result.
