### ISSUE TITLE
tree leaves other than oak doesn't change of color in abyssalcraft biomes

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#141]
Everything is in title. It has for consequences that when other trees than oaks or darklands trees for darklands generate them in these biomes, they keep their colors, and it makes kinda strange.

**Comment by Shinoow** [comment]
You will need to be more specific. Out of the vanilla trees, all leaf types (except Spruce and Birch, whose colors are hardcoded into the game) change colors inside AbyssalCraft biomes that applies different foliage colors.

**Comment by Hypsellis** [comment]
I spoke about these trees. ^^'

**Comment by Shinoow** [comment]
Since it's vanilla mechanics, there isn't much I can do about it (as I don't plan on rewriting core game behavior).
