### ISSUE TITLE
Crash - During World Generation

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Shinoow/AbyssalCraft#144]
Issue
https://gist.github.com/DPxKnightxZero/574be97efb54d586f662a1b5abc5b436

**Comment by Shinoow** [comment]
Seems to be a case of "item name typo on JSON file". Although, that shouldn't trigger on world generation, should only trigger when the entity in question (a Anti-Spider) is killed and attempts to drop the incorrectly referenced item.

**Comment by DPxKnightxZero** [comment]
Glad I could help you squash it :)
