### ISSUE TITLE
[Suggestion] Add config to disable armor smelting recipes

### ISSUE THREAD

**Issue by al132** [Shinoow/AbyssalCraft#152]
A config option to disable the furnace recipes that turns vanilla armor into ingots/diamonds would be lovely. Usually I would just use crafttweaker to solve this, but for whatever reason I can't remove these specific recipes with it.

**Comment by Shinoow** [comment]
Removing the recipes should be something like ```furnace.removeRecipe(<minecraft:diamond_chestplate>, <minecraft:diamond>);```, where you just replace the armor piece and material to fit each piece or armor.
Anyways, making it possible to stop the recipes from being registered through a config option is something I can include.
