### ISSUE TITLE
After defeating J'zahar I got no essence of the gatekeeper

### ISSUE THREAD

**Issue by mrtopf** [Shinoow/AbyssalCraft#153]
When I killed him I directly dropped down to the dark realm. When I got back there was no essence but also parts of the building was missing. Maybe this also deleted the essence? (xp was still there though). Maybe not destroy the building when he dies? 

I also dropped down some items of my own and they didn't land in the dark realm (as it's not a real portal I assume). So maybe that happened to the essence, too.

**Comment by Shinoow** [comment]
Getting dragged into the Dark Realm means you failed the fight. The essence only drops if there's at least one player within 48 blocks of the boss after the death animation has ended, and if all players ended up being moved to the Dark Realm, there's nobody there to collect the essence.

**Comment by mrtopf** [comment]
Well, it's SP so I was the only player. But I also was directly in front of him as he dragged me in when he died (or should I not come too close?)

**Comment by mrtopf** [comment]
oh and I assume there is no way to respawn it? (except deleting the dimension I guess)

**Comment by Shinoow** [comment]
Respawning can be done through a ritual (I believe it's called "Ritual of Reversed time"). Considering the amount of alarm bells (visual effects getting more intense, the gravity pull, sound that gets more intense, hints in the "villain speech"), I thought the impression that something bad is about to happen would be etched.

**Comment by mrtopf** [comment]
Sure, something seems to be happening, the text is maybe a bit too much to read with everything going on. The question for me was simply what this bad might be and if getting sucked in is ok or if I should fight it. But I also was kind of blinded by the effects so I am not sure how far sucked in I actually was. 

But I will try that ritual and see what happens.

**Comment by mrtopf** [comment]
Ok, I managed to get it now after hiding behind a wall :-) Thanks for the help!
