### ISSUE TITLE
ServerCrash

### ISSUE THREAD

**Issue by DnTheMn** [Shinoow/AbyssalCraft#155]
just like it says on the tin here is the line it prints before it crashes of you need full logs or crash reports let me know Caused by: java.lang.ArrayIndexOutOfBoundsException: 4 at com.shinoow.abyssalcraft.common.entity.EntityDepthsGhoul.func_180482_a(EntityDepthsGhoul.java:387)

i should state were running on 1.10.2 
forge build :12.18.2.2114
abyssalCraft 1.9.3.3

**Comment by blisterfingers** [comment]
Same, had to remove the mod to continue. Full crash log [here](http://pastebin.com/m22BeYvK)

**Comment by DnTheMn** [comment]
yet another one Caused by: java.lang.ArrayIndexOutOfBoundsException: 4	at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_180482_a(EntityAbyssalZombie.java:402) ~[EntityAbyssalZombie.class:?]	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:154)

**Comment by blisterfingers** [comment]
Ohh, haha. This appears to be some kind of Halloween easter egg that's gone derp. It's trying to place a pumpkin on the mobs head so for the mean time, changing the date of the machine running the server should get around this.

**Comment by JorgenHedlund** [comment]
Another one here ---

```
java.lang.ArrayIndexOutOfBoundsException: 4
	at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_180482_a(EntityAbyssalZombie.java:402)
```

**Comment by TLomon** [comment]
Another crash here, right at midnight.

**Comment by DnTheMn** [comment]
this has been resolved then?

**Comment by callmebackdraft** [comment]
> changing the date of the machine running the server should get around this.

this is easier said than done for hosted servers :///

cant there be some sort of workaround/ hotfix to solve this 
??

**Comment by Shinoow** [comment]
I'm gonna have a hotfix out for this today. Seems like a few thing changed slightly after 1.9, and I didn't pay attention to this particular part.

**Comment by Shinoow** [comment]
For those wondering, what's crashing isn't the part where the pumpkin is put on the head, it's the part where it sets the drop rate for the head item (in this case the pumpkin) to 0, which wasn't set to check for the correct slot (since the logic for armor slots changed in 1.9, and I didn't update the part that sets the drop rate.
