### ISSUE TITLE
blindness won't disable

### ISSUE THREAD

**Issue by archonsd** [Shinoow/AbyssalCraft#156]
The mod doesn't seem to honor the config setting to disable blindness.

My config:

`general {
    # Toggles whether blocks that emits particles should do so.
    B:"Block particles"=true

    # Set true to allow the Coralium Plague to spread outside The Abyssal Wasteland.
    B:"Coralium Plague spreading"=false

    # Set to false to disable the random blindness within Darklands biomes
    B:Darkness=false`

I still go blind on an SMP server I run when I step into Abyssal biomes occasionally.

Using "AbyssalCraft-1.10.2-1.9.3.1.jar" with "AbyssalCraft Integration-1.9.4-1.4.5.jar".

**Comment by Shinoow** [comment]
Did you disable it on the server as well? If the config option isn't disabled on the client and the server, you'll still get blinded on a server where it's enabled.

**Comment by Shinoow** [comment]
Closing this now, as said config option has been removed as of AbyssalCraft 1.9.3.10 (not to mention it was moved to only having effect server-side some updates ago).
