### ISSUE TITLE
1.10.2 Client crash due to spawner

### ISSUE THREAD

**Issue by Gunner76th** [Shinoow/AbyssalCraft#161]
http://pastebin.com/kky7jiTN

While exploring the world, my client suddenly crashed. Restart client, and it works for about 60 seconds then crashes again with the same crash. It would appear that there is something bugged with the spawner that was created by Abyssal craft when the dungeon generated.

**Comment by callmebackdraft** [comment]
This issue has been solved in the last pr,
It is also a puplicate of closed issues #154 #155 #157

It had to do with a halloween easter egg which disnt regard a change made to vanilla mc in 1.9

**Comment by Shinoow** [comment]
As callmebackdraft said, it's been fixed. Update to 1.9.3.4 (then again, it's globally past October 31 now, so you won't be able to crash with any released version now)
