### ISSUE TITLE
Brewing modded potions w/ glowstone incorrectly results in Dread Plague II potion

### ISSUE THREAD

**Issue by MechaJ** [Shinoow/AbyssalCraft#162]
Replicated with only JEI and Abyssalcraft.

Brewing any modded potion with glowstone dust results in Dread Plague II rather than the correct potion, for example, when brewing Coralium Plague I with glowstone dust.

**Comment by Shinoow** [comment]
That seems to be the case with any potion that doesn't have a strong variant (eg. one that's made with glowstone). This _could_ have something to do with Forge's brewing recipe registry, but it could also be that the way I use that recipe registry breaks it (gonna switch over to vanilla's system and see if that solves it).

**Comment by Shinoow** [comment]
Switching over to vanilla's system seems to have solved it. This could be a bug with Forge's handling, or a derp on my end using their brewing recipe registry.
