### ISSUE TITLE
issues with fluid storage/processing

### ISSUE THREAD

**Issue by Efimero** [Shinoow/AbyssalCraft#163]
there's a problem with the current abyssalcraft when dealing with coralium fluid
first, when smelting a bucket of it, you get the result, but lose the bucket, which seems like an oversight in the recipe
second, you can put liquid coralium into other mod's tanks and fluid storage (tested with refined storage and immersive engineering barrels), but you can't take it out again, like there is no corresponding liquid-to-bucket recipe
I haven't tested if this happens with antimatter or other of your fluids, but I have tested water, lava, blood magic life essence and creosote oil work as expected

**Comment by Shinoow** [comment]
The smelting recipe is a last resort if you don't have any Liquid Antimatter to use.
Not being able to extract the liquids probably has something to do with my fluids not using the new system, and support for the old fluid handling probably has been gone for quite some time now.
