### ISSUE TITLE
Achievements crash the game

### ISSUE THREAD

**Issue by MaciejJaromin** [Shinoow/AbyssalCraft#171]
Minecraft version: 1.10.2
Abyssalcraft version: 1.9.3.6
Forge version: 12.18.2.2151

Viewing achievements crashes the game. Without Better Achievements, Abyssalcraft's achievements are merged with vanilla ones, and going to the Abyssalcraft tab causes a crash. With BetterAchievements, opening the achievement screen at all causes a crash.
[crash-2016-11-21_19.19.58-client.txt](https://github.com/Shinoow/AbyssalCraft/files/604464/crash-2016-11-21_19.19.58-client.txt)
[crash-2016-11-21_19.02.20-client.txt](https://github.com/Shinoow/AbyssalCraft/files/604465/crash-2016-11-21_19.02.20-client.txt)

**Comment by Shinoow** [comment]
Seems like the internal rewrite of things in 1.9.3.5 broke this (something I should've expected, looking at the code). A hotfix is being released as I'm writing this,
