### ISSUE TITLE
no rain in Darklands ?

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#173]
I noticed that it didn't rain in some darklands variant biomes while it rains in other, I don't know if it's normal.

**Comment by Shinoow** [comment]
The Darklands Plains and Mountains doesn't have any rain in them. I might switch the mountain to snow, since they're mountains, but to be in par with vanilla, no rain in the plains.

**Comment by Hypsellis** [comment]
There is rain in plains, it's only in desert and savanna biomes there is no rain.

**Comment by Shinoow** [comment]
Yeah, just realized that. Not sure why I disabled rain in the plains, but there was probably some reason for it back when the additional Darklands biomes were implemented.

**Comment by Hypsellis** [comment]
So will you add rain to darklands which haven't rain ?

**Comment by Shinoow** [comment]
Most likely.
