### ISSUE TITLE
Inverted stairs are a little broken

### ISSUE THREAD

**Issue by belathus** [Shinoow/AbyssalCraft#174]
Trying to decorate using Abyssalcraft stairs, when they're right-side-up, they seem fine, but when inverted, they don't connect to each other well. Just to show you what I'm talking about, I made a very short imgur album: http://imgur.com/a/01Nse

**Comment by Shinoow** [comment]
It appears just about all of the upside-down stair rotations were inverted in 1.9, and I haven't noticed that (sine the normal ones didn't change, just the corners).
