### ISSUE TITLE
[1.11] Forge 13.19.0.2173

### ISSUE THREAD

**Issue by Shinoow** [Shinoow/AbyssalCraft#176]
Forge 13.19.0.2173 Did a cleanup of the BiomeDictionary code, which included a rename of a method (which triggers a crash as AbyssalCraft is still trying to call the old method). Downgrading to 13.19.0.2172 temporarily fixes it (that is, until I release a new version that's built against a Forge version after 13.19.0.2173), allowing you to use AbyssalCraft in 1.11. I'll have a version out soon that works on the latest Forge.

**Comment by shortybsd** [comment]
Are you referencing version AbyssalCraft-1.11-1.9.3.8.jar? If so any ETA or dev builds where I can push my pack?

**Comment by shortybsd** [comment]
Thank you so much! Awesome mod!!!
