### ISSUE TITLE
Iron Wall enchant doesn't actually do anything.

### ISSUE THREAD

**Issue by Yashimata** [Shinoow/AbyssalCraft#178]
1. Enchant a chestplate with Iron Wall
2. Find the nearest enemy
3. Let it hit you
4. Proceed to be knocked around like a pinata

The necronomicon lists it as an anti-knockback enchantment, but I can't see any difference between having it enchanted and not having it enchanted. You still get punted around just as easily.

**Comment by Shinoow** [comment]
Seems like I haven't updated the code for that effect to actually stop knockback in a pretty long time (at some point the code running in it actually worked to some extent, but there has been a wide range of changes done to physics handling over the years, and that hasn't been reworked to properly do it's thing with those changes). Good catch!
