### ISSUE TITLE
Dreadlands Oak next to impossible to locate?

### ISSUE THREAD

**Issue by SephirothWS** [Shinoow/AbyssalCraft#182]
Running Abyssalcraft 1.9.3.8 on MC 1.10.2, been exploring the Dreadlands dimension for a while and cannot seem to find any trees in any of the Dreadlands Forest biomes I've stumbled upon. Is there like a special way to get dreadlands wood that I'm overlooking?

**Comment by Shinoow** [comment]
That sounds like a mod is stopping the tree generating, since the forests should be nearly drowned in trees. The last time I modified the tree generating there in any way was when I replaced the old tree design with the current one (and that was a while ago).

**Comment by Shinoow** [comment]
Closing this, as it's supposedly been fixed in the modpack (as the issue on the modpack repo was closed, likely meaning it was fixed on their end).
