### ISSUE TITLE
Abyssal Zombies 

### ISSUE THREAD

**Issue by mrshomersimpson** [Shinoow/AbyssalCraft#184]
There is an issue with the zombies that is causing huge FPS issues. BasicallY they attack normal zombies and pick up the rotten flesh they drop which in turn causes the Abyssal zombies to not despawn. New Abyssal zombies keep spawning and at some points in my world i have ended up with thousands of Abyssal zombies all spawning and holding rotten flesh.

**Comment by Shinoow** [comment]
There's configurable item blacklists for a couple of entities (including the Abyssal Zombies), which will prevent them from picking up whatever's listed in said blacklist. If you add Rotten Flesh to that blacklist, the Abyssal Zombies won't pick them up.

**Comment by Shinoow** [comment]
Closing this, as there isn't much more to it than configuring the internal blacklist to not accept picking up Rotten Flesh.
