### ISSUE TITLE
Request - Tcon Direct Integration

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Shinoow/AbyssalCraft#185]
So I am loving this mod but since 90% of my pack contains things for TCON 1.10.2 I was wondering if you too could make some necessary changes.

**Comment by Shinoow** [comment]
The 1.9.4 builds of AbyssalCraft Integration are forwards compatible with 1.10.2, so the Tinkers' integration in there should work in 1.10.2 as well.

**Comment by Shinoow** [comment]
Closing this for now. If there's any particular TiCon 1.10.2 feature that the 1.9.4 integration doesn't cover, file an issue over at https://github.com/Shinoow/AbyssalCraft-Integration with details on it, and I'll be sure to implement it when I make the official 1.10.2 port of AbyssalCraft Integration.
