### ISSUE TITLE
CraftTweaker Recipes No Longer Display in JEI

### ISSUE THREAD

**Issue by Ommina** [Shinoow/AbyssalCraft#186]
Through some recent changes in the interaction between CraftTweaker and JEI (predicated by a desire to eliminate the connection timeouts many were experiencing when attempting to connect to a server), AbyssalCraft recipes added through CraftTweaker no longer appear in JEI.

They work, but do not display, which is less than totally lovely.

I don't know the details of the solution, but I'm told it can (or will be, or something like that) found at jaredlll08/CraftTweaker#127

Thanks!

**Comment by Shinoow** [comment]
Wrong repository, MineTweaker/CraftTweaker stuff is handled in AbyssalCraft Integration.
