### ISSUE TITLE
 Fist of Cha'garoth Crash

### ISSUE THREAD

**Issue by Dewfire** [Shinoow/AbyssalCraft#187]
I am playing the ArdentCraft pack, so not sure if this is directly related to Abyssalcraft or a conflict with another mod.  

I originally crashed to desktop when fighting the boss in the Dreadlands, and not I am unable to load the world at all for whatever reason so wanted to report here just in case I ran into something.

Crash Report:
http://pastebin.com/hxuM2s46

Pack Website:
https://mods.curse.com/modpacks/minecraft/251464-ardentcraft-the-beginning

Please let me know if there is anything I can provide to assist, thanks!

**Comment by Shinoow** [comment]
The crash report points to code updating the currently active Potion Effects of a entity. I'm unable to trigger the same crash with AbyssalCraft alone (also can't trigger it in the pack, so this might be a combination of specific things triggering it).

**Comment by Shinoow** [comment]
Closing this for now. If the crashes continue to happen at a regular basis, I'll have to take a deeper look to potentially find what's doing it.
