### ISSUE TITLE
[Suggestion] Hardcore Darkness Integration

### ISSUE THREAD

**Issue by Axebeard2025** [Shinoow/AbyssalCraft#191]
It would be nice if AbyssalCraft had a config option that if [Hardcore Darkness](https://minecraft.curseforge.com/projects/hardcore-darkness) is installed, AbyssalCraft dimensions will be darker.

**Comment by Shinoow** [comment]
Shouldn't be too hard to implement. I'll look into this.

**Comment by ejektaflex** [comment]
This setting already exists inside of Hardcore Darkness as a config option (dimension blacklist, I think)
