### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DoctorApparatus** [Shinoow/AbyssalCraft#193]
Rename src/main/java/com/shinoow/abyssalcraft/client/render/entity/Renderdreadguard.java
to: src/main/java/com/shinoow/abyssalcraft/client/render/entity/RenderDreadguard.java

Otherwise, at least under linux, gradle complains.

**Comment by Shinoow** [comment]
That's GitHub failing to notice a file rename. That was done on source level a long time ago.

**Comment by DoctorApparatus** [comment]
Hm any idea for a long term solution?

**Comment by Shinoow** [comment]
What exactly is it that you're trying to do?

**Comment by DoctorApparatus** [comment]
I am building a packet manager for minecraft mods right now. Of course after every iteration of a pull I could rename the file in a script but that seems not like a good solution.
