### ISSUE TITLE
Excess server console spam

### ISSUE THREAD

**Issue by sharkck** [Shinoow/AbyssalCraft#194]
Is there a way to fix all of this excess console spam about the abyssalcraft.abyssalzombie?  It makes it difficult to scroll through the server console without having to open the log files up directly and causes very large log files.

[latest.txt](https://github.com/Shinoow/AbyssalCraft/files/828897/latest.txt)

**Comment by Shinoow** [comment]
That's not done by AbyssalCraft. This is a vanilla bug. https://bugs.mojang.com/browse/MC-95649

**Comment by Shinoow** [comment]
Closing this, since there's nothing I can do about it on my end.
