### ISSUE TITLE
[Suggestion] Option to disable anti-mob collision explosions

### ISSUE THREAD

**Issue by rolandoislas** [Shinoow/AbyssalCraft#196]
The explosions are wrecking any attempts at a mob farm.

**Comment by vadis365** [comment]
Using obsidian and other blast resistant blocks will stop things from getting blown up.
There is also a vanilla gamerule to stop mob griefing but that would disable creeper explosions too.

**Comment by Shinoow** [comment]
The antimatter explosion is just like a vanilla explosion, so having the farm made out of something blast-proof cancels out this problem. Alternatively, you can disable mob griefing, but that affects a wider range of things, so building the farm out of something that can handle explosions will do the trick.
