### ISSUE TITLE
Mod compatability issue with ItemPhysics

### ISSUE THREAD

**Issue by MCJediYoda** [Shinoow/AbyssalCraft#197]
Shinoow

I was wondering if it would possible to have Abyssalcraft Pedestals rendering the items with ItemPhysic compatability.  ItemPhysics modifies the way the items are thrown/picked up.   When I right click a pedestal with an item, the item will just spin really fast inside the pedestal.  It would be nice to be able to use ItemPhysics with Abyssalcraft.  

I found a reference to something similar. https://github.com/CreativeMD/ItemPhysic/issues/29

Not sure if this is something you can take a look at on your end. 

Thanks for taking a look.

MCJediYoda

**Comment by Shinoow** [comment]
Turns out the item rendering part there has been relying on some ancient semi-redundant code (and switching out that code made the rendering function normally).

**Comment by MCJediYoda** [comment]
cool. thanks
