### ISSUE TITLE
modded flowers and bushes can't be placed on abyssalcraft dirts and grasses

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#198]
There is a problem with all the AbyssalCraft grasses and dirts, other than vanilla flowers and bushese, no ones of other mods bushes and flowers can be placed on them. You maybe forget to register them as dirt and grass blocks.

**Comment by Shinoow** [comment]
That's not how that works, but since it's a pretty small thing to do, I might as well apply the necessary changes on my end. If this still doesn't work in the next version, that'll be on the other dev's end.

**Comment by Hypsellis** [comment]
Now all trees can grow on dark and dread grass, while I suppose they shouldn't...
