### ISSUE TITLE
Crash on Server Side on LAN Multiplayer

### ISSUE THREAD

**Issue by kenijey** [Shinoow/AbyssalCraft#199]
i don't know what happened, i was just mining 
[crash-2017-04-05_12.19.59-server.txt](https://github.com/Shinoow/AbyssalCraft/files/895737/crash-2017-04-05_12.19.59-server.txt)
please help. thanks

**Comment by Shinoow** [comment]
Apparently I forgot to change one thing when porting some 1.10.2 code to 1.11.2, which evidently let a null element enter a list where there shouldn't be any null elements (then the game crashes when it tries to save the null value). I'm gonna do some additional debugging for any other case where it can crash, then release an update.

**Comment by kenijey** [comment]
thanks so much!
