### ISSUE TITLE
KnowledgeEventHandler.onDeath Error

### ISSUE THREAD

**Issue by BSKCorp** [Shinoow/AbyssalCraft#203]
Forge 1.11.2-20.13.0.2279
Abyssal Craft 1.9.4 Pre 2
Error Log - https://pastebin.com/vYZCeK4d

**Comment by Shinoow** [comment]
Since the other important part (apart from the stack trace of the crash report) wasn't present, what did you kill prior to the crash?

**Comment by BSKCorp** [comment]
Not sure honestly, I was not the one that created the error. This was taken from my private server. One of my family members were on when it happened. I can ask them but I am pretty sure they wont remember.

**Comment by BSKCorp** [comment]
Got the info from another player, think it is the same error but he killed a Chicken Zombie. Here is the second error - https://pastebin.com/yp848wty

**Comment by Shinoow** [comment]
That mod is registering it's mobs incorrectly, which results in the IDs collected by that part of the code not having a value, which then causes a crash as a null check is missing there.

**Comment by BSKCorp** [comment]
OK so I will send this over to deadly monsters then. Thank you for your time sorry if it was a inconvenience.

**Comment by Shinoow** [comment]
This was by no means a inconvenience, as it helped unearth some flaws in this particular part of the mod.
