### ISSUE TITLE
[Begging Suggestion] FIRE BAD!!  

### ISSUE THREAD

**Issue by MokahTGS** [Shinoow/AbyssalCraft#204]
OK, sorry for the silly title but I feel like the fire that trails behind the demon animals is still too much, even when using mimic fire.  It never goes away and is just everywhere.

Can you please add a config to allow server admins to turn it off?

**Comment by Shinoow** [comment]
There's already a config option to stop them from spreading fire when they spawn. Apart from that, some of the internal logic in the Mimic Fire hasn't been tuned to it ticking 30 times faster than regular fire, resulting in the fire spread being a lot more rapid, while the individual block extinguishes quicker.

**Comment by MokahTGS** [comment]
The issue is that in the nether it never goes out...so fire...more fire...more fire.

The fire at spawn was for the overworld versions.

**Comment by Shinoow** [comment]
Thing is, that only applies for regular Fire, as the Mimic Fire can't be sustained by anything.

**Comment by MokahTGS** [comment]
It's being sustained by the netherack that the animals walk on.

**Comment by Shinoow** [comment]
Check again. It's only sustained as long as the animal is standing at the same place for an extended time, refreshing the block. As soon as the animal walks away, the fire will die out after a few seconds.

**Comment by Shinoow** [comment]
Closing this, as you're suggested something already implemented in the mod.
