### ISSUE TITLE
Upgrade Kit Recipes Won't Work

### ISSUE THREAD

**Issue by kenijey** [Shinoow/AbyssalCraft#205]
Using forge 2282, AbyssalCraft-1.11.2-1.9.4-pre-2. We could use upgrade kits to upgrade tools before in time, but now we can't. Upgrading a wooden pickaxe to stone pickaxe with a cobblestone upgrade kit for example.. please help, thanks.

**Comment by Shinoow** [comment]
The whole upgrade kit mechanic has been moved to the anvil. I haven't set up a JEI thing to display it yet, but all of the upgrades are done in an anvil now instead of the crafting grid.

**Comment by kenijey** [comment]
oh :(( at least upgrading kits in crafting was very funny :( anvil isn't cool...

**Comment by Mike-T4** [comment]
I disagree, anvils are cool.
