### ISSUE TITLE
Overuse of Block IDs

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#206]
Clocking in at 188 block IDs Abyssalcraft is in the top ten users of block IDs for the Wanderlust pack. 
Any chance we could get some compression of these?

**Comment by Shinoow** [comment]
A plethora of blocks could easily be merged, but it would break backwards compatibility.

**Comment by Divineaspect** [comment]
I am aware of this, and the need to avoid excessive tile entities.

**Comment by Terpo** [comment]
ok... so with the latest 1.12 commit you break compat to older versions? https://github.com/Shinoow/AbyssalCraft/commit/13148306b351c1553c1ed85492cbd7db1543203f

**Comment by Shinoow** [comment]
When porting between major versions, I have no obligations to make the mod backwards compatible with previous MC versions, as per the SemVer specification. As an end user, you should expect mods to break backwards compatibility when moving between major MC versions. I decided to compress a plethora of my blocks in the 1.12 port, freeing up 30 block IDs.

**Comment by Shinoow** [comment]
Seeing as Blocks/Items with metadata values will be flattened in 1.13 (with the removal of metadata), it's unlikely that any large-scale compression is unlikely to happen (mainly since I'd have to undo it when porting to that version). Closing this issue for that matter.
