### ISSUE TITLE
Other mods trees spawn and grow on darklands and dreadlands grass

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#214]
While they are supposed to not be able to grow on these grasses.

**Comment by Shinoow** [comment]
So, you want me to undo the changes done in #198 ?

**Comment by Hypsellis** [comment]
Oh no, it's just that if I look at your wiki, you told that only flowers and bushes could grow in darkland grass, but if you decided to change it, it's fine for me. :)

**Comment by Shinoow** [comment]
There's a bunch of information in there that's getting outdated, so I need to rewrite some of it (including that bit of text, since all saplings work now).

**Comment by Hypsellis** [comment]
Oh ok I understand, so I will close this issue.
