### ISSUE TITLE
Crystallizer Server Crash

### ISSUE THREAD

**Issue by ukdyl94** [Shinoow/AbyssalCraft#216]
This has been tested both server and single player style.

Server and Single Player world seems to crash when taking out Dreaded Abyssalite Ore

Below is what the player did.

> Placed Crystallizer from abyssalcraft, smelted dreadium ore with blaze power and rods: left clicked on the dreadium crystal shards caused a crash, shift left clicking on the dreadium wont work, but on the abyssalite it did and has crashed the server as well.
Dreaded abyssalite ore
Tried to automatically pull out the crystals from the machine with enderIO item pipes, The abyssalite did fine no problems, but once it got to the Crystalised Dreadium it crashed.

[Crash Logs](https://pastebin.com/WX2nUyai)

**Comment by Shinoow** [comment]
Whoops, missed a null check there. I'll see if I can whip out a hotfix for that tomorrow.
