### ISSUE TITLE
crash with Biomes O' Plenty

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#217]
I get a crash with Biomes O' Plenty 6.1.0.2239 which add the white sandstone and AbyssalCraft when loading Minecraft. https://pastebin.com/jnjicpgj

**Comment by Temil2006** [comment]
same crash here as well. this is only with the 2 newest versions of BiomesOPlenty. 
This wasn't an issue in versions BiomesOPlenty-1.11.2-6.1.0.2238, only presented its self in versions BiomesOPlenty-1.11.2-6.1.0.2239 and BiomesOPlenty-1.11.2-6.1.0.2240

unsure if Biomes mod will change anything to fix this, so hope you are willing to.

**Comment by Shinoow** [comment]
That's partially their fault for not filtering out invalid metadata values when converting meta to state, but I might as well sneak in something on my end to handle metadata wildcards.

**Comment by Temil2006** [comment]
thanks for looking into it and considering doing that. might be good to do as you stated for support of other mods, but seems that BiomesOPlenty mod created put out a patch this morning that seems to correct this, just making you aware. thanks.

for anyone else with this issue, ...
update of
BiomesOPlenty-1.11.2-6.1.0.2243-universal.jar confirmed to fix this issue.
