### ISSUE TITLE
Using the gateway portals causes an endless teleport loop

### ISSUE THREAD

**Issue by phen0menal** [Shinoow/AbyssalCraft#221]
Any attempt to enter a Dreadlands or Abyssal Wasteland portal causes the player to be teleported constantly between whichever portal they entered and the overworld. It sadly renders transporting to the wasteland or dreadlands useless. Only way I know of fixing this problem is I delete my player data or time the tp command correctly.

**Comment by Shinoow** [comment]
There's a config option for the portal teleportation cooldown. Set that to a higher number, then you should have enough time to get out of the portal before you're teleported again.
