### ISSUE TITLE
AbyssalCraft 1.7.10 is crashing during server start up

### ISSUE THREAD

**Issue by Devilswarchild** [Shinoow/AbyssalCraft#223]
upon starting my server all pre initialization goes through without a hitch...then when the post stuff starts AbyssalCraft and AbyssalCraft Integration both come back as Errored...Can we get a fix for this please?
[crash-2017-06-23_16.44.52-server.txt](https://github.com/Shinoow/AbyssalCraft/files/1099131/crash-2017-06-23_16.44.52-server.txt)
[fml-server-latest.zip](https://github.com/Shinoow/AbyssalCraft/files/1099133/fml-server-latest.zip)

**Comment by Shinoow** [comment]
That's a Biome ID conflict. Go into the configs and change the IDs to resolve the conflict.

**Comment by Devilswarchild** [comment]
and what should I change it to?

**Comment by Shinoow** [comment]
The mod that's overlapping the biome ID is Galacticraft, so changing that in their config to a higher number (maybe 120? There's multiple mods in that list that adds biomes, so you might wanna skim through the config files for overlapping IDs).

**Comment by Devilswarchild** [comment]
hmmm ok then. Ill look into it

**Comment by Devilswarchild** [comment]
ill comment back if I find another problem after changing the biome id's

**Comment by Devilswarchild** [comment]
seems to be working so far
