### ISSUE TITLE
SHADOW GEMS PLES!

### ISSUE THREAD

**Issue by Darkosto** [Shinoow/AbyssalCraft#224]
How many miles do I have to walk to find a shadow gem dropping mob?!

1 MILE?!

2 MILES?!

8 MILES?!

WASTE OF MY TIME! MAKE MORE MOBS SPAWN!

BYE FELECIA!

**Comment by Terpo** [comment]
We built an outpost in a darklands plain biome and sometimes you can find one. But still.... the spawns should be more frequent. One shadow on 10 ghuuls and 100 zombies is not the best rate

AbyssalCraft-1.11.2-1.9.4-pre-4.jar

**Comment by Shinoow** [comment]
The spawn rates could probably use some tuning. Currently they spawn more frequently in Darklands Mountains compared to the other Darklands biomes, but the mountain spawn rates could be used as a baseline (after some testing) for the other biomes, while the current rates there gets a little boost of their own.
