### ISSUE TITLE
[1.11.2] Transmutator eats coralium buckets

### ISSUE THREAD

**Issue by Terpo** [Shinoow/AbyssalCraft#225]
A normal furnace just emties a lava bucket so that there is a bucket left. The transmutation just eats it ^^

AbyssalCraft-1.11.2-1.9.4-pre-4.jar

**Comment by Shinoow** [comment]
Huh, seems like that was changed somewhere around 1.10.2 (might've been earlier, but I haven't checked in a workspace prior to that MC version). I'll look into enabling the same functionality on my end to match vanillas.
