### ISSUE TITLE
Quality of life changes

### ISSUE THREAD

**Issue by BarsikTheCaT** [Shinoow/AbyssalCraft#226]
I've got two quality of life suggestions:
1. Remove all non-abyssalcraft hostile spawns from darklands. Seriously, it's hard enough to farm shadow fragments because of their drop rate, don't make mob spawn rate low too.
2. Worldgen structures tracking items. Not just you have a lot of grinding to do, but certain stuff requires somewhat rare worldgen things like ores or mobs. Add a way to find darklands biomes, corallium biomes and shoggoth lairs.

**Comment by angelnc1989** [comment]
For 2. there is the Nature's Compass. It adds a compass that points to biomes you ask it to find.

**Comment by Shinoow** [comment]
For 1, see #224. The planned tweaks there will clear up it.
For 2, Nature's Compass (as pointed out by angelnc1989) allows you to track down biomes. In the event that you've turned down the biome spawn weights, the biome rarity would be more on your end. The frequency of Shoggoth Lairs is RNG dependent (slightly less if the rarity config option is tampered with), so the chances of encountering a bunch of them compared to none comes down to the world seed.
