### ISSUE TITLE
The Amount of Times I have Flipped Pages In The NecroNominominicon (sp?) Is Over 9000

### ISSUE THREAD

**Issue by Darkosto** [Shinoow/AbyssalCraft#227]
Can you please, please, please allow the book to stay on the same page as when you closed it. Having to navigate back to the page you were on last is a bit tedious, immersion breaking, and exasperating. 

Can you please consider changing this?
<3

**Comment by Shinoow** [comment]
But you see, this is the insanity mechanic. Instead of simulating insanity in-game, the person playing loses their mind constantly having to navigate to the page they were at :P
But yeah, I can look into having it store the last page, then open that when opening the book.
