### ISSUE TITLE
Missing Config option

### ISSUE THREAD

**Issue by Quetzi** [Shinoow/AbyssalCraft#23]
There is no option to disable the update checker

**Comment by Shinoow** [comment]
Do you want to be able to disable all of it? Or just the message saying you're using the latest version?

**Comment by Quetzi** [comment]
Users should have the option to not have update checks run. In most cases it is completely unnecessary. An option to disable the check should ideally stop the check running at all.

**Comment by Shinoow** [comment]
Yeah, that makes perfect sense. I'll be sure to implement this for the next version.
