### ISSUE TITLE
[1.12] Game freeze when using the Staff of Rending

### ISSUE THREAD

**Issue by angelnc1989** [Shinoow/AbyssalCraft#230]
Minecraft 1.12
Forge 14.21.1.2426
AbyssalCraft 1.9.4-pre-4

I tried to collect Energy by rightclicking different AbyssalCraft mobs with the Staff of Rending. The game freezes every time and the task has to be killed with the task manager. Obviously there is no crash log.

**Comment by angelnc1989** [comment]
This also happens when I change the mode of the Staff of the Gatekeeper to Rending mode.

**Comment by Shinoow** [comment]
I'm unable to reproduce either case, do you have any other mods installed that could intervene in either of the cases?

**Comment by angelnc1989** [comment]
I can't think of a mod that would affect rightclicking with your Staff of Rending.
I can provide a mod list if you want.

**Comment by Shinoow** [comment]
A copy of the log could also be useful (might be some information in there).

**Comment by angelnc1989** [comment]
Strange thing. I had it happen 5 times in a row and now I can't reproduce it. I updated some other mods, that probably fixed it.
