### ISSUE TITLE
Standardization of Ore Dictionary names

### ISSUE THREAD

**Issue by drinfernoo** [Shinoow/AbyssalCraft#232]
While it doesn't particularly cause an issue with AbyssalCraft-exclusive materials, I've noticed that specifically with Tin and Copper, they aren't using the standard ingotTin and ingotCopper names for the ore dictionary, and rather tiningot and copperingot. This may be intended, so that *only* AbyssalCraft materials can be used in the Crystallizer, but it may be worthwhile, and cause less headaches for players, if they were brought in line with the community standard.

**Comment by Shinoow** [comment]
tiningot and copperingot are the internal names for the ingots (used in the /give command, among other places), which has no impact what so ever on the OreDictionary (as they're registered there with the standardized OreDict names).
