### ISSUE TITLE
Shoggoth not spawning in lairs

### ISSUE THREAD

**Issue by Kubikx** [Shinoow/AbyssalCraft#234]
I waiting for Shoggoth to spawn in lair for more than 3 real hours and nothing.
I try kill everything around, set time to day/night, put torches to lair, remove torches from the lair wait close to lair, wait inside the lair, wait far from it (about 100 blocks).
Only skeletons, zombies, creepers and bats spawn there.
No one kill them I found it newly generated world and I build a wall around it and after that I go inside and it was empty (not counting skeletons, zombies...).
Is there something special I need to do to spawn them? I found nothing about it in the book.

**Comment by Shinoow** [comment]
The lair should have a lot of biomass blocks inside, that's what spawns them. If there aren't any biomass blocks inside, then that lair has been exhausted.

**Comment by Ketrai** [comment]
Hey, can you please, PLEASE. make shoggoth lairs recharge slowly? Right now progressiong through the mod is kind of a pain as a late joiner on bigger servers. Especially if you wanna have a world border to prevent map size from growing into several gigabytes. Literally every lair is depleted. 

Thanks for reading.
