### ISSUE TITLE
Ritual altars and pedestals not craftable

### ISSUE THREAD

**Issue by ravensourcious** [Shinoow/AbyssalCraft#238]
Hi, I'm playing in 1.12 using AbyssalCraft 1.9.4-pre-4 and the Ritual Altar and Pedestal aren't craftable, have no JEI recipe, and don't show up in creative. They show up on JEI when I search but there is no recipe. I am using alot of other mods, but it is even doing this when I tested with this mod alone.

**Comment by Shinoow** [comment]
You don't craft them. The ritual formation is a multiblock structure that's created when you interact with the center block using your Necronomicon after placing the 9 blocks in the correct order.
