### ISSUE TITLE
Ritual for Altar of Cha'Garoth(top) won't activate

### ISSUE THREAD

**Issue by ravensourcious** [Shinoow/AbyssalCraft#239]
I got the ritual for the bottom half to work fine, but the top half is not activating. I followed the instructions in the Necronimicon and set it up correctly, have the required P.E., and have a villager on site as a sacrifice but the ritual won't activate.

**Comment by ravensourcious** [comment]
Nvm, it has to be a mod compatibility issue, tested it again and it works fine, will post when I find out the issue

**Comment by Shinoow** [comment]
There's a bunch of places in the 1.12 version where checking for entities within certain bounds fail due to said bounds being incorrectly offset.
