### ISSUE TITLE
Anti-Spiders glow too much white

### ISSUE THREAD

**Issue by Lykrast** [Shinoow/AbyssalCraft#240]
As you can see on this picture, anti-spiders glow white over their whole body, unlike vanilla spiders that just have glowing eyes.
![image](https://user-images.githubusercontent.com/8684850/31238977-e42880d4-a9fb-11e7-835b-da0da05b300f.png)
This is due to the transparent pixels on the eyes texture for them being transparent white, as the shader that applies spider's eyes ignores alpha. This can be fixed by changing all transparent pixels on the eyes texture to black (or transparent black).

**Comment by Shinoow** [comment]
Thanks for pointing that out! I overlooked that years ago, then never really looked into the specifics (there's a similar thing in leaf blocks, but I never considered that the same thing applies here).
![](https://puu.sh/xT2c9/84074dddeb.png)
That looks a bit more correct.
