### ISSUE TITLE
Unable to craft Tinker's parts

### ISSUE THREAD

**Issue by xenoflot** [Shinoow/AbyssalCraft#242]
AC 1.12-1.9.4-pre-4
AC integration 1.12.1-1.6.0
Forge 14.23.0.2512
TiCo 1.12-2.7.3.30
AllTheMods 4.2

I found a couple of ingots. The smeltery was happy to melt the abyssalnite ingots and displayed 2 ingots of Molten Abyssalnite. JEI suggests it's possible, but the facet won't pour then I have a part cast on the table.

It *will* re-pour them into ingot casts, just not pickaxe heads, etc.

Cheers!

**Comment by Shinoow** [comment]
I'm unable to reproduce this. There are a few casts that aren't supported (gear, gem, plate, to name a few), but when I tested this (I tried a cleaver blade and a small binding), everything seemed to be in order.

**Comment by Nonsanity** [comment]
Did you have enough ingots for the part. Some parts take up to 8 ingots. I’ve successfully made Tinker’s parts from Abyssalcraft materials.
