### ISSUE TITLE
Lesser shoggoth hitbox vs actual size

### ISSUE THREAD

**Issue by Chefbarbie** [Shinoow/AbyssalCraft#244]
Just noticed: To hit a lesser shoggoth, you have to be in it's mouth. 

Don't know if this is intended or not, but makes meeting one early a death sentence.

**Comment by Shinoow** [comment]
1.9.4.7 introduced adjustments to the hitbox and hit range of Lesser Shoggoths. There's likely going to be another round of changes to their hitbox again in the future when they eventually get a new model, but this update brings those properties to a manageable scale.
