### ISSUE TITLE
Staff of Rending does not recognise creatures of Omothol

### ISSUE THREAD

**Issue by Ulysses256** [Shinoow/AbyssalCraft#248]
Modpack: - All The Mods 3 - v5.2
Mod version: 
- AbyssalCraft-1.12.2-1.9.4.2
- AbyssalCraftIntegration-1.12.2-1.6.2
The issue seems to be the following: I've gone trough the intended progression, arrived at Omothol, but I'm not able to extract any essence from the mobs in Omothol, I can only acquire Shadow Essence from shadow creatures. I've tried it with Minions of the Gatekeeper, Remnants, Omothol Ghouls, none seems to care about my Staff of Rending (Staff is the Tier 2 variant - Dreadlands). I've already slain The Gatekeeper, but as many recepies need essence of Omothol, I hit a brick wall at the moment.

Thank you for reading my issue, your mod is superb, I hope It'll grow, and you'll find enjoyment developing it.

**Comment by Shinoow** [comment]
Whoops, looks like this is the one little code change I missed when porting the code between different MC versions. This will be addressed in the next update.

**Comment by Gayanfalor** [comment]
does it can work if we put it on the pedestal of rending that harvest it  ?

**Comment by Ulysses256** [comment]
Hi, sorry for delayed response, I've tested it, the pedestal of rending works fine on everything but Omothol creatures, so I guess It's the same issue. Hope this will help.
