### ISSUE TITLE
Dimensional Whitelist for Overworld/Shoggoth Lair Gen?

### ISSUE THREAD

**Issue by Vyraal1** [Shinoow/AbyssalCraft#250]
Hi,

I'm making a pack right now where the original overworld / dimension 0 is voided and you work your way to the surface world, which is an overworld copy. However it seems that I don't get any of Abyssalcraft's worldgen for dimension 0 in the surface world (it uses the overworld World provider). I get the Darklands biomes just fine, but would it be possible to add a whitelist so that other dimensions can have the Abyssalcraft worldgen such as Darklands structures / Shoggoth lairs?

**Comment by Shinoow** [comment]
The reason you're not getting any if the worldgen is due to it being hardcoded to only generate in dimension 0. I could easily switch that to check for the World Provider instead.

**Comment by Vyraal1** [comment]
That would also be great, I can use other mods to create dimensions with surface world provider, similar way as it also gets the Darklands biomes.
