### ISSUE TITLE
Right-clicking Remnants in Omothol crashes multiplayer server

### ISSUE THREAD

**Issue by SirMoogle** [Shinoow/AbyssalCraft#251]
Managed to make it to Omothol, and after encountering issue #248 I tried to right-click on a Remnant. It opened up a trade screen and a few seconds later it crashed. I'm assuming this will be fixed in a later update with the other issue?

**Comment by Shinoow** [comment]
Can you post the crash report? I haven't encountered any crashes in regards to Remnant trades recently.

**Comment by SirMoogle** [comment]
Unfortunately, I'm not the one with access to the server's files. I'll see if I can find them.

**Comment by SirMoogle** [comment]
The server admin gave me [this gist](https://gist.github.com/retep998/9a76e716899367cafd8ec7d3fdf3c2bc).

**Comment by Shinoow** [comment]
That seems to be caused by Soot. Considering that version (0.1) isn't available on the mod's CurseForge page, maybe try updating the mod and see if that solves it?
