### ISSUE TITLE
Crash with Abyssalcraft and Chisel

### ISSUE THREAD

**Issue by Vyraal1** [Shinoow/AbyssalCraft#252]
Crash Report Here:

https://hastebin.com/ekeputuzaj.sql

Not sure if it matters, but I turned off some blocks in chisel to save on Block ID's

**Comment by trogarus** [comment]
This post over at Chisel includes some log files as well that might help.

https://github.com/Chisel-Team/Chisel/issues/591

**Comment by trogarus** [comment]
Same as https://github.com/Shinoow/AbyssalCraft/issues/253

**Comment by Shinoow** [comment]
Seems like something significantly changed in the latest Chisel beta builds. The crash implies a metadata mismatch between the OreDict ItemStack and what *should* be the BlockState.
Not sure what's happening on their end, but I know how I can fix it on my end.

**Comment by JonasCiss** [comment]
Same here.
[crash-2017-12-10_22.25.05-client.txt](https://github.com/Shinoow/AbyssalCraft/files/1546105/crash-2017-12-10_22.25.05-client.txt)
[crash-2017-12-10_22.37.53-client.txt](https://github.com/Shinoow/AbyssalCraft/files/1546106/crash-2017-12-10_22.37.53-client.txt)

**Comment by codetaylor** [comment]
Forge: 14.23.1.2559
MC: 1.12.2
AbyssalCraft: 1.9.4.2
Chisel: 0.1.0.22

Crash log: https://gist.github.com/codetaylor/999fca5affe097b29f1156c6c1998f0a

**Comment by justinrusso** [comment]
Might still be worth adjusting things on your end, but a "workaround" was added to chisel: https://github.com/Chisel-Team/Chisel/commit/1eff222d4137373a1ca763cfc1451772c3d65a5f
