### ISSUE TITLE
[1.12.2] IllegalArgumentException

### ISSUE THREAD

**Issue by SirTwsted** [Shinoow/AbyssalCraft#253]
https://pastebin.com/sAGTJ9xu

Minecraft v1.12.2
Forge v14.23.1.2555
AbyssalCraft v1.9.4.2
AbyssalCraft Integration v1.6.2

**Comment by trogarus** [comment]
Same as https://github.com/Shinoow/AbyssalCraft/issues/252 and also reported at Chisel https://github.com/Chisel-Team/Chisel/issues/591

**Comment by Shinoow** [comment]
Duplicate of #252
