### ISSUE TITLE
Abyssalcraft 1.12.2 - Forge 14.23.1.2581 - Change Model Manager

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Shinoow/AbyssalCraft#254]
Full Log
https://gist.github.com/P3rf3ctXZer0/9cb96c50f0b6df5a53b6732409631f98

Crash Log
https://gist.github.com/P3rf3ctXZer0/30de9c486541991f2b694e66baf04bec

**Comment by Shinoow** [comment]
I don't see how this is caused by AbyssalCraft.

**Comment by P3rf3ctXZer0** [comment]
Hm I will close this for now.
