### ISSUE TITLE
[1.12.2] [BUG] Mobs don't spawn in Abyssal Wasteland.

### ISSUE THREAD

**Issue by DesolateElf** [Shinoow/AbyssalCraft#258]
I would like to load my Staff of Rending to make the Abyssal Wasteland Essence, but I can not find any mobs of that, the dimension is no mob, the only thing I found was this: 
![2018-01-15_17 18 37](https://user-images.githubusercontent.com/33802990/34958968-3ddec754-fa1b-11e7-87ea-1b2cb4751274.png)

**Comment by Shinoow** [comment]
You have a mod installed that's wiping the biome spawn list of the dimension (should've been the same thing with the Overworld biomes, provided the mod in question is Custom Mob Spawner). Find out which mod it is, then do whatever config changes required for it to not modify the biome spawn list(s).

**Comment by DesolateElf** [comment]
I do not know what happened but the last time I went to play, I was not with this problem anymore. Maybe it worked out because I increased the monster generation rate of a mod called Blood Moon. 
Custom Mob Spawner might even be responsible for the problem but I do not understand why it would have been solved by itself, and I did not change anything in the mod.

**Comment by Shinoow** [comment]
I'll take it this issue has been rectified, but in the event mob spawning ceases again, track down which mod is tampering with the mob spawn lists, then look for information about how to configure it (or reach out to it's dev if it comes down to that).
