### ISSUE TITLE
Possible Bug / Query

### ISSUE THREAD

**Issue by lxkm** [Shinoow/AbyssalCraft#26]
Is it intentional that Sacthoth's sword is an Item rather than ItemSword?

Wondered after trying to enchant it earlier with weapon-only enchants, which naturally doesn't work =) I presume it isn't a bug if this is intended behaviour.

**Comment by Shinoow** [comment]
Actually I'd say it was partially intentional, but generally I didn't really think about capabilities to enchant that weapon. If it's something you'd like me to enable, I could do so.

**Comment by lxkm** [comment]
It's cool with me this way. It's pretty darn powerful even without enchants! Will close issue for now. Also: thanks for the super fast reply!
