### ISSUE TITLE
Staff of Rending either crashes or just does nothing.

### ISSUE THREAD

**Issue by RexMontag** [Shinoow/AbyssalCraft#261]
#### Description:

Using AbyssalCraft along with 90+ other mods, mostly with no bugs aside from the CMS thing. Not a pack, just picked the stuff that seemed cool off the 1.12.2 compatible mod list on 9minecraft.

Singleplayer survival mode, if that makes a difference.

#### Crash report:

As noted in the title, using the Staff of Rending sometimes shuts down the server abruptly. It seems like maybe it happens the first time I try to use it on a given mob- if I use it on say a shadow creature, the server crashes, I reload, and then it works fine on shadows, but then if I try to use it on something else, it crashes again, etc. I think that resets when I cross dimensions, too, but I'm not 100% sure.

And sometimes it just does nothing at all- not even the little "wave" animation. Not sure what's up with that.

Sometimes it works for a good while, but lately not at all.

Oh, yeah, I tried it with both regular and Abyssal staff of rending, same problem.

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- AbyssalCraft: 1.9.4.4
- AC Integration: 1.6.2

Someone elsewhere mentioned maybe there's a clash with Botania (1.12.1), which I also have, but I don't know if it affects this specific thing.  

#### Latest log file for when the issue was present:

https://drive.google.com/file/d/1PYyGz9bqUEK5xsh_RxMkL4PqmyPCcbKQ/view?usp=sharing

I think this is the right file? Sorry, I've never reported a bug before.

**Comment by Shinoow** [comment]
The log mentions levelup2 on multiple occasions as part of stacktraces. Are you able to reproduce it without that mod installed?

**Comment by RexMontag** [comment]
Hm. Gimme a minute to figure out how to test that without losing the last 3 months worth of experience levels I have through that mod...

**Comment by RexMontag** [comment]
Yup. Still a thing. Here's the new log: 
https://drive.google.com/file/d/1PYyGz9bqUEK5xsh_RxMkL4PqmyPCcbKQ/view?usp=sharing

And I was able to restore my levels from backup, so phew!

**Comment by Shinoow** [comment]
I ran an instance with AbyssalCraft and Botania, and I was unable to reproduce it there, so Botania shouldn't be the cause of it.

**Comment by RexMontag** [comment]
Gtk, since I have a ton of Botania stuff I'd hate to give up. ^_^

With 90+ mods, I'm honestly amazed how *few* conflicts I've run into, although there are definitely a few small ones, and probably also some I'm not noticing. Also I added many post-worldgen, so there are elements that probably didn't seed properly.

**Comment by RexMontag** [comment]
Hm. The Bat Flute from Pet Bats also does not seem to work. Wonder if it's a related issue...

I'm going to try removing CMS later and see if that fixes any of the spawn issues I've been having, who knows, maybe it will fix this too?

**Comment by RexMontag** [comment]
UPDATE (on both of my issues, actually)
I took CMS out of the mods folder, and now I get regular mob spawns in the Abyssal Wastelands (and some MoCreatures, too, but maybe there's a way to tweak that? I'll post in the other thread.

As to the Staff issue, I tried using it on the newly spawning Abyssal mobs, and it seems to work on ab.zombies and depths ghouls just fine, it functions, it doesn't crash when switching between them, all good so far.

Only now it doesn't seem to work on shoggoths? When it worked in the past, it worked on shoggoths but not on ab.zombies, so I dunno if that's a clue or not.

**Comment by RexMontag** [comment]
Alright, I think I'm ok to call this one solved, the Staff of Rending works fine. Doesn't work on Shogs, but maybe it wasn't supposed to? I don't want to kill them anyway, so they can make those sweet, sweet statues for me.

If you want to close this ticket, I'm good.

I did want to ask though, are there supposed to be Advancements for AbyssalCraft? Cuz I don't have any. I mean, the Necronomicons give you a pretty good path to follow, so maybe we don't need them?

Anyway, thanks! Great mod, really enjoying it so far ^_^

**Comment by Shinoow** [comment]
Not too long ago the shoggoths were changed to use the identifier for Omothol mobs (previously they worked in all dimensions but Omothol), which also made them no longer possible to drain energy from in the Abyssal Wasteland and Dreadlands (but the ones in the Dark Realm can still be drained for producing shadow gems).
I had achievements before 1.12, but converting them into advancements hasn't been a high priority so far. When the time comes, advancements will show up in 1.12.

**Comment by RexMontag** [comment]
Good enough for me. Thanks for the heads up. Next stop: Dreadlands!
