### ISSUE TITLE
Abyssalcraft Crash when attempting to turn all Overworld Generation off

### ISSUE THREAD

**Issue by DJJBanx** [Shinoow/AbyssalCraft#262]
#### Intro:

I am trying to disable all Overworld generation, from Shoggoth Lairs, to Nitre Ore. I configured it all to be off and it crashes every time I attempt to start the game.

#### Description:

Ditto. 
I am running Forge 14.23.2.2617
I am running AbyssalCraft 1.12.2-1.9.4.4
I am running AbyssalCraft Integration 1.12.2-1.6.2

#### Crash report:

https://pastebin.com/b7Ddhc64

#### Config File that caused the crash

https://pastebin.com/TBA4sNhb

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.2.2617
- AbyssalCraft: 1.12.2-1.9.4.4

#### Latest log file for when the issue was present:

https://pastebin.com/Bmwhv6m8

**Comment by Shinoow** [comment]
I seem to have overlooked something in regards to how the biome disabling is handled internally. Until I have an update out to address this, re-enabling the Coralium Infested Swamp should stop the crashing.

**Comment by DJJBanx** [comment]
Thanks
