### ISSUE TITLE
Crash when using Mining spell on the bottom of a block

### ISSUE THREAD

**Issue by Efimero** [Shinoow/AbyssalCraft#265]
#### Description:

Using the Mining spell on the bottom of a block causes the server to lock up and the client to desync (ie, not kicked from singleplayer session, but can't drop items)

#### Crash report:

no crash log as the server hangs, but doesn't actually crash

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2611
- AbyssalCraft: 1.9.4.4

#### Latest log file for when the issue was present:

https://gist.github.com/Efimero/3a7887fc0e8f1d5f8c8f3e7f3ec32e88

**Comment by Shinoow** [comment]
That seems to be an infinite loop caused by the spells block tracking not stopping when looking for blocks to destroy, leading to it infinitely searching upwards (as air isn't something to destroy).

**Comment by Efimero** [comment]
so add a maximum distance of 256? =P
