### ISSUE TITLE
Trying to create Elytra with Materializer

### ISSUE THREAD

**Issue by Levitikan** [Shinoow/AbyssalCraft#267]
Been trying to create Elytra with materializer and the sometimes the icon for it disappears even though there is more than enough crystallized shards, I've onlyh been ablle to make a couple at a time when ive just logged in and not been on for a while. Would that be a Materializer or recipe bug?
AC version 1.9.4.3
MC 1.12.2

**Comment by Shinoow** [comment]
This was fixed in 1.9.4.4. Consider updating to that version.
