### ISSUE TITLE
[minor bug] Missing Texture error

### ISSUE THREAD

**Issue by EmanYm** [Shinoow/AbyssalCraft#27]
I get this in my console
[Client thread/ERROR]: Using missing texture, unable to load abyssalcraft:textures/items/eldritchscale.png

After looking through your source, I notice the .png is "eldrichScale.png" (https://github.com/Shinoow/AbyssalCraft/blob/master/src/main/resources/assets/abyssalcraft/textures/items/eldritchScale.png)

Case sensitive code!  yay! ^_^

**Comment by Shinoow** [comment]
I noticed that about 10 mins after releasing 1.8.2 for the third time (had a few cases of complete screw-ups around the release). If I finish the text I have left to write, I'll have the new version out today (can't promise anything).

**Comment by EmanYm** [comment]
No worries, Shinow.  It's not a game breaker, and I have made much worse errors in my day...I won't go into detail..
