### ISSUE TITLE
[1.12.2] Inquiry: Dread plague spreading

### ISSUE THREAD

**Issue by Yhuxz** [Shinoow/AbyssalCraft#272]
How does enchanting a weapon with dread plague and using it against mobs spread the plague? I know it can have a chance to spawn dread spawn causing the dread particles but the issue is how is it spreading below the ground even if I put the grinder above ground? Is it a bug or it is intentional?

Dread Stains on Darklands grass
![2018-04-04_00 23 22](https://user-images.githubusercontent.com/36140746/38283900-356ffe40-37eb-11e8-98ec-85d7d595f9b9.png)

AbyssalCraft v1.9.4.6
Forge v14.23.2.2611

**Comment by Shinoow** [comment]
The whole biome is being altered by the plague, which affects all Y-levels of the target area.

**Comment by Yhuxz** [comment]
Will it spread furthermore or that stain will remain the same?

**Comment by Shinoow** [comment]
As long as the plague has a host to travel by, it will spread further.

**Comment by Yhuxz** [comment]
Thanks for the respond :)

**Comment by Yhuxz** [comment]
(tell me if this needs a new issue or not)

Another question in mind is the Aklo Fonts being restarted every time I re log in the game/world. I mean every time I update a mod and relog to my survival world the game thinks I'm new and re-lock those unlocked scripts in the Necronomicon and JEI even just in my hotbar. progression-wise Im in the dreadlands and I always logged out in the overworld. Re entering the portals unlocks them again

**Comment by Shinoow** [comment]
That sounds like the information isn't syncing correctly to the client on world load (which I was pretty sure I already fixed). Might as well open a new issue for it.
