### ISSUE TITLE
[1.12.2] Aklo Font: Re-locks every time the game restarts

### ISSUE THREAD

**Issue by Yhuxz** [Shinoow/AbyssalCraft#273]
Aklo Fonts being restarted every time I re-log in the game/world. I mean every time I update a mod and relog to my survival world the game thinks I'm new and re-lock those unlocked scripts in the Necronomicon and JEI even just in my hotbar. progression-wise Im in the dreadlands and I always logged out in the overworld tho re-entering the portals unlocks them again.

**Comment by Yhuxz** [comment]
Tested back to v1.9.4.5 and it works but not in the v1.9.4.6

**Comment by Shinoow** [comment]
That's really strange, considering the code for handling the unlocking hasn't changed one bit in 1.9.4.6, but was changed in 1.9.4.5 to properly handle syncing.

**Comment by Shinoow** [comment]
Haven't been able to reproduce this for quite some time, closing the issue for now.
