### ISSUE TITLE
Dreadlands/Darklands - How to clean up?

### ISSUE THREAD

**Issue by unclekakarot** [Shinoow/AbyssalCraft#274]
#### Description:
This is more of a question than a bug, but how does one get rid of the Dreadlands/Darklands that has spread throughout the overworld from either the plaque or from the statues?

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- AbyssalCraft: 9.4.5

**Comment by Shinoow** [comment]
The Darklands can be reverted using the Ritual of Cleansing (available when you unlock the Abyssalnomicon). The Dread Plague can't be purified by any means (yet, there will be a thing for that later on).

**Comment by unclekakarot** [comment]
Dread Plaque can't? Damn that sucks, accidentally got that stuff everywhere on my base and it looks so ugly. Thanks for the info
