### ISSUE TITLE
Dreadlands is way overtuned

### ISSUE THREAD

**Issue by Valdevon** [Shinoow/AbyssalCraft#275]
Honestly I don't even understand how this is supposed to be possible.

The dreadguards tank 50+ hits from a 15 attack damage sword, they set you on fire whenever you attack them forcing you to stand in a pool of water the whole time, they give you a plague that you cannot cure until passing through the dimension that keeps refreshing itself and sometimes lasts 10+ minutes which is basically a death sentence.

I ended up standing in a hole in the ground with a 1 block gap and trying to lure them over to it so I could attack their feet, but it turns out they can also spray the plague on you through a wall so that's cool.

I entered this dimension with a fully enchanted set of armour and weapons from the previous dimension and I can't even kill a single mob. If there's something I'm missing it should be included in the book.

**Comment by mikemorana** [comment]
I experience the same frustration with the dread plague. Sometimes persists for 10+min. With other mods (i.e. Scaling Health allowing my to earn an increased health pool) its doable but I'd be frustrated enough to ditch the mod if it weren't for this consolation. Dreadguards also seem to be able to pass the plague to me through walls of dreadstone.
Cha'Garoth produced so many mobs while I danced around avoided the plague, that MC began to lag horribly despite my beefy computer.

**Comment by Iorce** [comment]
Use bows if possible. Material intensive but it works flawlessly.

**Comment by Quivelt** [comment]
I 100% agree with this but golden apples are there for a reason.
