### ISSUE TITLE
No Explosions, please

### ISSUE THREAD

**Issue by pingvikin** [Shinoow/AbyssalCraft#276]
Make please a config option to disable any Explosions in this mod.

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2655
- AbyssalCraft: 1.12.2-1.9.4.6.jar

**Comment by Shinoow** [comment]
If you don't want explosions, either disable mob griefing or keep some distance from a Coralium Infested Swamp. If you're referring to the explosives, don't stand next to them if you set one off.
