### ISSUE TITLE
Generation bug?? Smallest Darklands Mountain never see (1 chunk...)!

### ISSUE THREAD

**Issue by Fireztonez** [Shinoow/AbyssalCraft#277]
#### Intro:
Hello, I work now in a new modpack, and in a new Generation Test Word, and I see a little generation bug... A Darklands Mountain il 1 chunk, on the middle of a plain.... You can look the Print Screen, here:

![bigger-darkland-mountain](https://user-images.githubusercontent.com/19277301/38771949-5c64e9fe-3ffa-11e8-82f8-ae9e3299fbf0.png)

I use now the version 1.9.4.6 of AbyssalCraft...

I just want to specify, I'm not sure if the problem is from you mod, becose I use Now Quark Realistic  Terrain gen and Dimensional Control. But I prefer to send you that informations, pôssibly is can help you, if this is a bug from your side...

Thank you very mutch for your awesome work in that really nice Mod!!

AbyssalCraft: 1.9.4.6
Forge: 14.23.2.2645
Minecraft: 1.12.2
AbyssalCraft Integration: 1.6.2

**Comment by Shinoow** [comment]
Considering it's generating in the wrong temperature zone (Darklands Mountains is in the cold group, while Plains is in the warm), this could be a minor snag in the world generation logic, potentially due to the aforementioned mods.

**Comment by Fireztonez** [comment]
Hello Shinoow,
Sorry for the big delay before respond, we have completely forget that issue...

For reply, this is really interesting the fact of the biomes Temperature is completely different, because I use a script to make biomes generate in temperature band, similar to Sevtech, so, this is clearly not normal, but possibly not AbyssalCraft bug directly... I will see after all the update if is still happen in new worlds.

I wonder if the problem is not with the dimensional control ... Possibly this region would be supposed to be an AbyssalCraft mountain, but the dimensional control changes to be a plain, due to the realistic band generation... About that I can't really tel, because I don't really know how the biomes is generated in minecraft and with Dimensional Control...
