### ISSUE TITLE
Asorah immediatly despawns

### ISSUE THREAD

**Issue by nematrec** [Shinoow/AbyssalCraft#282]
#### Description:

Spawning Asorah close enough to the abyssal gateway will cause him to immediately despawn, Occasionally he goes through the portal and spawns in the overworld.

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.32669
- AbyssalCraft: 1.9.4.8

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by ZombieEnderman5** [comment]
That's strange...

**Comment by Shinoow** [comment]
That sounds more like he's flying into the portal, being teleported to the overworld rather than despawning. As of a couple of updates ago mobs can use the portals as well, and assuming he can get in contact with the block, he's teleported.

**Comment by nematrec** [comment]
Originally I thought some of them were despawning, but I found the rest of them as I got closer to 0,0 (Yay for Dragon AI)

Perhaps give them a grace period after summoning before they can go through portals?

**Comment by Shinoow** [comment]
Seems like I forgot to close this issue nearly 3 months ago. Anyways, portal cooldown is set to max whenever something is summoned through a ritual.
