### ISSUE TITLE
Can't respawn bug

### ISSUE THREAD

**Issue by pingvikin** [Shinoow/AbyssalCraft#284]
#### Intro:

If the player sleeps on the bed, breaks the bed, and then he dies, the button will be revived in the menu becomes inactive, and such an error will be displayed in the log

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.3.2655
- AbyssalCraft: 1.9.4.8
- Sponge: 1.12.2-2655-7.1.0-BETA-3058

#### Latest log file for when the issue was present:

https://gist.github.com/pingvikin/235e4e85eb7b3732a1a5a9d92e956ec3

**Comment by Shinoow** [comment]
In what biome were the player when this happened? What biome is the spawn point in? Can you reproduce this without sponge?

**Comment by pingvikin** [comment]
In what biome were the player when this happened? 
Plaints/Forest
What biome is the spawn point in?
Plaints/Forest
Can you reproduce this without sponge?
Yes

**Comment by Shinoow** [comment]
Can you give me the stack trace on that? The bug happening without Sponge, that is.

**Comment by pingvikin** [comment]
Sorry, this is sponge bug
I was wrong, sorry :)

**Comment by Shinoow** [comment]
This was fixed in 1.9.4.9.
