### ISSUE TITLE
Abyssalcraft mobs and spawning - Dimension spawning not working

### ISSUE THREAD

**Issue by MokahTGS** [Shinoow/AbyssalCraft#289]
Can someone please help with this spawning issue? I'm trying to get Abyssalcraft Shadow creatures to spawn in the Beneath dimension and can't get it to work. I have Depths Ghouls spawning just fine, but for some reason the Shadow Beasts won't spawn.

Currently I'm using the InControl mod to try and spawn them, but I don't know if there is some internal AC code that is blocking the spawning.

https://github.com/McJty/InControl/issues/60

This is the post I made on the InControl issue page that has the .json files I'm using.

**Comment by Shinoow** [comment]
No special code. They spawn like any other mob.
