### ISSUE TITLE
Latest Version of Forge - [Crash]

### ISSUE THREAD

**Issue by EndermanParty** [Shinoow/AbyssalCraft#29]
I am using forge version - 10.13.3.1370 and your mod is having a fluid registry error - If need be I can upload as crash

**Comment by Shinoow** [comment]
I've read about a overhaul in the fluid registry, so this will be adressed when I update to the latest forge.

**Comment by Shinoow** [comment]
Fixed in AbyssalCraft 1.8.5

**Comment by EndermanParty** [comment]
Thank you - That fixed it.
