### ISSUE TITLE
J'zahar's explosion blow up the blocks even when MobGriefing was set to false...

### ISSUE THREAD

**Issue by VioletWyvern** [Shinoow/AbyssalCraft#292]
When defeated J'zahar,  His self explosion still blow up the blocks even when MobGriefing was set to false, this makes a huge, gigantic hole at his Omothol castle **_(And I must repaired it by my self to rebuilding the broken wall)_**, Why this explosion can't be turn-off for damaging the world?

**Comment by Shinoow** [comment]
I seem to have missed putting a gamerule check there.

**Comment by VioletWyvern** [comment]
Nope,  I'm sure /gamerule MobGriefing was set to false...

**Comment by VioletWyvern** [comment]
Oops... sorry about that....
