### ISSUE TITLE
[Question] [1.12.2] Biome IDs

### ISSUE THREAD

**Issue by Sanofus** [Shinoow/AbyssalCraft#293]
Hello,
I want to prevent generation in the Abyssal Biomes, but I cannot find the specific IDs of the Biomes. Would you mind helping me?

**Comment by Shinoow** [comment]
Overworld biomes?
`abyssalcraft:darklands`
`abyssalcraft:darklands_forest`
`abyssalcraft:darklands_plains`
`abyssalcraft:darklands_hills`
`abyssalcraft:darklands_mountains`
`abyssalcraft:coralium_infested_swamp`

**Comment by Sanofus** [comment]
Overworld exactly. Thanks you.
