### ISSUE TITLE
[Suggestion] Show encrypted content in Creative mode

### ISSUE THREAD

**Issue by Bulldog83** [Shinoow/AbyssalCraft#294]
Hello. Please, make the encrypted content displayed in creative mode. I'm doing my own set of mods and it's not convenient after each re-creation of the world to discovery the encrypted content of the mod to look for id blocks or items.

**Comment by drakray** [comment]
there is a command to unlock everything, /acunlocksomething, if I recall correctly

**Comment by Bulldog83** [comment]
Oh. Thank you, I didn't know.
