### ISSUE TITLE
[1.12.2] Major memory leak caused by AC attempting to spawn an entity

### ISSUE THREAD

**Issue by SadChimera** [Shinoow/AbyssalCraft#295]
To elaborate, Abyssalcraft makes an attempt to spawn an entity but fails. Then it pauses the game, saves, unpauses and attempts to spawn said entity again. It repeats this until you get far enough away from the area that it doesn't make the attempt anymore. Originally thought it was a personal problem, but I've verified at least 4 other players who have had the exact same problems as I have.  
  
Since it doesn't force a crash, I'd have to get a live log and I'm unfortunately not able to do so at this time. Seems incredibly easy to recreate the issue though, if you're within mob-spawning distance of an AC biome then you can potentially catch the framerate drop associated with the bug.  
  
Throwing this issue up via mobile since no one has posted in the past week after we discovered the problem.

**Comment by Shinoow** [comment]
Please use the issue template when reporting a bug.
