### ISSUE TITLE
Duplicate Language key with some mods

### ISSUE THREAD

**Issue by TartaricAcid** [Shinoow/AbyssalCraft#296]
There are some dupliacte language key with other mods.
`tile.crate.name`
- Abyssalcraft: `Wooden Crate`
- MrCrayfish's Furniture Mod: `Crate`
- Harvestcraft: `Crate`

`item.staff.name`
- Abyssalcraft: `Staff of The Gatekeeper`
- Roots: `Staff`

`item.cloth.name`
- Abyssalcraft: `Washcloth`
- Bionisation3: `Cloth`

`item.coin.name`
- Abyssalcraft: `Coin`	
- Thaumcraft: `Gold Coin`

**Comment by Shinoow** [comment]
Oops. Might not be in the next planned release (since it's gonna include deprecating 1.10.2 and 1.11.12), but after that's out I'll refactor the localization to properly namespace the blocks and items.
