### ISSUE TITLE
[Suggestion][1.12.2] Option to disable Dreadlands Spread

### ISSUE THREAD

**Issue by Mike-U5** [Shinoow/AbyssalCraft#297]
Unlike some people, I was fine with the Darklands-spreading PE mechanic since there are rituals to clean it up. 
This is not the case for Dreadland Spread. Once a chunk is Dreadlands, it's ruined forever. All you can do is do the purge ritual, but Purged Lands are just as bad. So an option disable the spread of this would be very helpful.

Alternatively, add a way to restore Dreadlands chunks.

**Comment by zerotheliger** [comment]
I second this. Its extremely annoying to deal with and im about ready to just uninstall the mod. Apparently its a wide spread annoyance.

**Comment by CosmicGlowsticks** [comment]
Agreed, it's really annoying. It's only happening on one world for some reason but either way it's annoying.
