### ISSUE TITLE
[Bug] Abyssal Wasteland and Dreadlands turn into Overworld duplicate + Dreadlands oxygen bug?

### ISSUE THREAD

**Issue by DatFurry** [Shinoow/AbyssalCraft#299]
#### Description:
I had just managed to get Asorah's Dreaded Gateway Key, so I tried it out and went to the Dreadlands. But then I encountered a big message saying "WARNING: NO OXYGEN DETECTED". I assumed it was probably Advanced Rocketry thinking it was a planet, so I returned to the Overworld to make myself some Oxygen gear. When I returned again, both the Dreadlands and Abyssal Wasteland completely turned into regular stone, with patches of other Overworld things like grass and red sand. Dreadland mobs were also spawning in this normalized Abyssal Wasteland, and the biomes would switch between Abyssal Wasteland and Dreadlands. I think it might have been Advanced Rocketry screwing with the dimensions, but I don't really know because I haven't tested the mod out yet, only held it ready for when I do feel like it. 

(Note: Restarting the game seems to have fixed the major issue with the dimension, but the Dreadlands still has the "No oxygen" overlay on the screen while slowly killing me...)

#### Crash report:

----

#### Affected versions:
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2705
- AbyssalCraft: 1.9.4.10

#### Latest log file for when the issue was present:
First part:
https://pastebin.com/1NTV3hNZ
Second part:
https://pastebin.com/9pGgb1UF

**Comment by ZombieEnderman5** [comment]
The "No Oxygen Detected" warning is probably Advanced Rocketry... Although, if you have Galacticraft, that will also give you a warning if you don't have correct oxygen gear. I think GC says "Oxygen Setup Invalid" though.

**Comment by DatFurry** [comment]
I don't have GC installed in this run, since I thought 2 space mods would be overkill and had yet to try Advanced Rocketry. Either way though, it looks like I'll just have to use oxgen gear, regardless if I'm in space or not.

**Comment by Shinoow** [comment]
Like ZombieEnderman5 says, the "No Oxygen Detected" is caused by Advanced Rocketry. Can't say I remember the specifics entirely (a little searching on the web should show a plethora of results), but it's something along the lines of AR having a range of dimension IDs which it intends on using for planets, and the ID range I use for my dimensions (eg 50 - 53) just so happens to be within the aforementioned range. A little config tweaking in AR should solve it.
