### ISSUE TITLE
Stack bugs..

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Shinoow/AbyssalCraft#30]
These "* on a plate food" and MRE are bugged. They stack up to 4, but if you consume while having a stack of 4 in your hand, all 4 are consumed, and only 1 plate is returned.

**Comment by Shinoow** [comment]
That's a derp on my end. Can you check with the other food items added by the mod? I have a feeling this might occur on some of them as well.

**Comment by Unrepentant-Atheist** [comment]
It does.
