### ISSUE TITLE
Chisel & Bits compatibility

### ISSUE THREAD

**Issue by jacob814** [Shinoow/AbyssalCraft#300]
With your mod popularity ever growing and the fact you have great textures for your blocks, can I suggest having Chisel+bits compatibility? Its easy enough to do with the instructions layed out by the chisel+bits mod author here: https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.12/src/main/java/mod/chiselsandbits/api/IgnoreBlockLogic.java#L18

I have read up on the instructions and dont think it would be difficult to implement. I would do a pull request but I am unfamiliar with forge. This request might be harder than it appears but I still ask for you to consider this option.

Thank you.

Edit: Forgot to make a descriptive title and am unable to edit it on my phone as of now. Do forgive me.

**Comment by Shinoow** [comment]
I reckon most blocks should already work with it. Do you have any examples of blocks that currently can't be manipulated with it?

**Comment by jacob814** [comment]
Not me but at 6:30 timestamp https://youtu.be/RoA9CmsCrZk
