### ISSUE TITLE
Unable to activate ritual of the sleeper.

### ISSUE THREAD

**Issue by MatthewSmit** [Shinoow/AbyssalCraft#301]
#### Intro:

I am unable to activate the ritual of the sleeper in the Abyssal Wastelands.

#### Description:

I believe I have followed the instructions to the letter, yet shift-right clicking the alter does nothing.
I'm using a modified FTB Revelation pack which doesn't appear to change any abyssalcraft recipes.
I am in the abyssal wasteland dimension. I activated the ritual creating the transmutation gem just before, 
4 Gold Ingots.
1 Bucket Liquid Coralium.
1 Enchanting Table.
1 Transmutation Gem.
Centre and one pedestal empty.

Shift Right-Click with the Abyssal Wasteland Necronomicon. 9840 PE (also tried when it was at 10K)

There is nothing in the debug log around the time of activating the alter.

![abyss](https://user-images.githubusercontent.com/1002815/43261428-bccf7c32-9130-11e8-8228-ad7ad998403b.png)
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: forge-14.23.4.2739
- AbyssalCraft: 1.9.4.10

#### Latest log file for when the issue was present:

[latest.log](https://github.com/Shinoow/AbyssalCraft/files/2231813/latest.log)

**Comment by Shinoow** [comment]
That ritual would never show up in JEI in the first place, since my JEI integration only shows rituals that output an item.
Anyhow, this is caused by Astral Sorcery, as it adds another NBT tag to the bucket, which the ritual didn't expect (as the bucket instance it's looking for doesn't have any additional tags after the one that specifies the liquid contained).

**Comment by MatthewSmit** [comment]
The Amount tag? It seems strange Astral Sorcery would add that, considering buckets are always 1000mb worth.
Are you planning on fixing it on your end by ignoring extra tags, or should we take this to Astral Sorcery and see if they can modify how they change the bucket?

**Comment by Shinoow** [comment]
It's not the amount tag. AS attaches a capability to the bucket (see https://github.com/Shinoow/AbyssalCraft/issues/302#issuecomment-408251756). Judging by that comment, this affects other mods as well (Thaumcraft is used as an example there).
This is on their end, and there's probably already something in the issue tracker about it.

**Comment by wamc2017** [comment]
There was some issues with Thaumcraft and Astral Sorcery in the past with version prior 1.9...
I tried to play around with crafttweaker a little bit and it seems like if I remove the nbt sensitivity from the rituals, everything works fine, but I guess now I could use any bucket...
