### ISSUE TITLE
Crafting Recipe Bug for Making a Transmutator

### ISSUE THREAD

**Issue by Convergence2738** [Shinoow/AbyssalCraft#302]
#### Description:

Crafting Recipe bug making the Transmutator. Putting all the proper materials in the crafting grid and it does not want to output a transmutator machine. Posting some pics for a more visual look at the bug.

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- AbyssalCraft: 1.9.4.10

#### Latest log file for when the issue was present:
![20180726131306_1](https://user-images.githubusercontent.com/36319508/43286083-7c43c238-9110-11e8-84f1-513f3bed2cc2.jpg)

![20180726131312_1](https://user-images.githubusercontent.com/36319508/43286091-83a70972-9110-11e8-9a41-09fbace35b97.jpg)

![20180726131323_1](https://user-images.githubusercontent.com/36319508/43286098-8743d204-9110-11e8-8702-3e31549854e3.jpg)

**Comment by wamc2017** [comment]
Works fine with only AbyssalCraft on my side... Do you got other mods installed? Maybe Astral Sorcery? It broke some research in Thaumcraft, because it added empty nbt tags to things some time ago, maybe it's an similar issue...

I guess the bucket is the problem, do other things like the Helmet of the Depths ritual work?

**Comment by Shinoow** [comment]
There was another bug recently discovered with that recipe (minor snag in my recipe implementation that ignored the metadata wildcard on the Transmutation Gem), but that tag just about guaranteed breaks it, as the bucket is nbt sensitive in the ritual, and it's not expecting it to have any additional tags apart from the one that specifies the liquid.

**Comment by wamc2017** [comment]
Is there anything you could do on your side, or should this be reported to ASs issue tracker?

**Comment by Convergence2738** [comment]
Yeah, I am willing to bet it’s the bucket. If it broke the sleeper ritual, it isn’t surprising that it broke the transmutator recipe. I will just go through all the recipes involving the coralium bucket and see if they fail too.
