### ISSUE TITLE
Inquiry: How exactly does Dread Plague Spread work? 

### ISSUE THREAD

**Issue by Convergence2738** [Shinoow/AbyssalCraft#303]
I wanted to ask about the dread plague spread because I am leerily about how easily it can spread. From what I understand it spreads from the plague clouds produced by killed dread infected mobs and the infection: goes down to bedrock from the point of spread. 

Which leads me to the more important part of my question. Does the Dread Plague enchantment spread the dreadlands when mobs inflicted with the enchantment debuff are killed (because that would kill any desire to use that enchantment for anyone aware of it).

**Comment by Mike-U5** [comment]
The Dread-Plague enchantment is now effectively a [curse](https://minecraft.gamepedia.com/Curse). 
It's going to be a negative effects in almost every situation.
So **do not use it if you care about your world at all.**

Same thing goes for the Dreadium Tconstruct parts btw.

**Comment by wjrogers** [comment]
Was this just added in today's update? Does this destroy my world? Does anyone have a full explanation of what's going on here? I'm 100% not interested in any mod feature that destroys things I have spent my limited free time building.

**Comment by Convergence2738** [comment]
Well, this was an inquiry in to how exactly dread spread (lol the rhymes) works. Dread plague now spreads only when you get two infected entities next to each other and one gets the upgraded plague (plague 2), Otherwise it doesn't spread. The dreadland purge ritual also works better and covers more ground

**Comment by wjrogers** [comment]
How can entities get plague 2? Is this something that can happen while I'm minding my own business, building away in my base? Or do I have to trigger it via some specific AbyssalCraft feature?

**Comment by Convergence2738** [comment]
if two entities infected from the plague come close, there is a chance the plague worsens and goes to tier 2 plague. Most noteably if something dies with plague, makes a plague cloud, and another infected entity goes through it and voila chance for plague to worsen.

**Comment by wjrogers** [comment]
Right, I got that from the earlier discussion. What I don't know is when, why, and how that happens. Assume I know nothing about AbyssalCraft except that I heard it was cool, so I threw it in the modpack I use to play casually with a friend who likes Lovecraftian horror. I've now come across this issue where someone says,

> So a single "lucky" crit can easily dreadify the entire world.

I'm trying to make a decision about whether to take drastic action (like removing AbyssalCraft from my modpack) to prevent my entire world from getting dreadified. Do I need to do that? Or can I take some in-game action to guarantee it won't happen to my world?

**Comment by Convergence2738** [comment]
the dread enchantment procs on crits, so you can avoid any problems by not using the enchantment or dreadium tinkers weapons (they have automatically). And it isn't a problem so long as you just keep the infected area lit as you need dread mobs to spawn first before the plague can spread further. 

Also don't walk out of the dreadlands with the plague. that's also how it spreads. It isn't hard to contain so long as you don't play with fire.

**Comment by Mike-U5** [comment]
As of today's update, the Dread Plague has been nerfed a bit.
You now need **Dread Plague II** in order for it to spread.
