### ISSUE TITLE
Dreaded gateway key leads to Abyssal Wasteland

### ISSUE THREAD

**Issue by chevrelune** [Shinoow/AbyssalCraft#306]
#### Description:

After creating Asorah's Dreaded gateway key and right clicking the ground, it just makes another Abyssal portal (same location as the other)

#### Affected versions:
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- AbyssalCraft: 1.9.4.10

**Comment by Shinoow** [comment]
Did you use it in the Abyssal Wasteland?

**Comment by chevrelune** [comment]
It does nothing when used there

**Comment by chevrelune** [comment]
Well, forgot I had Blood Magic installed as well. Uninstalled it, now the key works. Strange.
