### ISSUE TITLE
Ritual of Cleansing doesnt work

### ISSUE THREAD

**Issue by ToserBan** [Shinoow/AbyssalCraft#307]
#### Description:

I play the sevtech modpack and I´m using the latest version of abyssalcraft. I tried to change back the chunks where my base is, because some mobs escaped from my mobfarm and turned a part of the chunks to dreadland. Unfortunately the Ritual of cleansing didnt work. I used 8 random statues, the abyssalnomicon with 100000PE and a cow on top of the altar as sacrifice. After trying without success I used MCedit to turn back some chunks to plains. But that cant be the solution.

#### Crash report:

no crash
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge:
- AbyssalCraft: 1.12.2.1.9.4.11

**Comment by Shinoow** [comment]
That's not the ritual for getting rid of Dreadlands, the ritual of cleansing gets rid of Darklands. For Dreadlands, it's the ritual of purging.

**Comment by ToserBan** [comment]
Ok, i tried it and it worked, thanks. Just a question, it is not possible to turn a purged biom into the former, for example plains biom ? Because if i stand on a purged biom and look into the sky, the sky is white while the normal sky is blue. It could be irritating if this happens in someones base. I tested both rituals now very far away from my base so thats no problem for me.

**Comment by Shinoow** [comment]
That's not possible. When a Dreadlands biome is purged, you're left with the Purged biome.
