### ISSUE TITLE
Abyssalite ore nonexistend?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Shinoow/AbyssalCraft#31]
Is abysallite ore supposed to be nonexistend beloy y=32 in Darkland Forests? I can't seem to find any....I've found some corralite though in the ocean.

**Comment by Shinoow** [comment]
Abyssalnite generates in all Darklands biomes (Darklands, Darklands Plains, Darklands Forest, Darklands Highland and Darklands Mountains) below Y = 32. The ore has the same rarity as Emerald ore, but it can generate in clusters with up to 4 ore blocks (as of AbyssalCraft 1.8.5).
