### ISSUE TITLE
More granular configuration options for blocks to conserve IDs/RAM

### ISSUE THREAD

**Issue by asiekierka** [Shinoow/AbyssalCraft#313]
Since we have Chisels & Bits already, I'd like to avoid redundancy on an already heavy pack.

In particular, I'm thinking of the stair, slab and wall variants of AbyssalCraft blocks. However, any options useful for us at BTM are more than welcome.

**Comment by Shinoow** [comment]
With the ID shifts caused by removing a block from an existing world, not to mention potential structures where the block might be incorporated, it might be easier if I just make a custom BTM version where redundant blocks are gone by default.

**Comment by asiekierka** [comment]
>With the ID shifts caused by removing a block from an existing world

This is meant to be a configuration option. Besides, last I checked 1.12 doesn't have ID shifting issues?
