### ISSUE TITLE
Crafting Recipe Conflicts

### ISSUE THREAD

**Issue by KittenKoder** [Shinoow/AbyssalCraft#315]
#### Description:

Vanilla recipe for wooden trapdoors and pressure plates conflict with ALL wood recipes.

#### Crash report:

No Crash
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2705 (latest stable)
- AbyssalCraft: 1.9.4.11

#### Latest log file for when the issue was present:

N/A

**Comment by Shinoow** [comment]
Not all of them, stairs still work.
Nonetheless, I hadn't taken the change vanilla did to the fence recipe into account. Pressure plates and buttons might require the planks to be removed from the Ore Dictionary, since that's what currently allows the recipe to be overridden by vanilla.

**Comment by KittenKoder** [comment]
If you convert to the new Json recipe structure, it could be repaired on the fly by anyone with relative ease. It was the first thing I looked for so I could make a temp fix for my own server.

**Comment by Shinoow** [comment]
Closing this for now. There are still some wooden blocks whose recipes are being overridden by vanilla, but all crafting recipes have been JSON recipes for quite some time now.
