### ISSUE TITLE
Missing localization for JEI fuels

### ISSUE THREAD

**Issue by Lykrast** [Shinoow/AbyssalCraft#316]
#### Description:

The JEI categories for Transmutator and Crystallizer Fuel are displaying raw localization keys, and also not displaying the actual burn time of the fuels, as seen here:

![image](https://user-images.githubusercontent.com/8684850/44139052-37d5f858-a076-11e8-9240-a30a14dd91d0.png)
![image](https://user-images.githubusercontent.com/8684850/44139058-3d23d38e-a076-11e8-9ba8-38bd0e8ae251.png)

----

#### Affected versions:
- Minecraft: 1.12.2
- Forge: 14.23.4.2747
- AbyssalCraft: 1.9.4.11

**Comment by Shinoow** [comment]
Yeah, discovered in #309.
Seems like JEI changed the localization keys a couple of updates ago.

**Comment by mcBegins2Snow** [comment]
I crated a pr #314
