### ISSUE TITLE
JEI Display problem

### ISSUE THREAD

**Issue by BadLucKWyvern** [Shinoow/AbyssalCraft#317]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

JEI description is bugged for most items

#### Crash report:

Don't have any

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: forge1.12.2-14.23.4.2757 and before
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.4.12 and the version before that one

#### Latest log file for when the issue was present:

its a permanent effect

![image](https://user-images.githubusercontent.com/17027691/44961651-0a7df100-af15-11e8-9437-c13a1b95ed61.png)

**Comment by BadLucKWyvern** [comment]
Some more exemple below
![image](https://user-images.githubusercontent.com/17027691/44961682-68aad400-af15-11e8-9df2-c6cac0ac33a3.png) No
![image](https://user-images.githubusercontent.com/17027691/44961685-6d6f8800-af15-11e8-807a-3fb3ea642de5.png) Yes
![image](https://user-images.githubusercontent.com/17027691/44961687-76f8f000-af15-11e8-95f4-badd5884ef1c.png) No
![image](https://user-images.githubusercontent.com/17027691/44961692-84ae7580-af15-11e8-98c4-4bdd0b317021.png) Yes
![image](https://user-images.githubusercontent.com/17027691/44961701-9b54cc80-af15-11e8-9acd-ec6b59b1b794.png)No

**Comment by wamc2017** [comment]
That's intended, if you progress further, the item informations will unlock...

**Comment by OrdnungsHirsch22** [comment]
http://abyssalcraft.wikia.com/wiki/Obtaining_Knowledge_(Necronomicon)

**Comment by BadLucKWyvern** [comment]
Damn... i didn't know it didn't had that feature when i played before :l 
sorry for stupid thread :S
