### ISSUE TITLE
Client crash on reading Necromicon

### ISSUE THREAD

**Issue by Bulldog83** [Shinoow/AbyssalCraft#321]
#### Description:

Crash occurred when I flipped through the pages of basic rituals. Now when I try to open the Necromicon crash happens again.

#### Crash report:

https://gist.github.com/Bulldog83/e2092fbdc71fd059f09236fa138acc73

----

#### Affected versions:
- Minecraft: 1.12.2
- Forge: 14.23.4.2747
- AbyssalCraft: 1.9.4.12

**Comment by Shinoow** [comment]
@AlekseiVoronin Can you go over the Russian translation and check that none of the ritual descriptions exceed 368 characters. I think it might be line 729.
