### ISSUE TITLE
Server Crash when entering 1st Dimension Portal

### ISSUE THREAD

**Issue by preflora** [Shinoow/AbyssalCraft#322]
Sorry in advance if this is the incorrect place to post about this.
I made a custom modpack that includes Abyssalcraft for my multiplayer server. The server crashes whenever we try and go through the first portal to the first dimension. When trying to rejoin the server it just crashes again so we had to delete our player data. Is this a compatibility issue or something I can fix? 

Crash report:
https://pastebin.com/NZzfm0zP
----
- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- AbyssalCraft: 1.12.2 -1.9.4. 12

**Comment by Shinoow** [comment]
That's a minor thing that shouldn't happen, but due to circumstances it did. Will be fixed in the next update. Right now it's pretty much don't go in there or downgrade to 1.9.4.11.
