### ISSUE TITLE
crash issue when entering portal

### ISSUE THREAD

**Issue by NekoAthena** [Shinoow/AbyssalCraft#324]
#### Description:

This error crashes our server when we enter a portal and it begins to load the dimension.

#### Crash report:

(https://pastebin.com/Cu9xA0K6)

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- AbyssalCraft: 1.9.4.12

**Comment by Shinoow** [comment]
Duplicate of #322
