### ISSUE TITLE
Odd interaction with Kathairis dimension mod

### ISSUE THREAD

**Issue by EmergentCapulin** [Shinoow/AbyssalCraft#328]
An oddity I found while running this mod with Kathairis.  For some reason Abyssalcraft Shoggoths, Depths Ghouls, Abyssal Zombies, and Dr. Orange spawn in abundance during the night and anywhere there is shadow in the Kathairis dimension.  I'm not sure what is causing this - but to the best of my knowledge, none of these creatures are spawning in other dimension mods that we have added.  Again, not sure if this is an Abyssalcraft or Kathairis issue.  Just thought I'd bring it up to both parties just in case.

**Comment by Shinoow** [comment]
That's on their end. The mobs spawn due to their biomes being in the same Biome Dictionary group as some of the biomes they can spawn in.

**Comment by EmergentCapulin** [comment]
Interesting.  Sorry to necro the closed thread, but just tonight I noticed
the same thing happening in a Mystcraft world, but I don't see all of those
Abyssalcraft creatures spawning naturally like this on the overworld.  Is
there possibly a restriction on spawn rates on dimension 0 that is
loosened  in those grouped biomes on different dimensions?  (Genuinely
curious)
