### ISSUE TITLE
[suggestion] darkwood doors?

### ISSUE THREAD

**Issue by Seth0067** [Shinoow/AbyssalCraft#329]
have always wanted to see these in mc, the new remake has inspired me and i think you may understand the request:  

![door_darkwood_upper](https://user-images.githubusercontent.com/22122348/47820812-df006280-dd1b-11e8-921a-7fec1fa60fbf.png)
![door_darkwood_lower](https://user-images.githubusercontent.com/22122348/47820799-d3ad3700-dd1b-11e8-9042-42126065a343.png)
![door_darkwood](https://user-images.githubusercontent.com/22122348/47820805-d871eb00-dd1b-11e8-960c-295be0d4700a.png)

Inspiration:
![suspiria-doors](https://user-images.githubusercontent.com/22122348/47821407-d14bdc80-dd1d-11e8-849f-aa99c8c79411.jpg)

**Comment by Hypsellis** [comment]
It looks nice. You could make dreadwood door too. ;)

**Comment by Seth0067** [comment]
i would be happy to, if Shinoow gives the tentacles up.

**Comment by cybercat5555** [comment]
I decided to touch up the texture a bit, fixing some of the anti-aliasing issues

[https://i.imgur.com/f2PMfTl.png](url)

Hopefully you like em

**Comment by Seth0067** [comment]
awesome.  i sent Shinoow a dread door as well:  

![door_dreadwood](https://user-images.githubusercontent.com/22122348/51644878-a7721280-1f26-11e9-9103-9e3c79537606.png)
![door_dreadwood_lower](https://user-images.githubusercontent.com/22122348/51644880-a93bd600-1f26-11e9-83b6-e6d0ffe9932f.png)
![door_dreadwood_upper](https://user-images.githubusercontent.com/22122348/51644881-a9d46c80-1f26-11e9-8cfd-7101feec11c2.png)

feel free to edit away, but make sure @Shinoow has the right files if/when he chooses to add...

**Comment by Seth0067** [comment]
Oh, @cybercat5555 I love your wall/damask block from the above screenshot. Are you going to release those blocks?

**Comment by cybercat5555** [comment]
Yep @Seth0067 , I just need to get a few things fixed such as the names and sounds before a public release though, but my name on Curseforge is the same as it is here, is case you want to check up on it.

**Comment by Seth0067** [comment]
good job! love it!
