### ISSUE TITLE
[Issue]Enchantments not showing on dreadium katana.

### ISSUE THREAD

**Issue by Draconian4466** [Shinoow/AbyssalCraft#335]
#### Intro:

Enchantments not showing on the Dreadium katana
#### Description:

when I enchanted the dreadium katana with sharpness 5 it showed 15 damage on it but it didn't show the enchantment.
#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge:14.23.5.2796
- AbyssalCraft:AbyssalCraft-1.12.2-1.9.4.14

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by GinkREAL** [comment]
Not sure if it is intended, but enchanting table doesn't work. Books and anvil work though
