### ISSUE TITLE
AbyssalCraft::AbyssalCraftEventHooks_damageStuff

### ISSUE THREAD

**Issue by RainOfPain125** [Shinoow/AbyssalCraft#337]
#### Description:

I doubt the modpack devs can do anything about this, sooooooo :)

Modpack: All The Mods 3

I did a timings report, and AbyssalCraft::AbyssalCraftEventHooks_damageStuff is causing considerable lag

#### Crash report:

Timings report - https://timings.aikar.co/?id=4e87304b77804c1ba4c07bd30de39137
https://i.imgur.com/hyEP7hS.png

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2768
- AbyssalCraft: 1.12.2-1.9.4 13.jar

#### Latest log file for when the issue was present:

Log is way too large for any of those websites
[2019-01-20-1.log](https://github.com/Shinoow/AbyssalCraft/files/2777313/2019-01-20-1.log)

**Comment by Shinoow** [comment]
Do you have a mob grinder running on the server? That's about the only logical conclusion I can come with as to why a lot of mobs would be getting attacked (which is the event the above event listener is tracking) within a short time span.

**Comment by RainOfPain125** [comment]
> Do you have a mob grinder running on the server? That's about the only logical conclusion I can come with as to why a lot of mobs would be getting attacked (which is the event the above event listener is tracking) within a short time span.

A single, small mob spawner with 4 spawners can cause this much lag? Imagine scaling that up with tons of players, and bases that want much larger, expansive spawners. Are you sure theres not a more efficient way to go about tracking attacking mobs..?

**Comment by Shinoow** [comment]
Closing this for now. I can't really do much more on my end when it comes to optimization (unless I straight up remove all of the relevant code, but that kinda defeats the purpose of said code).
