### ISSUE TITLE
Slabs missing oredict entries

### ISSUE THREAD

**Issue by Mon732** [Shinoow/AbyssalCraft#339]
#### Description:
Slabs such as the darkwood slab are missing their respective oredict entries. Stopping the items from being used in recipes that require slabs.

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- AbyssalCraft: 1.9.4.14

**Comment by Shinoow** [comment]
Good catch! Also noticed I hadn't put my wooden fence blocks in the Oredict either.

**Comment by Hypsellis** [comment]
I suppose it's the same for stairs, walls, fences, and fence gates.

**Comment by Shinoow** [comment]
AbyssalCraft doesn't add fence gates.

**Comment by Hypsellis** [comment]
Oh I thought it did, anyway it would be a nice thing to add. ;)
