### ISSUE TITLE
Ticking Entity Crash when doing a Sacrifice Ritual

### ISSUE THREAD

**Issue by newcodher** [Shinoow/AbyssalCraft#340]
#### Description:

I was doing a sacrifice ritual for the Oblivion Catalyst. I had 5000 PE for the craft, so as it begun, everything was going normal, until the lightning. When lightning struck the cow I had put to sacrifice, server crashed.

The ritual/cow was on slabs if that has anything to do with it, I don't know.

#### Crash report:

https://pastebin.com/B4PiXq5s

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- AbyssalCraft: 1.9.4.15
- AbyssalCraft Intergration: 1.6.6

**Comment by Shinoow** [comment]
Huh, seems to be a minor snag on my end that only happens under specific circumstances. It shouldn't crash every time, but from the looks of it there's a smallish chance the game crashes when you fail a ritual. Will have a fix for this in the next update!
