### ISSUE TITLE
Portal looping v1.9.4.15

### ISSUE THREAD

**Issue by Hasseloe** [Shinoow/AbyssalCraft#341]
#### Intro:

I am running abyssalcraft on a server and whenever I try to enter the first portal I am caught in a portal loop where I am sent back and forth between the overworld and first dimension until I either crash or get randomly (very infrequently) spit out in either dimension. I have tried setting the portal cooldown to max and it has not worked. I am currently on the latest version. 

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2
- AbyssalCraft: 1.9.4.15

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
Did you set the portal max on both the client and server (as opposed to only on the client)? Does the server log print anything out of the ordinary when you go through the portal? Do you have additional mods running, and is that mod count of a considerable size? Do you have a good connection to the server?
The last time I had a report of portal looping where I was able to reproduce it was before the portal cooldown option was added (around the same time the handling code in the portal block was also changed, which helped stopping it from happening).

**Comment by Hasseloe** [comment]
Had only done it on client. Fixed the issue by setting the portal max to 300 on server as well. Thank you :)

**Comment by katyejackson** [comment]
How do you find the portal max and change it? I've been looking for it on my server but can't seem to find it.

**Comment by Shinoow** [comment]
What you're looking for is the "Portal cooldown" config option. Setting that to its max value (300) will alleviate portal looping, if you are experiencing that.

**Comment by teeZgit** [comment]
sorry to bring up an old thread, but i am on the same version with the same issue, and i cannot find a portal cooldown option?

**Comment by Shinoow** [comment]
Did you check under general in the AbyssalCraft config file, or in the config GUI (whichever of them you might be using)? Because the option is there, and the name of it is "Portal cooldown".

**Comment by teeZgit** [comment]
i’m actually using a different mod but i just assumed it was universal but i can’t find one for divinerpg

**Comment by Shinoow** [comment]
No, this is a config option in AbyssalCraft for its portals. If DivineRPG doesn't supply a configurable value for portal cooldowns, then you'd be better off asking them to add one.
