### ISSUE TITLE
Client crash in multiplayer

### ISSUE THREAD

**Issue by Goju-Sulfam** [Shinoow/AbyssalCraft#342]
[please forgive me if my spelling is wrong, English is not my native language]

#### Description:

I am in the process of updating my server and the associated modpack.

Before, I run AbyssalCraft-1.12.2-1.9.4.11 with forge-1.12.2-14.23.4.2705 and everything was running fine.

Now, I try to run forge-1.12.2-14.23.5.2768 with updated mods and I have client-side crash when an AbyssalCraft mob spawn or is loaded from the map (seen with Depth Ghoul and Lesser Shoggoth). The problem exists with AbyssalCraft-1.12.2-1.9.4.11, but also with AbyssalCraft-1.12.2-1.9.4.14 and AbyssalCraft-1.12.2-1.9.4.15

Strangely, the client crash only with a copy of my server map, if I run the server with a new map I don't have problem apparently. I don't crash my client if I spawn manually some Depth Ghoul or Lesser Shoggoth in the server and the map run fine if I load it in client. If I spawn one of this mob with the client and load the map with the server, I crash my client at connection.

So, I am a bit confused and I don't understand why this crash is happening. I don't know if the problem is with AbyssalCraft or if it's an incompatibility with another mod, my test or the error itself doesn't help me much.

#### Mod List:

This is my precedent client mod list : https://pastebin.com/vSgX4bF9
This is my precedent server mod list : https://pastebin.com/Kq3jFGkP

This is my updated client mod list : https://pastebin.com/hb3xCNzx
This is my updated server mod list : https://pastebin.com/2A7ZRUgf

Note : I have "Sponge" server-side and "Better FPS" and "FoamFix" client-side. I have tried without these mods, the client is crashing as well.

#### Crash report:

Server-side log : https://pastebin.com/Y9ERKfhs
Client-side crash : https://gist.github.com/Goju-Sulfam/7a3c6140f24720dbb02d5347dad10eef

#### Affected versions ("latest" is **NOT** a version):

- Minecraft: 1.12.2
- Forge:  1.12.2-14.23.5.2768
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.4.11, but also with AbyssalCraft-1.12.2-1.9.4.14 and AbyssalCraft-1.12.2-1.9.4.15

**Comment by Shinoow** [comment]
The client-side log is not a crash report, and I can't see anything in either log that would explain this behavior.

**Comment by Shinoow** [comment]
Yeah, it seems like it should be on my end, but I have no idea how that code could be crashing (the part in question hasn't changed in several years). Only thing I can think of would be if something in Forge changed, but that might be a long shot.

**Comment by Goju-Sulfam** [comment]
I have made an instance of the previous version of the modpack/server and just updated forge (1.12.2-14.23.5.2768-universal),  ImmersiveEngineering (0.12-87) and ImmersiveCables (1.12.2-1.3.2).

Everything seems to run fine, the problem doesn't show in this configuration. So, I think it's a conflict with another mod. I will try to update all mod one by one.

**Comment by Shinoow** [comment]
Closing this for now. Feel free to re-open if necessary.
