### ISSUE TITLE
Ritual of Reversed Time not working with J'zahar throne broken

### ISSUE THREAD

**Issue by rosareven** [Shinoow/AbyssalCraft#343]
Maybe not a bug because I've heard that the ritual requires J'zahar's throne being intact to work. If the throne is broken by J'Zahar's death explosion, will the ritual work by rebuilding the throne by hand, or would we need a dim reset?

**Comment by Shinoow** [comment]
The ritual resets the whole temple, so you don't need to rebuild anything.

**Comment by rosareven** [comment]
This is a screenshot of the temple where a player performed the ritual. He had 40k PE.

https://i.imgur.com/iBDBiMK.jpg

He said he did it twice - there was no message from the ritual in chat, the items are gone, and PE didn't get spent. He had the right book, right items and the ritual only needed 20k PE.

It was on PO3.

**Comment by Shinoow** [comment]
> and PE didn't get spent
Does he have the book inside an Akashic Tome? Seeing as that's in the pack, I'm not entirely sure if having a Necronomicon combined in that will allow energy extraction/insertion to function properly. It's either that or he did something wrong.
Another possibility would be if he had another Necronomicon in his inventory that's empty. Depending on the order in which the inventory is scanned through for something to drain energy from, having multiple *nomicons in your inventory would have one come before the other, and it stops searching after the first one it finds.

**Comment by rosareven** [comment]
Thanks Shinoow. I do hate how PO3 seemingly messes up a lot of normal mod mechanics. I'll keep figuring it out.

**Comment by rosareven** [comment]
Weather update, the ritual is fixed by rebuilding the altar. No other ritual worked on that altar apparently.
