### ISSUE TITLE
So abyssal craft causing crash on the server and immense lag

### ISSUE THREAD

**Issue by D4rkHelix** [Shinoow/AbyssalCraft#345]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:
the shaggoths causing crash ho do we fix this

#### Crash report:
https://pastebin.com/R6mKxCS6

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:
- Forge:
- AbyssalCraft:

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
Fill in the template and provide the necessary information (and an actual crash report) in a new issue if you want help.
