### ISSUE TITLE
Issues with Terrain and Stuck as a Zombie

### ISSUE THREAD

**Issue by gladoscore** [Shinoow/AbyssalCraft#347]
#### Description:
So i played with this mod in 1.11.2 with no issues, but when i upgrade it and my other mods to 1.12.2, it seems abyssalcraft has a problem with terrain. the very first layer of all the overworld biomes is missing. structures and plants are just floating. also i seemed to have turned into an abyssal zombie, and im not sure why...

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- AbyssalCraft: 1.9.5.2

#### Latest log file for when the issue was present:

https://www.mediafire.com/file/2rl6d3t94d0lv44/2019-02-22-4.log.gz/file

Hope i did this right, let me know if theres anything else you need. I do play with multiple mods, but none of them should interfere with terrain gen. Played with mainly the same mods in 1.11.2 and no issues.

**Comment by Shinoow** [comment]
The missing terrain is because of changes I made to the 1.12.2 codebase that's incompatible with versions of the mod made for earlier MC versions.
The zombie part sounds like something caused by another mod. Do you have any mods installed that allows you to morph into mobs?

**Comment by gladoscore** [comment]
It maybe be caused by another mod, ill look into that! and ah, makes sense. Should i completely delete Abyssal craft and then reinstall it? (Sorry for late response too, real life sucks)

**Comment by gladoscore** [comment]
Yup, turning into a zombie was from one of my other mods. Seems that ones glitching out a bit. Im gonna try reinstalling Abyssalcraft and see if that fixes the terrain.

**Comment by Shinoow** [comment]
Regenerating already explored chunks would be the closest you can get to migrating those parts of the world to 1.12.2.
