### ISSUE TITLE
Reworking the achievements (suggestions wanted)

### ISSUE THREAD

**Issue by Shinoow** [Shinoow/AbyssalCraft#35]
The achievements in AbyssalCraft has been a mess for quite a bit, displaying some of the progression, but still not showing all of it. Mainly it hasn't showed advancement in weapon/armor/tool tiers, but there's generally a lack of achievements related to obtaining certain materials, which would give the user a greater sense on which "page" their at in the mod. One could say the Necronomicon has covered parts of this, but achievements would still give the player a feeling of how far they've ventured into the mod.
Now over to the reason I filed this issue: I want to rework the achievements, and I want suggestions for this (achievement chains, certain things that should be highlighted etc). If you have opinions on the achievements, post them here, I want any critique that can improve the line of achievements found in this mod.

Below here will be a theoretical achievement list, which will be updated with suggestions and my own ideas. It is likely that this is what the achievement chain will look like in the end. Most of these achievements are already in the mod, but some might be removed (and some will be added).

¤ = new achievement
§ = will be removed

# Achievements:
#### Welcome (obtain Darkstone):
* **Necronomicon:** ¤
 * Craft a Necronomicon ¤
 * Abyssal Wasteland Upgrade ¤
 * Dreadlands Upgrade ¤
 * Omothol Upgrade ¤
 * Abyssalnomicon ¤
* **Rituals:** ¤
 * Create a ritual altar ¤
 * Perform a Summoning ritual ¤
 * Perform a Creation ritual ¤
 * Perform a Breeding ritual ¤
    * Make a Shoggoth Infestation happen ¤
 * Perform a Potion ritual ¤
 * Perform a Area-of-Effect Potion ritual ¤
 * Perform a Infusion ritual ¤
* **Exploration (begins after a Necronomicon has been crafted):**
 * Enter Abyssal Wasteland
    * Kill Spectral Dragon
 * Summon Asorah (through ritual ¤)
 * Kill Asorah
 * Enter Dreadlands
    * Kill Dreadguard
 * Enter Cha'garoth's lair
 * Kill Cha'garoth
 * Enter Omothol
    * Enter Dark Realm
    * Kill elite mob found in Omothol ¤
 * Locate J'zahar ¤
 * Defeat J'zahar ¤
* **Gateway Keys:**
 * Craft Gateway Key
    * Obtain Dreadlands Infused Powerstone
 * Create Asorah's Dreaded Gateway Key (through a ritual ¤)
 * Transmute Dread-plagued Gateway Key into Cha'garoth's R'lyehian Gateway Key
* **Depths Ghouls:**
 * Killing:
   * Kill Depths Ghoul
    * Kill Pete §
    * Kill Wilson §
    * Kill Orange §
 * Heads:
   * Depths Ghoul Head
    * Pete Head
    * Wilson Head
    * Orange Head
* **Materials:**
 * Obtain Abyssalnite Ore
 * Obtain Coralium Gem
 * Obtain Shadow Gem ¤
 * Obtain Liquified Coralium Ore ¤
 * Obtain Abyssal Ores (iron, gold, diamond, tin, copper, nitre, one of them) ¤
 * Obtain Dreadlands Abyssalnite/Dreaded Abyssalnite ¤
 * Obtain Dreadium ¤
 * Obtain Ethaxium ¤
* **Machinery:** ¤
 * Craft Transmutator ¤
 * Craft Crystallizer ¤
 * Craft Engraver ¤
 * Craft Materializer: ¤
   * Craft a Crystal Bag ¤

**Comment by LiteraryRecluse** [comment]
The Necronomicons are very useful in game, and though it should be obvious after creating the first one that you should continue to upgrade them, I think adding a chain of achievements for each necronomicon upgrade would be a simple way of leading the player in that direction.

**Comment by Shinoow** [comment]
I added a list of achievements (implemented ones and ones that might be implemented), which will be updated whenever a suggestion is added, or if I get an idea.

**Comment by Shinoow** [comment]
All achievements that haven't implemented in the mod has been tagged with a "¤".

**Comment by Shinoow** [comment]
All listed achievements has been added/removed/altered.
