### ISSUE TITLE
[1.12.2] Anti-Ghouls and Anti-Abyssal Zombies don't burn in sunlight

### ISSUE THREAD

**Issue by Mike-U5** [Shinoow/AbyssalCraft#350]
Anti-Ghouls and Anti-Abyssal Zombies do not burn in sunlight like normal undead creatures do.

**Comment by Shinoow** [comment]
None of the Undead Anti-mobs do.

**Comment by Mike-U5** [comment]
If it's intentional then feel free to close this issue. :)
