### ISSUE TITLE
[1.12.2]Crystallizer copying items

### ISSUE THREAD

**Issue by heiseshuishan** [Shinoow/AbyssalCraft#351]
AbyssalCraft-1.12.2-1.9.5.4.jar
1.12.2-forge1.12.2-14.23.5.2815
![1](https://user-images.githubusercontent.com/33478233/54762994-24242300-4c30-11e9-9aa0-7547854269e9.gif)
Copy with Shift+mouse

**Comment by heiseshuishan** [comment]
8 changes to 4, other materials can also

**Comment by Shinoow** [comment]
Yeah, that's not supposed to happen. Good catch!

**Comment by heiseshuishan** [comment]
> Yeah, that's not supposed to happen. Good catch! Also, please use the issue template in the future.

I will pay attention to using the template next time.
