### ISSUE TITLE
[1.12.2] Lesser Shoggoths drop FPS and despawn quickly

### ISSUE THREAD

**Issue by Mike-U5** [Shinoow/AbyssalCraft#353]
#### Intro:
Firstly, looking at a Lesser Shoggoth drops my FPS by about ~15. If there's a bunch clustered together then this can be a bit painful.

Secondly, I tried luring some shoggots out of their lair and then ran away and observed them at a safe distance, hoping they would make some pillars.  
  
However, they popped out of existence. The first one disappeared after 10 seconds and the others despawned a bit later. 

#### Affected versions:
- Minecraft: **1.12.2**
- Forge: **14.23.5.2823**
- AbyssalCraft: **1.9.6**
_No mods used besides Abyssalcraft._

**Comment by Shinoow** [comment]
The despawning is vanilla behavior, so I don't think there's that much I can do about it.
The FPS drops are connected to the new model. I need to conduct more tests on that to see what can be done on that front.

**Comment by Mike-U5** [comment]
@Shinoow Hope something can be done. The FPS drops suck but that new model looks fantastic.

**Comment by pinkpig3777** [comment]
To clarify, Is this still an issue?

**Comment by Shinoow** [comment]
Yes, unless it magically fixed itself (which I highly doubt).
