### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by ReportBot9009** [Shinoow/AbyssalCraft#354]
#### Description:

As soon as I enter my world which I've been playing for ~20 hours or so, I crash immediately with the log below. I tried making a new world and got the same crash. The mod that lets you go back to the splash screen said it's Soot and Abyssalcraft. I posted this on Soot's git as well just in case.

#### Crash report:

https://paste.dimdev.org/poxoneragu.mccrash

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2815
- AbyssalCraft: 1.9.6

#### Latest log file for when the issue was present:

I restarted Minecraft and I think I lost the latest.

**Comment by Shinoow** [comment]
That seems to be on Soot's end. Try updating that mod (provided you're not already using the latest version of it) and see if that helps.
