### ISSUE TITLE
[1.12.2] Twilight Forest 

### ISSUE THREAD

**Issue by MokahTGS** [Shinoow/AbyssalCraft#355]
#### Description:

Getting a crash when entering the Twilight Forest.  Crash log is calling out Abyssalcraft.

#### Crash report:

https://paste.dimdev.org/ulexazeqas.mccrash

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2823
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.6

Full mod list: https://paste.dimdev.org/soxojaxuqa.md

**Comment by Andromander** [comment]
Can you check the config for AbyssalCraft regarding the Shoggoth Lair generation count (one for Swamp, one for Rivers)? It might be a negative number, and the random number generator cannot use a negative number.

**Comment by MokahTGS** [comment]
From the config:

    # Generation chance of a Shoggoth Lair in river biomes. Higher numbers decrease the chance of a Lair generating, while lower numbers increase the chance.
    # [range: 0 ~ 1000, default: 30]
    I:"Shoggoth Lair Generation Chance: Rivers"=0

    # Generation chance of a Shoggoth Lair in swamp biomes. Higher numbers decrease the chance of a Lair generating, while lower numbers increase the chance.
    # [range: 0 ~ 1000, default: 30]
    I:"Shoggoth Lair Generation Chance: Swamps"=30

**Comment by MokahTGS** [comment]
So switching the river generation back to 30 stopped the crash.  It doesn't like 0.

**Comment by Shinoow** [comment]
In that context, 0 is considered a negative number. A slight oversight on my end in regards to not taking into account that someone might set one of those options to 0.
