### ISSUE TITLE
Major game-breaking mod conflict

### ISSUE THREAD

**Issue by LiteraryRecluse** [Shinoow/AbyssalCraft#36]
I just discovered that if you play this mod (at least, versions 1.8.7 and 1.8.6.1) in combination with TheErebus-0.2b, the Abyssalcraft dimensions become completely broken.  No mobs spawn, no ores spawn, and you have a weird glitch where your levels disappear (but only visually, they come back once you earn more experience.)  Also, when in Abyss dimensions, Minecraft lists Erebus biomes on the debug screen (Fungal Forest, Elysian Fields, etc)

I was able to summon Asorah, but there were no spectral dragons.

This is a game-ending glitch for as long as The Erebus is installed, because you have no way of obtaining the items to progress further.

**Comment by Shinoow** [comment]
That sounds like a biome ID conflict. This should be resolved by switching biome IDs in the biome configuration section.

**Comment by olee** [comment]
I have the same problem.
The thing is, I checked for any biome ID conflicts in the server log, but there were none (there were some of other mods, but I already had fixed these.

**Comment by Shinoow** [comment]
Yeah... it's a biome ID conflict. I just set up a instance with AbyssalCraft 1.8.7 and Erebus 0.2b. At first all AbyssalCraft biomes inside the dimension were replaced by Erebus biomes (only exception being Omothol, which had the correct biome). Then I went into the config and changed the biome IDs, and after that no biomes were replaced.

**Comment by olee** [comment]
Could it be there is no error message to be found in the server logs about this conflict?
Also when I went around the world, I had Abyssal biomes (e.g., showing up as "Darklands Plains"), but it's just the mobs not spawning...

**Comment by olee** [comment]
I tried to reassign all biome IDs and *definitely* made sure there are *no* conflicts.
However I still have no moby spawning at all.
Please reopen this issue as it was not solved yet.

Even removing the Erebus mod does **not** fix this (I generated a complete new world after removing it). I don't know what could cause this so if you need more info, please ask.

**Comment by Shinoow** [comment]
I need a full list of mods.

**Comment by LiteraryRecluse** [comment]
I was able to reassign the biomes and it did indeed fix everything.  The weird thing is my NEI biome dump displayed different numbers than the ones that were actually used.  I believe Erebus and AbyssalCraft were overlapping in the 101-105 area.  I just opened both config files at the same time and compared them side-by-side.

I still have the weird issue with my experience bar going blank when changing dimensions until I collect an XP orb though.  It's just a minor display glitch though.

**Comment by Shinoow** [comment]
I will be closing this issue, as the original issue (with the Erebus mod) has been resolved.
@olee you should see if you have any mod installed that alters mob spawning (JAS, Just Another Spawner, or CustomMobSpawners are the ones I know off). If you have JAS, http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288431-just-another-spawner-jas-v0-14
If you have CustomMobSpawners, I'd rather recommend removing it, since I've never seen that mod working well with mods adding biomes.
If you still run into issues with mob spawning, file a new issue.

**Comment by olee** [comment]
Oh the hint with CustomMobSpawners might be the solution.
I noticed some other spawning being messed up as well so that might be the reason!
Thanks a lot and sorry for bothering you.

**Comment by Shinoow** [comment]
No worries, always willing to help out someone in need.
