### ISSUE TITLE
Strange Portal Bug

### ISSUE THREAD

**Issue by SirAron111** [Shinoow/AbyssalCraft#360]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

Going into the portal (any portal) breaking it on the abyssal dimension side and placing a new one to get out you can’t get back into the portal from the over world even if you make a new one until by chance a mob walks into the one on the other side or you restart the server/single player.

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:Minecraft:1.12.2
- Forge:Forge 14.23.5.2836 (and lower (so on most of them))
- AbyssalCraft:AbyssalCraft-1.12.2-1.9.7.jar

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
I'm unable to reproduce this. Does it happen with AbyssalCraft alone, or in a modpack?

**Comment by SirAron111** [comment]
A i fixed it in my dev it was the portal cd not trigerring some thing messed with portal instant travle i removed that mod and your is ok now gonna close this forgot sry.
