### ISSUE TITLE
Crash/Freez: jzhar Black hole skill crashs if he cant find a dimension to send you to

### ISSUE THREAD

**Issue by SirAron111** [Shinoow/AbyssalCraft#361]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

If no dimension is set for the jzhar black hole skill it will simply cause a crash. You should fix this or make an option for the boss to use a special dimension for the teleport (a new one where the player has to get out of a labyrinth or something funny) since getting ported to dimensions like dimensional doors ones is buggy af and if the player ends up in the spectra dimension or the quantum quarry dimension this isn’t much fun. So in modpacks you have to use the blacklist and if you blacklist all the skill just crash the game.

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----o.k. I couldn’t get it to crash damn when I  need it to it won’t do it great (now it only freezes permanently but I can’t get a crash report like that only a client log so I put that down below)

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge:Forge 14.23.5.2836 (and lower (so on most of them))
- AbyssalCraft:AbyssalCraft-1.12.2-1.9.7.jar

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by SirAron111** [comment]
![2019-05-04_15 02 24](https://user-images.githubusercontent.com/39855956/57179387-b4839380-6e7d-11e9-88b8-2338730ab6e0.png)
Well sometimes everything just freezes (not much better thought)

**Comment by Mike-U5** [comment]
In all fairness, you could just whitelist one of abyssalcraft's own dimenions to avoid this issue entirely I'd think?

**Comment by SirAron111** [comment]
thats what i did i just wanted to inform you about the problem

**Comment by Shinoow** [comment]
> So in modpacks you have to use the blacklist

That's why the blacklist exists, to prevent the player from being teleported to a dimension they're either not supposed to enter, or which you're not supposed to enter in that manner. An oversight on my end was the possibility that someone would blacklist every single registered dimension.
