### ISSUE TITLE
Crafting conflict

### ISSUE THREAD

**Issue by nukaplays** [Shinoow/AbyssalCraft#363]
#### Intro:

Hi, I'm trying to use this with immersive engineering, and the crafting recipe for iron plates is the same as iron rods. 

Ideally, I'd be happy to just disable the plates but I'm not sure how. (would be nice to disable the food recipes in the config perhaps?)

if anyone knows of a way to fix this I'd really appreciate it!

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2814
- AbyssalCraft: 1.9.6

**Comment by Shinoow** [comment]
You can remove the recipes for the plates and the food through [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker?gameCategorySlug=mc-mods&projectID=239197). Alternatively, if you don't want to mess around with scripting, and just be able to craft the iron rods, [NoMoreRecipeConflict](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict?gameCategorySlug=mc-mods&projectID=238123).
