### ISSUE TITLE
Bug: Portals send me right back to the overworld

### ISSUE THREAD

**Issue by Spodershibe** [Shinoow/AbyssalCraft#367]
#### Intro:

Portals send me right back to the overworld when I step in them

#### Description:
I can still see the dimension I'm trying to go to for a split second, but it then sends me back no matter what I do. I have the portal delay set to the highest possible value (300). It would be nice to have the portal delay that happens when you go to the nether, and mods like aether classic and the betweenlands implement a similar thing.

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1815
- AbyssalCraft: 1.9.8

#### Latest log file for when the issue was present:

My server: https://www.dropbox.com/s/rve3i37kutyakse/debug%20%282%29.log?dl=0
my client: https://mega.nz/#!cJME0CCD!DAE7UOkW2O-_pPtii2jx4vAhPi3Mv4DO9BI-LMAf-Xc

**Comment by Shinoow** [comment]
Did you set the portal delay on both the client and server?

**Comment by Shinoow** [comment]
Closing this for now. I can't really conclude if this is because the portal delay hasn't been set on the server as well, or if it's a mod or plugin on the server that's causing this to happen.
