### ISSUE TITLE
The 1.14.3 port

### ISSUE THREAD

**Issue by Shinoow** [Shinoow/AbyssalCraft#374]
I haven't even set up a workspace for 1.14.3 yet, but this issue will contain a list of things that will be removed from the mod by the time it enters 1.14.3. I might find more useful information to convey here, but at a minimum a list of things that will go away (either die off completely or possibly become a separate mod if deemed useful enough on its own) will expand here over time.

Things that will be removed from the mod by the time it reaches 1.14.3:

- Plate food, MRE
- Iron Plates
- Washcloth
- Upgrade kits (might consider splitting it off into a separate mod)
- The Coralium and Dread enchantments (the plagues are contagious enough on their own)
- A bunch of config options (the config file is going to be overhauled in the port, so some options will likely die in the process, while new ones might be added)

Mechanics that will change in the mod by the time it reaches 1.14.3:

- The portals will be entities instead of "nether portal"-shaped (since having a portal that's shaped like the nether portal is so two thousand and late, and no longer socially acceptable regardless of how long your mod has been around)
- The gateway keys might switch to activating the portals through a ritual (or place down the vortexes)

Content-wise, there's a chance #371, #372 and #373 might not be finished in 1.12.2, but rather in 1.14. I think #264 will definitely fall under that category (considering a rework of the book contents around the port). #70 might also end up in that category (1.14 might be where I start putting some time into fleshing out the dimensions).

**Comment by Mike-U5** [comment]
I think the food items and upgrade kits are definitely fat (hah) that could be trimmed.
The Plates, Storage Crate and Upgrade Kits feel a bit out of place and would probably work better as a separate mod.

I'm curious if you intend to use Fabric for the 1.14 version?

**Comment by Shinoow** [comment]
Closing this since the porting has been put on hold since the end of last year.
