### ISSUE TITLE
Item  Name not lock in with applied energist

### ISSUE THREAD

**Issue by Fozkais** [Shinoow/AbyssalCraft#380]
#### Description:
there is a bug with the mod if have the use with applied energistic 2, if have put an item with the name of lock in the system applied the name is put like this it was unlocked in my case the item and the Lorem Ipsum. having absolutely not start the mod so as if I had just created a new world I still access the name of the item if I put it in my system applied
----

#### 
- Minecraft: 1.10.2
- Forge: 1.10.2forge1.10.2-12.18.3.2511
- AbyssalCraft: AbyssalCraft-1.10.2-1.9.4.11-FINAL + Integration1.10.2-1.6.3

[Image 1 : http://zupimages.net/viewer.php?id=19/29/y9as.png ]
[Image 2 : http://zupimages.net/viewer.php?id=19/29/vbos.png ]

**Comment by Shinoow** [comment]
Minecraft versions below 1.12.2 are no longer supported. I do believe the fix for #377 should cover this as well, but that's for 1.12.2.
