### ISSUE TITLE
[Suggestion] Add an option to restrict ODB explosion

### ISSUE THREAD

**Issue by tonalom** [Shinoow/AbyssalCraft#382]
Hello,

As this is not a bug I will continue without the template.

I am part of a team running a modded server that uses abyssalcraft, and it was discovered that the Oblivion Death Bomb makes a huge explosion when used, as intended. I had a look in the configs for abyssalcraft, but was unable to find a way there to disable the explosion. Disabling the item in the mod would restrict progress in the pack, so that cannot be done either.

Therefore I suggest the addition of an option to limit or restrict the explosion of the ODB to the "abyssalcraft.cfg" file be made.

Thank you!
-tonalom

**Comment by Shinoow** [comment]
Going by the same reasoning I did in #375, I don't see where you can't just disable the item. If the use of the bomb in the pack is to summon Sacthoth, you can just use the ritual that summons him instead, or use the crafting recipe that turns the bomb into a spawn egg (then again, something that disables an item would probably prevent it from being used in a crafting recipe).

**Comment by tonalom** [comment]
I get that. For now our solution was to disable the item from being placed, but still usable for crafting. Therefore only limiting what we wish. This suggestion is moreso to make the process of disabling the explosion less complicated, and for people who do not have access to the restrictions we use to be able to disable the explosion without the headache. I do understand your point of view, and agree to an extent, but having an option to disable the explosion (similiar to how antimatter-explosions can be edited) would simplify the process.
