### ISSUE TITLE
Bewitchment Incompatibility Crash with Abyssalcraft

### ISSUE THREAD

**Issue by MokahTGS** [Shinoow/AbyssalCraft#383]
Bewitchment mod has an incompatibility that they say has to be fixed on your end. 

#### Description:
Getting a crash with bewitchment-1.12.2-0.0.20.3 and Abyssalcraft with launching in SP.

Full Mod list: https://paste.dimdev.org/yamobucovu.md

Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Forge 2838
Baubles-1.12-1.5.2
bewitchment-1.12.2-0.0.20.3
Patchouli-1.0-20
AbyssalCraft-1.12.2-1.9.10
AbyssalCraft Integration-1.12.2-1.8.1

Logs, in the event of a crash
https://paste.dimdev.org/kaloqodufe.mccrash

Link to Bewitchment issue report: https://github.com/Um-Mitternacht/Bewitchment/issues/385

**Comment by Shinoow** [comment]
Update AbyssalCraft Integration, this was fixed in 1.9.0.

**Comment by MokahTGS** [comment]
Ah, thanks!
