### ISSUE TITLE
Lesser Shoggolth back part Show Unknown on HWYLA

### ISSUE THREAD

**Issue by Fireztonez** [Shinoow/AbyssalCraft#385]
#### Intro:
Hello, I really like the new 3d model for the shoggolth, really creepy, I like that!! But there have a new bug introduced with this new model when you look the entity with HWYLA (WAILA) or somes other mods showing entity informations... This is pretty anoying when you try to look how many heath point teh entity have, but you have bad time to get see because you saw the bad part of is body...

#### Description:
When you look the Lesser Shoggoth, the front part show correctly the entity information, but wen you look the back part of the entity, it show Unknown, with no information at all, but Unknown... Sincerely this is the first time I saw an entity how is show 2 different thing depend where I look it.

![shoggolth_hwyla_bug](https://user-images.githubusercontent.com/19277301/63000962-74e72300-be40-11e9-87d6-3829902ab770.png)

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- AbyssalCraft: 1.9.10

**Comment by Shinoow** [comment]
I'm not sure there's much I can do about that on my end. I will do some research on the matter, but this likely falls on the mod displaying the information not checking for multipart mobs, which leads to the "parts" not displaying the parent mod they're part of, resulting in unknowns.

**Comment by Shinoow** [comment]
Closing this for now. I don't know if there's much I can do on my end to alleviate it on my end.
