### ISSUE TITLE
Request - Config to disabled the Active Statues in Shoggolth Lare

### ISSUE THREAD

**Issue by Fireztonez** [Shinoow/AbyssalCraft#387]
#### Description:
Hello,
I work currently on a big long progress modpack, and found right now on somes Shoggolth Lare sometime 1 to 3 active Statue directlty availiable on Shoggolth Lare... I think this is little too easy to get the statue if you an locate directly on the world like that... Can you please add a config for being able to disable the access of active statue. I have no real problem with the access of decorative statue on the Lare, so this can stay, I have no issue with that...

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- AbyssalCraft: 1.9.11

Thank's
Fireztonez

**Comment by Shinoow** [comment]
I did not expect someone to actually complain about statues being easier to obtain without any shoggoth herding, but yeah, I can make that configurable.
