### ISSUE TITLE
Bone Meal Event in purged biomes

### ISSUE THREAD

**Issue by sk2048** [Shinoow/AbyssalCraft#388]
#### Intro:

Using bonemeal in a purged biome results in consumption of whatever item triggered the event, even when this might not necessarily be expected. For example, Blood Magic's Sigil of the Green Grove should probably not be eaten.

#### Description:

Allowing modpack authors control over the items which are consumed through a config option or only consuming bonemeal specifically would resolve this issue.

#### Crash report:

N/A

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- AbyssalCraft: Present as of Shinoow/Abyssalcraft@2bca6866e94459c88bb95357100697bb7fc50d52

#### Latest log file for when the issue was present:

N/A

See here: https://github.com/Shinoow/AbyssalCraft/blob/master/src/main/java/com/shinoow/abyssalcraft/common/handlers/PurgeEventHandler.java#L33-L39

**Comment by Shinoow** [comment]
Yup, unintended consequence. Will be fixed in the next update!
