### ISSUE TITLE
[1.12.2] Backpack & Abyssalcraft

### ISSUE THREAD

**Issue by GeumGQ** [Shinoow/AbyssalCraft#389]
#### Description:
Hello, I dont think It's a bug idk, but, when I try to craft IRON STICK (backpack-3.0.2-1.12.2) on the crafting table I got the iron plate from the abyssalcraft

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2838
- AbyssalCraft: 1.12.2-1.9.11

**Comment by Shinoow** [comment]
That's a recipe conflict. You can use [NoMoreRecipeConflicts](https://www.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict) to resolve it.
