### ISSUE TITLE
Cannot damage j'zahar in survival.

### ISSUE THREAD

**Issue by Meaningofautism** [Shinoow/AbyssalCraft#392]
I'm using a mod pack, however it wasn't originally in it. I'm using RL craft and don't know what mods conflict in case that is the bug. Anyway, while in survival I progressed through to omothol and reached j'hazar but couldn't damage him with ethaxium nor sacoth's blade. I can damage him in creative, however I have no intention of hitting a boss with 500 health if he kills me instantaneously each time I hit him. Nor do I wish to cheat just to progress. Can anyone help me?
- Minecraft: 1.12.2
- Forge: 14.23.5.2803
- AbyssalCraft:1.9.12

**Comment by Shinoow** [comment]
With AbyssalCraft alone, I can damage him just fine, so my bet is on something in that modpack is causing it. Since you've modified the modpack, you're unlikely to get any support from the modpack developer.

**Comment by Shinoow** [comment]
Closing this for now. I don't think there's much I can do on my end, as this seems to be an interaction with some mod present in that large modpack.
