### ISSUE TITLE
[1.12.2] Dupe with bags

### ISSUE THREAD

**Issue by bigenergy** [Shinoow/AbyssalCraft#399]
#### Description:

Dupe with bags.
We take the bag, put something in it, throw it out and sharply open its interface with the right mouse click.
We take things from the interface, pickup a bag and get X2 items.

See a video demo: https://youtu.be/uh4rN9-LABE

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847
- AbyssalCraft: 1.12.2-1.9.13.1

**Comment by Shinoow** [comment]
Regardless of how many times I throw the item and right click (even with a macro that does that with zero delay), I can't reproduce that. Judging by your video you seem to have some input lag, considering that the right click fires off before the item is thrown (even though by your instructions you throw the item before right-clicking).
Nevertheless, by commenting out some code I managed to somewhat recreate the circumstance of the bug.

**Comment by bigenergy** [comment]
You should check if the player has a bag before opening GUI.

**Comment by Shinoow** [comment]
I do that, twice. Both on the client and on the server. This somehow circumvented that.
