### ISSUE TITLE
Suggestions how to improve the dimensions

### ISSUE THREAD

**Issue by kutschkem** [Shinoow/AbyssalCraft#40]
Currently, Abyssalcraft is all about grinding mobs. First, you have to grind shadows (which you only find in certain biomes I think?), then you are mining a little in the Darklands, then you are grinding again in the Dreadlands. Fine with me, but these dimensions lack other things to do.

No suggestions for Overworld, I see your approach is grinding stuff in a specific biome. Keep in mind though that finding a specific biome is not always easy...

Darklands: Add spawners or something to the stronghold, it was really empty. I spent quite some time backtracking until I found the Powerstone, in which time I encountered a bunch of spectral dragons but not much else. There are lots of torches, I suppose that is on purpose to reduce spawning, but it was abit too succesful for my taste. The fight against Asorah could be better if she (he?) didn't fly away so much. That's ok for the Ender dragon (it heals and doesn't fly away all that far) and spectral dragons (no comment), but Asorah flew quite far before coming back, I basically had to hunt her down.

Darklands and Dreadlands: Please add some ores here, maybe get some inspiration from other mods that procedurally generate ores based on existing ones? I am thinking of DenseOres here. That way you can sprinkle a little more oregen in your dimensions. Especially the Dreadlands is annoying in that the only ore you can find is Abyssalnite, but that is already dropped in abundance by all the mobs there. You have nice ideas for biomes there, but it is completely empty. You just find yourself some montains, hope you get done with grinding soon, and then, you leave as soon as possible. Also, since you fight against so many mobs in these dimensions, it becomes an issue that the drops can't be used for much (you don't need tons of dreaded cloth, for example, and what do you do with tons of coralium plagued flesh). It would be nice to have more options what to do with all that.

Omothol: Very nice so far. The eldritch scales are completely useless after the first three, I suppose you have plans what to with these things?

Dark Realm beneath Omothol: The most grindy of all dimensions, there is literally nothing else there but shadows and Sactoth. That was the most crazy fight in all of my minecraft play time, blind against endless masses of shadows and somewhere Sactoth that comes into sight from time to time. I like it, but Sactoth is on me again right after I killed him, I am not sure but I think when I left I saw three (!) of him following me. Give  me a break from time to time, please ;-)

**Comment by Shinoow** [comment]
By this time (or earlier today) I would've had a reply for this, but I've been busy updating my laptop (installed a new SSD, so it's mostly been getting default software and drivers for everything).
At least I can say this, you got some good points there, and I'll provide you with my thoughts on the matter sometime later today.

**Comment by Hypsellis** [comment]
I think that  curruntly the 4 dimensions are really empty, dead and repetitive. It misses of content like different biomes with different plants, structures, blocks... Without it looks like huge dimension mod like Aether and BetweenLands. You should really work more on them, since they are supposed to be the main feature of AbyssalCraft. I think you can do really nice and interesting stuff on these 4 dimensions. ;)

**Comment by Hypsellis** [comment]
Another suggestion I can give too would be to potentially reunite Omothal and Dark Realm into one dimension, with Omothol islands spawning far up the dark realm floor. These 2 dimensions are supposed to be the same, I never really understood why they were separated, it makes the things more complex for nothing as much for you than for players. Many people don't understand that they have to jump from Omothol for going in Dark Realm, and so never go inside.

**Comment by Hypsellis** [comment]
I have another suggestion to integrate the darklands biomes in the dreadlands since these biomes are supposed to be native from this dimension, but maybe in a different way with abyssalnite stone and dirt. I would suggest too to add the same 5 variants than darklands for dreadlands forests biomes. And add too purified dreadlands moutains.

**Comment by kutschkem** [comment]
Closing as this is super old. I have no idea what the current situation with the mod is, but this issue is probably outdated.
