### ISSUE TITLE
Rendering Bug with Applied Integration

### ISSUE THREAD

**Issue by ym1025** [Shinoow/AbyssalCraft#403]
#### Description:

I right clicked on Applied Integration's Energy Interface,on GUI, I moved the cursor on the slot,Minecraft crashed.
And I re-joined the world, a little later,I had move server selection screen.

#### Crash report:

https://pastebin.com/pYAyMDcC
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge:14.23.5.2847
- AbyssalCraft:1.9.14

#### Latest log file for when the issue was present:

https://pastebin.com/kC0sdh7H (Just a little bit towards the end)

**Comment by Shinoow** [comment]
Either Applied Integration is rendering an empty tooltip, or the List containing the tooltip text is null (which it should NEVER be). Either way it shouldn't even try to render a tooltip if either of those things are happening (as there is no point in displaying an empty tooltip).

**Comment by Shinoow** [comment]
After further checking, this is on Applied Integration's end.
