### ISSUE TITLE
Complete Crash

### ISSUE THREAD

**Issue by synil890** [Shinoow/AbyssalCraft#404]
### this is the hastebin info:

---- Minecraft Crash Report ----
// Sorry :(

Time: 2019-12-25 00:08:57 EST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AbyssalCraft (abyssalcraft)
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.DamageSource.setDamageBypassesArmor()Lnet/minecraft/util/DamageSource;
    at com.shinoow.abyssalcraft.api.AbyssalCraftAPI.<clinit>(AbyssalCraftAPI.java:70)
    at com.shinoow.abyssalcraft.init.InitHandler.preInit(InitHandler.java:126)
    at com.shinoow.abyssalcraft.AbyssalCraft.lambda$preInit$0(AbyssalCraft.java:63)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at com.shinoow.abyssalcraft.AbyssalCraft.preInit(AbyssalCraft.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.14.6
  Java Version: 1.8.0_74, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 392579312 bytes (374 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 91 mods loaded, 91 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version             | Source                                           | Signature                                |
       |:----- |:-------------------- |:------------------- |:------------------------------------------------ |:---------------------------------------- |
       | LCH   | minecraft            | 1.12.2              | minecraft.jar                                    | None                                     |
       | LCH   | mcp                  | 9.42                | minecraft.jar                                    | None                                     |
       | LCH   | FML                  | 8.0.99.99           | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
       | LCH   | forge                | 14.23.5.2847        | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
       | LCH   | ivtoolkit            | 1.3.3-1.12          | minecraft.jar                                    | None                                     |
       | LCH   | bspkrscore           | 7.6.0.1             | [1.12]bspkrsCore-universal-7.6.0.1.jar           | None                                     |
       | LCH   | treecapitator        | 1.43.0              | [1.12]TreeCapitator-client-1.43.0.jar            | None                                     |
       | LCH   | jei                  | 4.15.0.291          | jei_1.12.2-4.15.0.291.jar                        | None                                     |
       | LCE   | abyssalcraft         | 1.9.14              | AbyssalCraft-1.12.2-1.9.14.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LC    | forgeendertech       | 1.12.2-4.4.22.2     | ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar    | None                                     |
       | LC    | adlods               | 1.12.2-1.0.6.2      | AdLods-1.12.2-1.0.6.2-build.0408.jar             | None                                     |
       | LC    | aether_legacy        | 1.4.4               | aether_legacy-1.12.2-v1.4.4.jar                  | None                                     |
       | LC    | animalium            | 0.3.8               | Animalium-0.3.8.jar                              | None                                     |
       | LC    | placebo              | 1.5.1               | Placebo-1.12.2-1.5.1.jar                         | None                                     |
       | LC    | apotheosis           | 1.12.4              | Apotheosis-1.12.2-1.12.4.jar                     | None                                     |
       | LC    | baubles              | 1.5.2               | Baubles-1.12-1.5.2.jar                           | None                                     |
       | LC    | atum                 | 2.0.16              | Atum-1.12.2-2.0.16.jar                           | None                                     |
       | LC    | quark                | r1.6-177            | Quark-r1.6-177.jar                               | None                                     |
       | LC    | autoreglib           | 1.3-32              | AutoRegLib-1.3-32.jar                            | None                                     |
       | LC    | bno                  | 1.12.2-1.0.4.0      | BasicNetherOres-1.12.2-1.0.4.0.jar               | None                                     |
       | LC    | bettercaves          | 1.12.2              | bettercaves-1.12.2-1.6.0.jar                     | None                                     |
       | LC    | biomesoplenty        | 7.0.1.2441          | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar    | None                                     |
       | LC    | guideapi             | 1.12-2.1.8-63       | Guide-API-1.12-2.1.8-63.jar                      | None                                     |
       | LC    | bloodmagic           | 1.12.2-2.4.3-105    | BloodMagic-1.12.2-2.4.3-105.jar                  | None                                     |
       | LC    | bloodmoon            | 1.5.3               | Bloodmoon-MC1.12.2-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LC    | bookshelf            | 2.3.573             | Bookshelf-1.12.2-2.3.573.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | ceramics             | 1.12-1.3.7          | Ceramics-1.12-1.3.7.jar                          | None                                     |
       | LC    | clumps               | 3.1.2               | Clumps-3.1.2.jar                                 | None                                     |
       | LC    | codechickenlib       | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | coralreef            | 2.0                 | CoralReef-2.5-1.12.2.jar                         | None                                     |
       | LC    | customspawner        | 3.11.4              | CustomMobSpawner-3.11.4.jar                      | None                                     |
       | LC    | cyclopscore          | 1.5.0               | CyclopsCore-1.12.2-1.5.0.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LC    | waila                | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
       | LC    | darkutils            | 1.8.226             | DarkUtils-1.12.2-1.8.226.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | defiledlands         | 1.4.3               | defiledlands-1.12.2-1.4.3.jar                    | None                                     |
       | LC    | dimdoors             | 3.0.9+287           | DimensionalDoors-3.0.9-287.jar                   | None                                     |
       | LC    | dimensionaledibles   | 1.3.1               | DimensionalEdibles-1.12.2-1.3.1.jar              | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LC    | doggytalents         | 1.15.1.4            | DoggyTalents-1.12.2-1.15.1.4-universal.jar       | None                                     |
       | LC    | dldungeonsjbg        | 1.12.10             | DoomlikeDungeons-1.12.10-MC1.12.2.jar            | None                                     |
       | LC    | mocreatures          | 12.0.5              | DrZharks+MoCreatures+Mod-12.0.5.jar              | None                                     |
       | LC    | dynamictrees         | 1.12.2-0.9.2        | DynamicTrees-1.12.2-0.9.2.jar                    | None                                     |
       | LC    | dynamictreesbop      | 1.12.2-1.4.1e       | DynamicTreesBOP-1.12.2-1.4.1e.jar                | None                                     |
       | LC    | mysticalworld        | 1.12.2-1.6.1        | mysticalworld-1.12.2-1.6.1.jar                   | None                                     |
       | LC    | endercore            | 1.12.2-0.5.72       | EnderCore-1.12.2-0.5.72.jar                      | None                                     |
       | LC    | enderio              | 5.1.51              | EnderIO-base-1.12.2-5.1.51.jar                   | None                                     |
       | LC    | enderiobase          | 5.1.51              | EnderIO-base-1.12.2-5.1.51.jar                   | None                                     |
       | LC    | enderstorage         | 2.4.6.137           | EnderStorage-1.12.2-2.4.6.137-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | erebus               | 1.0.30              | Erebus-1.0.30.jar                                | None                                     |
       | LC    | evilcraft            | 0.10.78             | EvilCraft-1.12.2-0.10.78.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LC    | evilcraftcompat      | 1.0.0               | EvilCraft-1.12.2-0.10.78.jar                     | None                                     |
       | LC    | extrautils2          | 1.0                 | extrautils2-1.12-1.9.9.jar                       | None                                     |
       | LC    | familiarfauna        | 1.0.11              | FamiliarFauna-1.12.2-1.0.11.jar                  | None                                     |
       | LC    | llibrary             | 1.7.19              | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LC    | fossil               | 8.0.3               | fossilsarcheology-8.0.3.jar                      | None                                     |
       | LC    | geolosys             | 3.0.2b              | Geolosys-1.12.2-3.0.2b.jar                       | None                                     |
       | LC    | glacidus             | 1.2.1               | Glacidus-1.12.2-v1.2.1.jar                       | None                                     |
       | LC    | goodnightsleep       | 0.2.2               | good-nights-sleep-1.12.2-v0.2.2.jar              | None                                     |
       | LC    | gottschcore          | 1.9.0               | GottschCore-mc1.12.2-f14.23.5.2768-v1.9.0.jar    | None                                     |
       | LC    | gravestone           | 1.10.1              | gravestone-1.10.1.jar                            | None                                     |
       | LC    | lycanitesmobs        | 2.0.4.2 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.4.2.jar                 | None                                     |
       | LC    | magma_monsters       | 0.3.0               | MagmaMonsters-0.3.0.jar                          | None                                     |
       | LC    | mantle               | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                         | None                                     |
       | LC    | metallurgy           | 0.2.2               | Metallurgy-4-Reforged-0.2.2.jar                  | None                                     |
       | LC    | millenaire           | Millénaire 8.0.0    | millenaire-1.12.2-8.0.0.jar                      | None                                     |
       | LC    | mist                 | alpha_c_09          | MistWorld_1.12.2_alpha_c_09.jar                  | None                                     |
       | LC    | mowziesmobs          | 1.5.4               | mowziesmobs-1.5.4.jar                            | None                                     |
       | LC    | multimob             | 1.0.5               | multimob-1.0.5.jar                               | None                                     |
       | LC    | mystcraft            | 0.13.7.04           | mystcraft-1.12.2-0.13.7.04.jar                   | None                                     |
       | LC    | natura               | 1.12.2-4.3.2.69     | natura-1.12.2-4.3.2.69.jar                       | None                                     |
       | LC    | yurtmod              | 9.5.2               | NomadicTents-1.12.2-9.5.2.jar                    | None                                     |
       | LC    | samsocean            | 1.0.2               | OceanFloor-1.12.2-1.0.2.jar                      | None                                     |
       | LC    | oreberries           | 0.5.0               | oreberries-1.12.x-0.5.0.jar                      | None                                     |
       | LC    | harvestcraft         | 1.12.2zb            | Pam's+HarvestCraft+1.12.2zf.jar                  | None                                     |
       | LC    | patchouli            | 1.0-20              | Patchouli-1.0-20.jar                             | None                                     |
       | LC    | primitivemobs        | 1.2.3a              | primitivemobs-1.2.3a.jar                         | None                                     |
       | LC    | progressivebosses    | 1.5.4               | ProgressiveBosses-1.5.4-mc1.12.x.jar             | None                                     |
       | LC    | reccomplex           | 1.4.7               | RecurrentComplex-1.4.7.jar                       | None                                     |
       | LC    | additionalstructures | 2.2.2               | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar | None                                     |
       | LC    | ruins                | 17.2                | Ruins-1.12.2.jar                                 | None                                     |
       | LC    | savemystronghold     | 1.12.2-1.0.0        | savemystronghold-1.12.2-1.0.0.jar                | None                                     |
       | LC    | simplecore           | 1.7.3.4             | simplecore-1.12.2-1.7.3.4.jar                    | None                                     |
       | LC    | simpleores           | 1.11.2.0            | simpleores-1.12.2-1.11.2.0.jar                   | None                                     |
       | LC    | treasure2            | 1.7.0               | Treasure2-mc1.12.2-f14.23.5.2768-v1.7.0.jar      | None                                     |
       | LC    | tropicraft           | 7.1.9.115           | tropicraft-MC1.12.2-7.1.9.115.jar                | None                                     |
       | LC    | twilightforest       | 3.9.984             | twilightforest-1.12.2-3.9.984-universal.jar      | None                                     |
       | LC    | undergroundbiomes    | 1.3.7               | UndergroundBiomesConstructs-1.12-1.3.7.jar       | None                                     |
       | LC    | vanillafix           | 1.0.10-SNAPSHOT     | VanillaFix-1.0.10-99.jar                         | None                                     |
       | LC    | waystones            | 4.0.72              | Waystones_1.12.2-4.0.72.jar                      | None                                     |
       | LC    | midnight             | 0.3.4               | themidnight-0.3.4.jar                            | None                                     |
       | LC    | thebetweenlands      | 3.4.9               | TheBetweenlands-3.4.9-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LC    | mysticallib          | 1.12.2-1.3.8        | mysticallib-1.12.2-1.3.8.jar                     | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
                                        
                                      ApotheosisCore (Apotheosis-1.12.2-1.12.4.jar)
                                        shadows.ApotheosisTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      midnight (themidnight-0.3.4.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.72-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
  GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.10.14' Renderer: 'Intel(R) UHD Graphics 617'
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Suspected Mods: AbyssalCraft (abyssalcraft)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.2
  OpenGL: Intel(R) UHD Graphics 617 GL version 2.1 INTEL-12.10.14, Intel Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz

**Comment by Shinoow** [comment]
This error makes no logical sense, so I can only assume that either one of the coremods you have installed is messing something up, or you have a corrupt jar file.
Also, please use the bug report template in the future, rather than just pasting the entire crash report.

**Comment by Shinoow** [comment]
Closing this for now. I think the source of the problem lies in one of the coremods, and would need to be fixed in whichever of them it might be.
