### ISSUE TITLE
Blacklist, Remove, or Modify?

### ISSUE THREAD

**Issue by Yourname942** [Shinoow/AbyssalCraft#406]
1) Is it possible to disable or blacklist the Iron Wall enchantment? 
    a) I am using thaumcraft and Botania, both which have items for knockback.

2) Is it possible to disable or blacklist the MRE?

3) Is it possible to either: 
    a) disable, blacklist the various types of "[insert food] on a plate"
    b) modify how much hunger that the various types of "[insert food] on a plate" gives?
    c) I am using Pam's Harvestcraft and these food items from Abyssalcraft are not balanced for it.

Thank you.

**Comment by Shinoow** [comment]
1. Not without using some additional mod. I wouldn't know what to look for, but there's probably some enchantment blacklisting mod somewhere
2 and 3. Disable them in the config.

**Comment by Shinoow** [comment]
If you can't find any enchantment blacklisting mod, you could use Game Stages. Simply create a "disabled" stage, lock the enchantment behind that stage (might need an addon for staging enchantments), then simply never give that stage to the player.
