### ISSUE TITLE
lesser dreadbeast going through walls when pushed

### ISSUE THREAD

**Issue by ios777** [Shinoow/AbyssalCraft#407]
Description:
I was trying to do a mobfarm when i noticed that this mob coud escape through the wall 

 Affected versions:
- Minecraft:1.12.2

- AbyssalCraft:1.9.13.1

**Comment by ios777** [comment]
take it more as a fun fact. I was repeating the shoggots's story lol.
I'll change my mob farm

**Comment by Shinoow** [comment]
Huh, good to know. Might have something to do with the mob size.
