### ISSUE TITLE
unsolvable potion id conflict

### ISSUE THREAD

**Issue by luffykick** [Shinoow/AbyssalCraft#41]
Installing the latest IC2 experimental alongside AbyssalCraft causes an unsolvable potion id conflict. Both mods do not allow configuration of potion ID's in their respective config files.

Solution--- add an option to tweak the potion ID.

**Comment by Shinoow** [comment]
An easier fix would be if the IC2 devs didn't hardcode the potion ID, and instead simply made sure that the potion was registered with a ID that isn't occupied. But I'll reimplement the potion ID configuration, and add a option to use the dynamic ID configuration whenever it's possible to use that without some mod hardcoding the potion IDs.
