### ISSUE TITLE
plated coralium helmet; night vision effect not working in other dimensions (._.)/

### ISSUE THREAD

**Issue by th3AkMiN** [Shinoow/AbyssalCraft#411]
I´ve made the plated coralium armor and only the night vision effect of the helmet don´t work in other dimensions, only in overworld, this is a bug or is intentionaly?

I have other mods whit diferents dimensions (also in nether didn´t work)  so I wanted to use it to avoid the use of night vision potions when fighting with bosses.

If isn´t intentional,how can I change it to work in all dimensions??

**Comment by Shinoow** [comment]
Yes and no. The night vision only triggers in "surface worlds", which the Overworld is, but not necessarily other dimensions.
I can add a a config option to toggle that behavior, so it works in all dimensions.

**Comment by th3AkMiN** [comment]
thanks for answer me, i´ll be waiting for that change!!!!!!
