### ISSUE TITLE
Pregen issue

### ISSUE THREAD

**Issue by MineyShadow** [Shinoow/AbyssalCraft#413]
#### Description:
During world pregeneration with the chunk pregenerator mod, Some chunks will generate differently (different biome) as long as JEID and Abyssalcraft are installed together. Using NEID/Vanilla + pregen + abyssalcraft works fine. Normal world generation is also fine with JEID.
![image](https://user-images.githubusercontent.com/37338176/74937495-fd590880-540d-11ea-96a4-91f57507a9bf.png)
![2020-02-20_18 17 19](https://user-images.githubusercontent.com/37338176/74937507-06e27080-540e-11ea-81ee-08c0a8f05585.png)

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- AbyssalCraft: 1.9.16

Other mods:
- Chunk+Pregenerator+V1.12-2.2
- JustEnoughIDs-1.0.3-48
- preview_OptiFine_1.12.2_HD_U_F6_pre1

**Comment by Shinoow** [comment]
I don't see how my mod causes this, considering I don't alter the way biomes generate in the Overworld (the only thing AbyssalCraft does to the biome generation is adding the biomes to the list of possible biomes to generate).

**Comment by MineyShadow** [comment]
Well I tried adding and removing mods around, I ended up tracing it back to this mod, I didin't notice it with other mods such as Biomes O Plenty, Maybe it's just cause of the 1.13 format that JEID has. In a previous version of JEID, pregen was not working properly after all.

**Comment by twardy95** [comment]
I have the same issue but with Traverse mod installed. Some chunks are relocated or "sheer cliffs" occurs.

**Comment by Shinoow** [comment]
Closing this for now, but if someone can pin down what needs to change on my end to solve it (assuming there is something that needs to be changed on my end), please drop the information.
