### ISSUE TITLE
[Suggestion][1.12] Spell config

### ISSUE THREAD

**Issue by ace10102** [Shinoow/AbyssalCraft#414]
It would be wonderful to be able to enable/disable various spells in config, or modify their effects/what they can effect.
Prime example would be to be able to disable the detachment spell, or disable it being able to target players for multiplayer servers that may not want players to be capable of stealing items from each other

**Comment by Shinoow** [comment]
I think currently the Life Drain spell is the only one that takes pvp being enabled into account prior to damaging other players on servers, but that should apply to more of the offensive spells.
But sure, I can add config options to disable spells.
