### ISSUE TITLE
Interdimensional Cage Blacklist Ignored

### ISSUE THREAD

**Issue by Hydraheads** [Shinoow/AbyssalCraft#416]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

The interdimensional cage blacklist in the config does not seem to be working at all. Even though it seems to accept stuff such as minecraft:horse, for instance, the horse can still be captured with cages. 

Furthermore, the config options regarding the oblivion death bomb dont seem to work either.

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.16.jar:

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
Seems like the blacklist check is using the legacy ID rather than the "modern" one, which is what it should be comparing.
Could you provide me with examples of what you set the config options regarding the oblivion deathbomb to? They seem to be working just fine for me.
