### ISSUE TITLE
Materializer Crash

### ISSUE THREAD

**Issue by Cazadorsniper** [Shinoow/AbyssalCraft#418]
#### Intro:
Crash reported to me by a PO3 tester when they were trying to create saplings.

#### Description:

"Had another crash today, this time while using the Materializer from Abyssalcraft, I was trying to make the last 2 saplings I needed for the bonsai pots simple achievement which seem to only be obtainable using the Materializer, I'd put the necronomicon in the machine, moved the crystals into the bag then tried to shift click the bag into the machine. The crashed happened as I did that, it also crashed again when I tried to access the machine after reloading the world."

#### Crash report:
https://pastebin.com/PqWSq6pb
https://clips.twitch.tv/CoyAnimatedFinchBCWarrior
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- AbyssalCraft: 1.12.2-1.9.16

**Comment by Shinoow** [comment]
Replicating the video, I'm unable to reproduce it, but judging by my code, this crash is caused by an edge case I accidentally created which only happens when there's more than 110 available recipes to display in the GUI.
