### ISSUE TITLE
The sky in the Darklands is bright yellow

### ISSUE THREAD

**Issue by Zachary2897** [Shinoow/AbyssalCraft#425]
#### Description:

The sky in the Darklands biome is bright yellow, even though the sky in all of its variants (ex. Darklands Highland, Darklands Forest, etc.) is black. This appears to be happening because the Darklands is using its water color as its sky color.

![2020-04-29_18 17 29](https://user-images.githubusercontent.com/64550833/80652629-519fea80-8a46-11ea-8f76-2b933ce6f979.png)

![2020-04-29_18 15 42](https://user-images.githubusercontent.com/64550833/80652651-5bc1e900-8a46-11ea-9a5a-3c066d4be89c.png)

![2020-04-29_18 16 14](https://user-images.githubusercontent.com/64550833/80652654-5ebcd980-8a46-11ea-8274-32bee5b7d525.png)

This appears to be the cause of the issue (in https://github.com/Shinoow/AbyssalCraft/blob/master/src/main/java/com/shinoow/abyssalcraft/lib/util/ClientVars.java):

![image](https://user-images.githubusercontent.com/64550833/80652966-0b975680-8a47-11ea-99ff-751b0de78440.png)

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- AbyssalCraft: 1.9.18

#### Latest log file for when the issue was present:

**Comment by Shinoow** [comment]
Whoops, that doesn't look right. Nice catch!
