### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by loismosteiro** [Shinoow/AbyssalCraft#429]
Mobs like shadow criatures don't spawn in the Darklands in the dimensions and in the overworld only Shoggoth spawn.
I've been reading here a couple of similar issues and somebody said it will help if a increase the RAM or something for the chunk, i think, and i don't know how to change it in Aternos (the server louncher i'm using).

**Comment by Shinoow** [comment]
Use the bug report template it you wish to report a bug. In this case (based on the complete absence of information) my guess would be that you have CustomMobSpawner installed, which breaks the mob spawning of any modded biome unless configured properly (and in 99% of cases it isn't properly configured).
