### ISSUE TITLE
Unable to damage J'zahar with Tough As Nails installed

### ISSUE THREAD

**Issue by Chtho** [Shinoow/AbyssalCraft#430]
#### Description:

I was unable to damage jzahar with any melee in survival with TAN installed.

#### Affected versions :
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.19.1.jar
- ToughAsNails ToughAsNails-1.12.2-3.1.0.141-universal

**Comment by Shinoow** [comment]
I'd say that's on their end, but it is a conflict between logic in their thirst system and J'zahar's invincibility frames, in which the TAN thirst system kicks in the i-frames before the actual attack happens, which then cancels out the attack.
Generally speaking, I don't think there would be a way that their handling could be altered to work with this, so I do need to make some alterations on my end.
