### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Darkfiend009** [Shinoow/AbyssalCraft#432]
Player was just walking in a newly generated world from world spawn.

- Crash report: https://pastebin.com/1FAsEXJY

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- AbyssalCraft: 1.12.2-1.10.0

[2020-06-14-3.log](https://github.com/Shinoow/AbyssalCraft/files/4777187/2020-06-14-3.log)

**Comment by Shinoow** [comment]
This didn't happen while testing the feature in question that the crash comes from, but that could be connected to not running a full modpack. I'll have an update out amending this crash.
