### ISSUE TITLE
Suggestion: Omothol config

### ISSUE THREAD

**Issue by Shattered2909** [Shinoow/AbyssalCraft#434]
Hey, I am the dev of a modpack called Darkest Journey 2,
one of my players made me aware of an issue with Abyssalcraft and specifically Omothol in the pack, players get different skyblocks (with large distances between them) and explore differen dimensions, now there is an issue with Omothol (and maybe the Abyssal Wasteland Strongholds as well?) because there is only 1 J'Zahar Temple so depending on where players spawn, it could take hours to find him, maybe you can add some config option to generate more? Or maybe provide some other alternative?
I am not sure on how to fix this myself, could add Spawn Eggs but that is boring...

**Comment by Mike-U5** [comment]
A solution could perhaps be to Minetweak a Summoning Ritual into the Omothol Necronomicon that allows your players to summon J'zahar.

**Comment by Shattered2909** [comment]
That is true, I have considered that and might end up doing that.

**Comment by Shinoow** [comment]
Abyssal Wasteland Strongholds generate the same way vanilla does (eg. all over the place, spread out across the world), so there shouldn't be any problems with those.
Everything regarding the temple is shaped around there being only one, and I have no intentions of randomly generating more of it throughout the dimension, so a summoning ritual would be the way to go unless you can come up with a more creative solution.

**Comment by Shattered2909** [comment]
Fair enough
