### ISSUE TITLE
Staff of Gatekeeper does not switch mode

### ISSUE THREAD

**Issue by Fungidelight** [Shinoow/AbyssalCraft#435]
#### Description:

Staff of Gatekeeper does not initially switch mode.
Steps to repeat:
Craft Staff of Gatekeeper in Omothol (used the altar in J'Zahar's temple)
The crafted staff is initially in key mode
Press M
Nothing happens

Workaround: The staff does change mode after it has created a portal for the first time.

Staff obtained in creative mode (i.e. without crafting) switches mode as expected.

This was tested with only Forge and Abyssalcraft installed.

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- AbyssalCraft: AbyssalCraft-1.12.2-1.10.1.jar

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
Ah, the internal part that keeps track of the current mode hasn't been initialized in the item, and I haven't included logic to deal with that (since all testing was done with a staff spawned in creative, where this has already been resolved).
