### ISSUE TITLE
Materializer doesn't have all recipes show up.

### ISSUE THREAD

**Issue by DonkeyPAWNCH** [Shinoow/AbyssalCraft#437]
#### Description: When using the materializer, even if you have a full stack of carbon, hydrogen, and oxygen, you are still unable to create saplings. The rest of the outputs are there, such as longs and planks.

Another small side note, Nomicons are not required when using materializer.

@Shinoow 

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- AbyssalCraft: 1.12.2-1.9.19

**Comment by Shinoow** [comment]
I'm unable to reproduce this lack of recipes. Do you have other mods installed that add trees and such?
I'm also aware of the nomicon not being required, that mechanic was scrapped in the earlier stages of development, and later replaced with a Clippy easter egg whenever something was placed in that slot.

**Comment by Shinoow** [comment]
This appears to be related to the list of recipes to display exceeding the maximum amount of recipes that can be displayed.
