### ISSUE TITLE
Leave the Livestock Alone

### ISSUE THREAD

**Issue by OriginalSuperGumby** [Shinoow/AbyssalCraft#438]
The first time I encountered a demon sheep, I thought it was cool and hilarious; however, this makes your mod incompatible with a basic aspect of Minecraft - animal husbandry. What's initially an interesting feature becomes tiresome as the charging area has to be put far away from a player's base to avoid this effect. 

Keep the random spawning of creatures but don't transform the livestock please.

**Comment by Shinoow** [comment]
I think that's the first time I ever heard the term "animal husbandry", but nevertheless, build a Place of Power. Doing so nullifies the aspect of statues triggering Disruptions over time,  which won't result in livestock being transformed.
