### ISSUE TITLE
Logged in - Character was a demon cow?...

### ISSUE THREAD

**Issue by StudioVulcan** [Shinoow/AbyssalCraft#440]
I logged in to my 2nd day of a fresh SMP and my character spawned in AS a demon cow. I'm on fire, I die fast, I'm setting everything on fire and the internet can't tell me how to fix it... I've never seen anything like this before, i didn't log out this way, i don't understand why i'm suddenly a demon cow character....

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2
- AbyssalCraft: 1.12.2

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by StudioVulcan** [comment]
Holy crap I figured it out, some weird hotkey "["

**Comment by Shinoow** [comment]
This isn't a feature of AbyssalCraft. Whatever morphing mod you might have installed would be the cause as to why you spawned in as a mob, and not a player.
