### ISSUE TITLE
crash with stackup

### ISSUE THREAD

**Issue by TheNimbleNinja** [Shinoow/AbyssalCraft#447]
#### Intro:

added stackup mod and the game crashed on startup

#### Description:

If this bug occurs in a modpack, please report this to the modpack author. Otherwise delete this line and add your description here.

#### Crash report:
https://pastebin.pl/view/f3a126c3
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12
- Forge:14.23.5.2854
- AbyssalCraft:1.12.2-1.10.2.jar

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by BaccarWozat** [comment]
Good news! I got AbyssalCraft 1.12.2-1.10.2 to work with StackUp 0.2.3! So this downgrade could be used as a temporary workaround.

The only problem with it is the StackUp config will change and you might have to change the font size. (I had to set fontScaleLevel=-1 for max stack size of 999.)
