### ISSUE TITLE
Fail compile Master branch with Gradle 

### ISSUE THREAD

**Issue by Stvchm9703** [Shinoow/AbyssalCraft#451]
#### Intro:
Fail compile with Gradle 

#### Description:

Gradle report that the plugin `net.minecraftforge.gradle.forge` dependency is missing, while the ForgeGradle (.jar file) had no related lib path, neither all version (v1,v2,v3)

And, the version of `2.3-SNAPSHOT` may not be found in minecraft-forge 

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:
- Forge: 2.3-SNAPSHOT 
- AbyssalCraft: ? (clone from master branch)

#### Latest log file for when the issue was present:
```cmd
F:\Gitrepo\minecraft\AbyssalCraft>gradle build

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\Gitrepo\minecraft\AbyssalCraft\build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'AbyssalCraft'.
> 'org.gradle.api.tasks.TaskOutputs org.gradle.api.internal.TaskOutputsInternal.dir(java.lang.Object)'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
```

**Comment by Shinoow** [comment]
I've never experienced this. Have you tried using the gradle wrapper instead of using the installed gradle (1.12.2 has had some issues with more modern versions of gradle, out of which most were fixed in FG 3)? Also assuming you've run the setup tasks prior to building.
Besides, why are you trying to compile the master branch?
