### ISSUE TITLE
SidedInvWrapper cannot be cast to IItemTransferCapability

### ISSUE THREAD

**Issue by TCreopargh** [Shinoow/AbyssalCraft#452]
#### Description:

This bug happens when both TofuCraft mod and AbyssalCraft are installed. Placing the Tofu Aggregator in that mod will directly lead to a server side crash, and it destroys the world unless there is a backup.
I already reported this to TofuCraft's author and he asks me to post the issue here.

#### Crash report:

https://paste.ubuntu.com/p/YbkNzwk3NS/

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- AbyssalCraft: 1.10.2

#### Latest log file for when the issue was present:

See the crash report

**Comment by Shinoow** [comment]
This is on TofuCraft's end. They're not handling capabilities correctly.
https://github.com/0999312/TofuCraftReload/blob/master/src/main/java/cn/mcmod/tofucraft/tileentity/tofuenergy/worker/TileEntitySoymilkAggregator.java#L117-L151
Both of these methods should fallback to their super implementations if they don't encounter the capabilities they're looking for.

**Comment by Shinoow** [comment]
Closed this a bit prematurely, as I should probably make some changes on my side to counter other mods potentially doing the same thing.
