### ISSUE TITLE
Place of power deletes Necromonicon

### ISSUE THREAD

**Issue by Antoninecek** [Shinoow/AbyssalCraft#455]
#### Description:

I've built place of power (ArchwayStructure), activated it, placed Necromonicon at the top, started gathering energy. After some time (about 3 minutes) Necronomicon disappears. No disruption.

![image](https://user-images.githubusercontent.com/15322661/97776262-f79fef00-1b66-11eb-80ac-73a8b76035b9.png)

#### Crash report:
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2854
- AbyssalCraft: 1.12.2-.1.9.19.1

#### Latest log file for when the issue was present:

I have only client log (trying to get server log). It happend in 10.06 to 10.08 (there is nothing in client log - we tried again)
https://pastebin.com/5pxjbSBt

**Comment by Shinoow** [comment]
Did you place the book on a pedestal, or did you just drop it on the ground?

**Comment by Antoninecek** [comment]
I dropped it to the top block.

**Comment by Shinoow** [comment]
Dropped items despawn after 5 minutes.
