### ISSUE TITLE
Language Bug

### ISSUE THREAD

**Issue by NotThisGamer** [Shinoow/AbyssalCraft#457]
I've found a bug.
When i tried to use the mod all of the items were in some kind of language while i was playing in english i dont know what it is or what i need to do ;/

**Comment by Shinoow** [comment]
Not a bug. The names of items and blocks are locked from the beginning, and become readable over time as you progress in the mod.
You can use the command `/acunlockallknowledge` to bypass this mechanic altogether, or enable "Display Item Names" in the config to display the names.
