### ISSUE TITLE
No longer compatible with JAOPCA

### ISSUE THREAD

**Issue by Sunconure11** [Shinoow/AbyssalCraft#459]
https://github.com/TheLMiffy1111/JAOPCA/issues/185

**Comment by Shinoow** [comment]
JAOPCA is referencing deprecated API methods that were removed in 2.0.0-ALPHA-1 (hence the version number starting with a 2 instead of 1). Things relying on the 1.x API will likely need to update in order to be compatible with the 2.x API.

**Comment by Shinoow** [comment]
However, the JAOPCA devs shouldn't rewrite compatibility to support AbyssalCraft 2.0 until it's out of Alpha, as the API changes aren't finalized at the moment.
