### ISSUE TITLE
Anti-matter Suggestion

### ISSUE THREAD

**Issue by jj-easts** [Shinoow/AbyssalCraft#461]
1.10.2 the antimatter can touch any block. This is not how physics works. Antimatter if exposed to normal matter they would annihilate each other and release energy. Antimatter should basically be liquid TNT.

**Comment by Shinoow** [comment]
You do realize the performance impact this would have, right? Load a chunk with a Coralium Infested Swamp biome, and the whole biome evaporates and as long as the liquid can spread anywhere, more explosions.
