### ISSUE TITLE
Upgrade kit only works once

### ISSUE THREAD

**Issue by yspreen** [Shinoow/AbyssalCraft#462]
#### Description:

I'm playing on ABOE 3.8.6b. 
As you can see, the upgrade doesn't work. It seems to have worked exactly once. I tried switching around the order, restarting my game, building a new anvil, nothing works.

![image](https://user-images.githubusercontent.com/12631527/106323513-d63ec400-6277-11eb-8684-954322d75806.png)

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- AbyssalCraft: 1.12.2-1.10.3

**Comment by yspreen** [comment]
Okay restarting both client and server completely did work. I could use one upgrade again. I'll make a video this time.

**Comment by yspreen** [comment]
Seems to have affected only the server this time, not the client

https://youtu.be/JkhkZG3W3C4

**Comment by Shinoow** [comment]
Unsure whether or not I'll actually look into fixing this, as the Upgrade Kits are removed in version 2.0 an onwards. Does the same occur if you do this in an instance with just AbyssalCraft, as opposed to an entire modpack?

**Comment by Shinoow** [comment]
Closing this for now. If someone finds the source of the problem in the future, please submit a pull request or drop a note here!
