### ISSUE TITLE
Server crash when modloading finishes

### ISSUE THREAD

**Issue by rhgngle** [Shinoow/AbyssalCraft#463]
#### Intro:

Title. It crashes after all mods has finished loading and before the world starts loading

#### Description:

I was trying to use my modpack in a server when this happened. I then found the crash report to contain Abyssalcraft's name so I tried it with only Abyssalcraft in the mods folder, same thing happed.

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2855 + 14.23.5.2854
- AbyssalCraft: 2.0.0-ALPHA-1

#### Latest log file for when the issue was present:

https://gist.github.com/rhgngle/8b913d29f429741c120652fd000487aa

**Comment by rhgngle** [comment]
Does not crash in singleplayer

**Comment by Shinoow** [comment]
Whoops, made the wrong assumption that code wouldn't run on server-side.

**Comment by ThatOneJose95** [comment]
does downgrading resolve the issue until it's fixed?

**Comment by Shinoow** [comment]
Yes... sort of. You wouldn't experience this crash in 1.10.3, but 1.10.3 and 2.0.0-ALPHA-1 are not compatible, so if you play with 1.10.3 and later update to 2.0.0-ALPHA-2 (whenever I drop that), content in the world will disappear (as some things have been removed).
