### ISSUE TITLE
Portal placement

### ISSUE THREAD

**Issue by NikeSchuh** [Shinoow/AbyssalCraft#465]
I cannot place the portal with the Gateaway Key. Instead of placing the portal it just cycles through the possibilities making it
impossible to place a portal. (Mk1)

- Minecraft: 1.12.2
- Forge: 2854
- AbyssalCraft: AbyssalCraft-1.12.2-2.0.0-ALPHA-2

**Comment by Shinoow** [comment]
Portals are no longer placed by the key as of 2.0.0, instead you create portals through a ritual. Right-clicking the key merely cycles through the available dimensions you can create portals leading to, but the ritual is where the actual portal is created.

**Comment by NikeSchuh** [comment]
Is the ritual already implemented?

**Comment by Shinoow** [comment]
Yeah, it was implemented in the same release as the keys had their functionality changed.

**Comment by NikeSchuh** [comment]
Can I look up the ritual somewhere or is it only implemented in the code?

**Comment by Shinoow** [comment]
Like all rituals, it's viewable in the Necronomicon in-game. I don't know if anyone has posted a screenshot of the page with the ritual.
