### ISSUE TITLE
Places of Power and Energy Collectors

### ISSUE THREAD

**Issue by MaxAstro** [Shinoow/AbyssalCraft#470]
Disclaimer: I am playing SevTech, latest version (3.2.1), which includes Abyssalcraft 1.9.19.1

How does one connect an energy collector to a Place of Power? What is the correct placement of the collector relative to the structure? I have tried every arrangement I can think of... I know the Place of Power is built correctly, because the key block changed, and I know the statues are working because I can stand near them with a necronomicon and get PE.

But it seems like no matter where I put the energy collector, or what Place of Power layout I use, the statues never power the energy collector. I've tried putting the collector on the same level as the statues, one level below, the same level as the key block, two blocks away, three blocks away... nothing seems to work.

**Comment by Shinoow** [comment]
Placement follows the same rules as with statues not in a Place of Power. Since most of the Places of Power increase range, you will likely be able to space them out a bit further than normal, but the minimum two block gap between the statue and collector still applies. Can you post a screenshot of your current setup?

**Comment by MaxAstro** [comment]
I figured out the problem - I was testing in a world with doDaylightCycle set to false (we were doing Astral Sorcery stuff and tired of waiting for night). Didn't realize that would mess with the collectors! Once I turned the daylight cycle back on it started working.

Sorry for the confusion.

**Comment by Shinoow** [comment]
Ah, yeah, that checks out. The logic in the statues that "discovers" nearby energy collectors (of all types) it can transfer energy to utilizes current world time to pace out the time interval at which said logic runs (done every 10 seconds). This whole set of logic falls flat if the daylight cycle stops.
