### ISSUE TITLE
Ritual Setup Keeps Breaking

### ISSUE THREAD

**Issue by MaxAstro** [Shinoow/AbyssalCraft#471]
Disclaimer: I am playing SevTech, latest version (3.2.1), which includes Abyssalcraft 1.9.19.1

I am playing on a dedicated server, and every time I leave the server and return, my ritual setups no longer work - shift+right click with the necronomicon won't start the ritual.

If I break all the blocks, replace them, and recreate the setup, it works fine. This happens with ritual setups in other dimensions as well (tested the Abyssal Wasteland, haven't tested the Dreadlands yet).

It's possible this is a chunkloading issue, as my ritual setup is not near any of my chunkloaders.

**Comment by Shinoow** [comment]
Are all of the blocks of the ritual setup in the same chunk? I've had reports of that same scenario where the solution was to place all of the blocks within the same chunk.

**Comment by MaxAstro** [comment]
Literally _one_ block is outside the chunk boundary, wow. I'll try moving the setup and see if that fixes it. Might be worth adding a warning to the Necronomicon that it's best to put the whole setup in a single chunk?

**Comment by Shinoow** [comment]
Yeah, either a warning, add some restriction in the mechanic of forming the setup that informs the player that the blocks need to be in the same chunk, or try to solve the issue of it not working when all of the blocks aren't in the same chunk.
