### ISSUE TITLE
Multimodel - No Base Models were provided

### ISSUE THREAD

**Issue by huskyflapper** [Shinoow/AbyssalCraft#472]
#### Description:

Hello, I'm creating a custom modpack just for myself and I was wondering what this error means.

MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)

I was wondering what this means. If someone can tell me that would be great. Also this also happens to me in teh latest nonalpha version too - 1.10.3 Version. If there is a solution for this that would be great.

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2-forge-14.23.5.2855
- AbyssalCraft: 1.12.2-2.0.0-ALPHA-3

#### Latest log file for when the issue was present:

[latest.log](https://github.com/Shinoow/AbyssalCraft/files/6410108/latest.log)

**Comment by Shinoow** [comment]
I can't recall which ones it is, but five models are loaded in an unconventional enough way to generate that error message in the log. The blocks themselves work as they should visually, so you can safely ignore that message.

**Comment by MuffinFantasy** [comment]
i have this problem but the minecraft just crashes and those errors are last thing in the log
