### ISSUE TITLE
Maven always returns HTTP 403

### ISSUE THREAD

**Issue by Wunst** [Shinoow/AbyssalCraft#474]
Hey Shinoow,

It isn't directly a mod problem, but somehow your Maven has stopped to work. Your dl.bintray... maven just returns "403 forbidden" to all requests and your fallback maven hasn't been updated since 2017.

~~Wunst

**Comment by Shinoow** [comment]
Right, bintray shut down their maven service at the beginning of last month. I haven't gotten around to migrating yet (planning on hosting it myself, but I haven't really had the time to purchase the hardware and set the thing up).
For now you'll have to go the CurseForge route, as there is some maven component there you can use (or several gradle plugins that simplifies it).

**Comment by Wunst** [comment]
Thank you very much! I'm gonna try the CurseForge thing.
