### ISSUE TITLE
Configuration entry "ODB Explosion Size" has no effect

### ISSUE THREAD

**Issue by RisingInIris2017** [Shinoow/AbyssalCraft#477]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

If `"Disable ODB Explosions"=false`, Oblivion Deathbomb's explosion will create a size-fixed big hole on the ground regardless of the "ODB Explosion Size" configuration even though it is set to `"ODB Explosion Size"=0`.

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- AbyssalCraft: 1.12.2-1.10.3

**Comment by Shinoow** [comment]
Apparently I didn't specify the bounds for that config option, but you can't set it to 0 (lowest is 80). If you don't want explosions, disable them.

**Comment by RisingInIris2017** [comment]
> Apparently I didn't specify the bounds for that config option, but you can't set it to 0 (lowest is 80). If you don't want explosions, disable them.

Oh, I see. Maybe it's better to write some comments for the `ODB Explosion Size` entry, because setting it to 0 was able to disable the explosion, but summon the Boss, in a certain old version of AbyssalCraft.
