### ISSUE TITLE
Necronomicon uses Username over UUID

### ISSUE THREAD

**Issue by ImTheSquid** [Shinoow/AbyssalCraft#478]
#### Description:

Changing your Minecraft username locks you out of your necronomicon because it uses a player's username over their UUID for identification.

I was able to find the offending code in `ItemNecronomicon.java`, specifically in `onItemRightClick` and `isOwner`. A possible fix would be to use `EntityPlayer.getUUID` to set the `owner` tag.

#### Crash report:

N/A

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- AbyssalCraft: 1.12.2-1.10.2

#### Latest log file for when the issue was present:

N/A

**Comment by Shinoow** [comment]
Right, I didn't bother to change that when utilizing UUIDs came about. Probably a good time to actually make that change.
