### ISSUE TITLE
Please start a new thread (async) to get your supporters' list

### ISSUE THREAD

**Issue by roj234** [Shinoow/AbyssalCraft#481]
#### Description:

Do not try to get a URL on main thread without setting a timeout!!!
Do not try to get a URL on main thread without setting a timeout!!!
Do not try to get a URL on main thread without setting a timeout!!!

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2855
- AbyssalCraft: 1.10.3

#### Latest log file for when the issue was present:

Some images
https://ibb.co/TrwXTrz
https://ibb.co/6J9KV17

**Comment by Shinoow** [comment]
Duplicate of #469
