### ISSUE TITLE
Abyssalcraft and erebus biome conflict 

### ISSUE THREAD

**Issue by EXOTOWasClaimed** [Shinoow/AbyssalCraft#485]
So basically i am wanting to use abyssalcraft and erebus in a single modpack but minecraft is conflicted and crashes.

I know theres an easy fix for this somewhere but I don't know where to look, I spent 20 minutes using 7-Zip to look around the java file but could not find anything that hinted a possible biome id change

Crash report: "The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Erebus can not use biome ID 100 because it's being used by com.shinoow.abyssalcraft.common.world.biome.BiomeGenDarklands@713651bb. Please choose a different one.
Exit Code: -1"

(Yes, i have used the crash report and went all the way to biomes and couldn't find "com.shinoow.abyssalcraft.common.world.biome.BiomeGenDarklands@713651bb" if you are able to help me on this please do.)

- Minecraft: 1.7.10 (Java)
- Forge: 10.13.1614
- AbyssalCraft: 1.9.1.3

**Comment by Shinoow** [comment]
The config file is where you change biome IDs, not by modifying the source code. There should be a config folder in your minecraft directory, check the .cfg files there for the config files of the respective mods.
