### ISSUE TITLE
Server crash: Exception while ticking a block

### ISSUE THREAD

**Issue by RisingInIris2017** [Shinoow/AbyssalCraft#487]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:
When server load a chunk contains `abyssalcraft:cwater` block, server will crash.

#### Crash report:
https://gist.github.com/RisingInIris2017/cd42be80d26b43532a025e53702ad054

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- AbyssalCraft: 1.10.3

#### Latest log file for when the issue was present:
https://gist.github.com/RisingInIris2017/cd42be80d26b43532a025e53702ad054#file-latest-log

If you think this is an issue related to my server software, please tell me too.
I have posted the same issue to its repo: https://github.com/MohistMC/Mohist/issues/1725

**Comment by Shinoow** [comment]
Yeah, I believe this is something on the server software's end.

**Comment by Shinoow** [comment]
Don't know if this was fixed (based on the issue on Mohist's repo being closed), but this issue can be re-opened if it's still a problem.
