### ISSUE TITLE
Washcloth Dupe Glitch

### ISSUE THREAD

**Issue by RadioactivePrototype** [Shinoow/AbyssalCraft#490]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

If I put 2 wash cloths in a crafting grid and take the "crafted" one out, then the 2 in the crafting grid will stay and the crafted one will also be there. However, the 2 crafting grid ones have 1 less durability, which probably means it repairs, because it damages the item instead of removing it. I do have some other mods installed, but not an official modpack.

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- AbyssalCraft: 1.10.4

#### Latest log file for when the issue was present:

https://docs.google.com/document/d/1_0iXqjDs00M9CYxu-JLvYHj9O0-rzjT_cGceJhL2eW8/edit?usp=sharing

**Comment by Shinoow** [comment]
Digital note for myself:
add `setNoRepair()` to the constructor of
https://github.com/Shinoow/AbyssalCraft/blob/1.12.2-1.x.x/src/main/java/com/shinoow/abyssalcraft/common/items/ItemWashCloth.java
