### ISSUE TITLE
Game Crippling Mob Spawn Issue

### ISSUE THREAD

**Issue by AisuTistoto223** [Shinoow/AbyssalCraft#492]
#### Intro:

Mobs do not spawn in the dimensions and biomes they are intended to.

#### Description:

Abyssal wasteland has zero enemies. Darklands have no enemies, etc.

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- AbyssalCraft: 1.10.2 and 1.10.4

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

My Mods, to see if it's a compatibility issue:
![image](https://user-images.githubusercontent.com/47762838/148115415-866e7750-525a-47cc-8f34-298cf72e3bec.png)

**Comment by Shinoow** [comment]
This is caused by `CustomMobSpawner`, which in it's default configuration breaks mob spawning in any custom biome (and dimension) added by other mods. Removing that should fix the issue.

**Comment by AisuTistoto223** [comment]
> 

There any way to modify the CustomMobSpawner configs to fix it instead of removing it entirely?

**Comment by Shinoow** [comment]
By all means, you can try. But in the 10 years I've been developing mods, I've never come across anyone who managed to figure it out and get things to work. Last attempt (known to me) would be #259

**Comment by AisuTistoto223** [comment]
I've decided to just use a different mod for now. It's solved a vast number of issues I didn't even realize existed. I'll look into fixing the wretched mod's incompatibility with basically everything another time. Consider this solved.
