### ISSUE TITLE
Crashing for some reason

### ISSUE THREAD

**Issue by SojwetUnion** [Shinoow/AbyssalCraft#502]
Hello, when I launch the mod, for some reason I end up crashing.

It only occurs when i install abyssalcraft and i dont know why

java.lang.NoSuchMethodError: com.shinoow.abyssalcraft.client.model.entity.ModelLesserShoggoth: method <init>()V not found
	at net.minecraft.AgeOfMinecraft.abyssalcraft.render.entity.RenderLesserShoggoth.<init>(RenderLesserShoggoth.java:39)
	at net.minecraft.AgeOfMinecraft.ClientProxy2.lambda$renderEntitiesAbyssalcraft$27(ClientProxy2.java:63)
	at net.minecraft.AgeOfMinecraft.ClientProxy2$$Lambda$351/1764376460.createRenderFor(Unknown Source)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:230)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.AgeOfMinecraft.abyssalcraft.render.entity.RenderLesserShoggoth.<init>(RenderLesserShoggoth.java:39)
	at net.minecraft.AgeOfMinecraft.ClientProxy2.lambda$renderEntitiesAbyssalcraft$27(ClientProxy2.java:63)
	at net.minecraft.AgeOfMinecraft.ClientProxy2$$Lambda$351/1764376460.createRenderFor(Unknown Source)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:230)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 274592992 bytes (261 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                     | Source                                             | Signature                                |
	|:----- |:------------------- |:--------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                      | minecraft.jar                                      | None                                     |
	| LCH   | mcp                 | 9.42                        | minecraft.jar                                      | None                                     |
	| LCH   | FML                 | 8.0.99.99                   | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2860                | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       | 4.0.2.284                   | minecraft.jar                                      | None                                     |
	| LCH   | mixinbooter         | 5.0                         | minecraft.jar                                      | None                                     |
	| LCH   | jei                 | 4.16.1.302                  | jei_1.12.2-4.16.1.302.jar                          | None                                     |
	| LCH   | abyssalcraft        | 2.0.0-ALPHA-4               | AbyssalCraft-1.12.2-2.0.0-ALPHA-4.jar              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | aether_legacy       | 1.5.3.2                     | aether-1.12.2-v1.5.3.2.jar                         | None                                     |
	| LCH   | codechickenlib      | 3.2.3.358                   | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux        | 2.1.1                       | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCH   | brandonscore        | 2.4.20                      | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LCH   | ctm                 | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LCH   | draconicevolution   | 2.3.28                      | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| LCH   | ageofabyssalcraft   | 0.7                         | Engender+Mod-1.12.2-0.7-pre1.jar                   | None                                     |
	| LCH   | ageofchaos          | 0.7                         | Engender+Mod-1.12.2-0.7-pre1.jar                   | None                                     |
	| LCH   | ageofminecraft      | 0.7                         | Engender+Mod-1.12.2-0.7-pre1.jar                   | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.284                   | Galacticraft-1.12.2-4.0.2.284.jar                  | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.284                   | Galacticraft-1.12.2-4.0.2.284.jar                  | None                                     |
	| LCH   | mjrlegendslib       | 1.12.2-1.2.1                | MJRLegendsLib-1.12.2-1.2.1.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | extraplanets        | 1.12.2-0.7.4                | ExtraPlanets-1.12.2-0.7.4.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | flansmod            | 5.10.0                      | Flan's+Mod-1.12.2-5.10.0.jar                       | None                                     |
	| LCH   | forgerocks          | 7.3.1-1.12.2                | ForgeRocks-7.3.1-1.12.2-full.jar                   | None                                     |
	| LCH   | hbm                 | hbm-1.6.8Av5-1.12.2         | hbm-1.6.8a-Gv5.jar                                 | None                                     |
	| LCH   | waila               | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCH   | icbmclassic         | 1.12.2-4.1.0.20211106011047 | ICBM-classic-1.12.2-4.1.0b20211106011048.jar       | None                                     |
	| LCH   | jeid                | 1.0.4-SNAPSHOT              | JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar              | None                                     |
	| LCH   | stevekung's_lib     | 1.2.0                       | SteveKunG's-Lib-1.12.2-1.2.0.jar                   | None                                     |
	| LCH   | moreplanets         | 2.2.4                       | More-Planets-1.12.2-2.2.4-GC284.jar                | None                                     |
	| LCH   | planetprogression   | 1.12.2-0.4.6                | PlanetProgression-1.12.2-0.4.6.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | projectintelligence | 1.0.9                       | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
	| LCH   | simplepartspack     | 5.7.2                       | Simple+Parts-Content+Pack-1.12.2-5.7.2.jar         | None                                     |
	| LCH   | ww2pack             | 5.7.2                       | WW2-Content+Pack-1.12.2-5.7.2.jar                  | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
  org.dimdev.jeid.JEIDTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  
MixinBooter (!mixinbooter-5.0.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9621' Renderer: 'Intel(R) Iris(R) Plus Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: Intel(R) Iris(R) Plus Graphics GL version 4.6.0 - Build 27.20.100.9621, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Is is possible other mods I have installed have effected Abyssalcraft? Please let me know.

**Comment by Shinoow** [comment]
Engender isn't compatible with AbyssalCraft 2.0, but if you downgrade AbyssalCraft to version 1.10.4 (latest in the 1.x.x branch of the mod) you'll be able to play.
