### ISSUE TITLE
Several biome absence

### ISSUE THREAD

**Issue by Andrey007380** [Shinoow/AbyssalCraft#509]
#### Description:

An issue where The Dreadlands fail(To clarify, when I say 'fail to generate,' I mean that there are no such biomes as Dreadland Mountains, Dreadland Forest, and Purified Dreadland in The Dreadlands. Instead, everywhere I go in The Dreadlands, I only encounter the standard Dreadlands biome.) to generate these biomes: Dreadland Mountains, Dreadland Forest, and Purified Dreadland?

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- AbyssalCraft: 1.10.4

-- System Details --
Details:
  Minecraft Version: 1.12.2
  Operating System: Windows 11 (amd64) version 10.0
  Java Version: 1.8.0_361, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 706864256 bytes (674 MB) / 1073741824 bytes (1024 MB) up to 4261412864 bytes (4064 MB)
  JVM Flags: 6 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 43 mods loaded, 43 mods active
  States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

  | State | ID                                           | Version                | Source                                       | Signature                                |
  |:----- |:-------------------------------------------- |:---------------------- |:-------------------------------------------- |:---------------------------------------- |
  | LCH   | minecraft                                    | 1.12.2                 | minecraft.jar                                | None                                     |
  | LCH   | mcp                                          | 9.42                   | minecraft.jar                                | None                                     |
  | LCH   | FML                                          | 8.0.99.99              | forge-1.12.2-14.23.5.2860.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
  | LCH   | forge                                        | 14.23.5.2860           | forge-1.12.2-14.23.5.2860.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
  | LCH   | com.elytradev.movingworld.common.asm.coremod |                        | minecraft.jar                                | None                                     |
  | LCH   | jei                                          | 4.16.1.301             | jei_1.12.2-4.16.1.301.jar                    | None                                     |
  | LCE   | abyssalcraft                                 | 1.10.4                 | AbyssalCraft-1.12.2-1.10.4.jar               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
  | LC    | aether_legacy                                | 1.5.3.2                | aether-1.12.2-v1.5.3.2.jar                   | None                                     |
  | LC    | appleskin                                    | 1.0.14                 | AppleSkin-mc1.12-1.0.14.jar                  | None                                     |
  | LC    | baubles                                      | 1.5.2                  | Baubles-1.12-1.5.2.jar                       | None                                     |
  | LC    | astralsorcery                                | 1.10.27                | astralsorcery-1.12.2-1.10.27.jar             | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
  | LC    | bettercaves                                  | 1.12.2                 | bettercaves-1.12.2-2.0.4.jar                 | None                                     |
  | LC    | bettermineshafts                             | 1.12.2-2.2.1           | BetterMineshaftsForge-1.12.2-2.2.1.jar       | None                                     |
  | LC    | bookshelf                                    | 2.3.590                | Bookshelf-1.12.2-2.3.590.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
  | LC    | clumps                                       | 3.1.2                  | Clumps-3.1.2.jar                             | None                                     |
  | LC    | dailies                                      | 1.12.2-6               | dailies-1.12.2-6.jar                         | None                                     |
| LC    | movingworld                                  | 1.12-6.353             | movingworld-1.12-6.353-full.jar              | None                                     |
  | LC    | davincisvessels                              | @DVESSELSVER@          | davincisvessels-1.12-6.340-full.jar          | None                                     |
  | LC    | mocreatures                                  | 12.0.5                 | DrZharks MoCreatures Mod-12.0.5.jar          | None                                     |
  | LC    | dungeonsmod                                  | @VERSION@              | DungeonsMod-1.12.2-1.0.8.jar                 | None                                     |
  | LC    | ebwizardry                                   | 4.3.9                  | ElectroblobsWizardry-4.3.9.jar               | None                                     |
  | LC    | mod_lavacow                                  | 1.3.3                  | Fish's Undead Rising-1.3.3.jar               | None                                     |
  | LC    | ftbbackups                                   | 1.1.0.1                | FTBBackups-1.1.0.1.jar                       | None                                     |
  | LC    | gravestone                                   | 1.10.3                 | gravestone-1.10.3.jar                        | None                                     |
  | LC    | waila                                        | 1.8.26                 | Hwyla-1.8.26-B41_1.12.2.jar                  | None                                     |
  | LC    | inventorysorter                              | 1.13.3+57              | inventorysorter-1.12.2-1.13.3+57.jar         | None                                     |
  | LC    | ironbackpacks                                | 1.12.2-3.0.8-12        | IronBackpacks-1.12.2-3.0.8-12.jar            | None                                     |
  | LC    | journeymap                                   | 1.12.2-5.7.1           | journeymap-1.12.2-5.7.1.jar                  | None                                     |
  | LC    | mutantbeasts                                 | 1.12.2-1.0.2           | MutantBeasts-1.12.2-1.0.2.jar                | None                                     |
  | LC    | mysticalworld                                | 1.12.2-1.11.0          | mysticalworld-1.12.2-1.11.0.jar              | None                                     |
  | LC    | naturescompass                               | 1.8.5                  | NaturesCompass-1.12.2-1.8.5.jar              | None                                     |
  | LC    | brewcraft                                    | 1.12.2-1.0.2           | Pam's BrewCraft 1.12.2-1.0.2.jar             | None                                     |
  | LC    | patchouli                                    | 1.0-23.6               | Patchouli-1.0-23.6.jar                       | None                                     |
  | LC    | roguelike                                    | 1.8.0                  | RoguelikeDungeons-1.12.2-1.8.0.jar           | None                                     |
  | LC    | thaumcraft                                   | 6.1.BETA26             | Thaumcraft-1.12.2-6.1.BETA26.jar             | None                                     |
  | LC    | vampirism                                    | 1.6.2                  | Vampirism-1.12.2-1.6.2.jar                   | None                                     |
  | LC    | teamlapen-lib                                | 1.6.2                  | Vampirism-1.12.2-1.6.2.jar                   | None                                     |
  | LC    | vampirism_integrations                       | vampirism_integrations | VampirismIntegrations-1.12.2-1.3.0.jar       | None                                     |
  | LC    | wawla                                        | 2.6.275                | Wawla-1.12.2-2.6.275.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
| LC    | waystones                                    | 4.1.0                  | Waystones_1.12.2-4.1.0.jar                   | None                                     |
  | LC    | wizardryutils                                | 1.12.2-1.1.4           | WizardryUtils-1.12.2-1.1.4.jar               | None                                     |
  | LC    | necromancersdelight                          | 1.12.2-1.0.5           | WizardryNecromancersDelight-1.12.2-1.0.5.jar | None                                     |
  | LC    | mysticallib                                  | 1.12.2-1.13.0          | mysticallib-1.12.2-1.13.0.jar                | None                                     |

  Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by Shinoow** [comment]
Hm.... that's a new one. After looking through the code of some of the mods, Better Mineshafts is the only one I could think of that could mess with the dimension, but that "messing" would be replacing the mineshaft generation, which shouldn't result in the whole dimension seemingly switch to only generating a single biome.

Just to ask the stupid question, you have made a new world and flied around checking to ensure that none of the other biomes generate, and didn't just have **really bad luck**?

Since I can't really find an obvious culprit, best advice would be to try removing mods, and by doing so continually narrow it down until biome generation in the dimension works.
