### ISSUE TITLE
Statues & pedestals

### ISSUE THREAD

**Issue by LatentDesire** [Shinoow/AbyssalCraft#51]
Some flexibility in the Y axis of where the statues need to be placed in relation to the thing that gathers PE would be appreciated. Specifically having the option to place it 1 or 2 blocks above the Y of the collector. Should invalidate statues placed underneath a statue, to prevent stacking I think.

**Comment by Shinoow** [comment]
I've worked this through. Now you will be able to place pedestals up to 2 blocks further down on the Y axis, and statues are invalidated when stacked (any attempt to transfer PE is stopped if there's a statue above or below the statue in question).
