### ISSUE TITLE
(1.7.10)abyssalcraft mod problem crash at launch of minecraft

### ISSUE THREAD

**Issue by LeonMaster9415** [Shinoow/AbyssalCraft#513]
#### Intro:

hi, i created a modpack with 50/60 mods i just putted 34/35 because it keeps crashing and i didnt know why so i deleted all the mods and added some to know what was the problem. the AbyssalCraft mod was the problem and i dont know how to fix this... anyone can help me please im desperate.

#### Crash report:
[latest.log](https://github.com/Shinoow/AbyssalCraft/files/13648285/latest.log)

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.7.10
- Forge:???
- AbyssalCraft:1.9.1.3

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
`java.lang.RuntimeException: Biome ID 100 is already occupied by the biome Eden (net.divinerpg.dimensions.twilight.eden.BiomeGenEden)!`
You have a biome ID conflict. Check either the AbyssalCraft or DivineRPG config file and modify the IDs there.
AbyssalCraft uses the ID range 100 - 113, so keep that in mind when configuring.

**Comment by LeonMaster9415** [comment]
thank you so much @Shinoow

**Comment by LeonMaster9415** [comment]
can you help me to modify the id of divinerpg? if yes where i have to set the id config? minecraft mod menu?

**Comment by LeonMaster9415** [comment]
??

**Comment by Shinoow** [comment]
If you open your modpack folder, there should be a folder named `config` next to the mods folder. This folder should contain a bunch of .cfg files (and possibly other stuff), and there should be one called something along the lines of "divinerpg.cfg". I have no idea what the contents of that file look like, but I would assume there should be something there mentioning biome IDs. Open it and modify any biome ID config option so that no biome from that mod occupies the ID range 100 - 113, then the game should load.

**Comment by LeonMaster9415** [comment]
ok i did thanks

**Comment by LeonMaster9415** [comment]
but still not working :\

**Comment by LeonMaster9415** [comment]
![image](https://github.com/Shinoow/AbyssalCraft/assets/153620929/612f5181-f4ea-4b3c-962b-eac783044cba)

**Comment by LeonMaster9415** [comment]
@Shinoow im having a problem while starting a world. i waited 2 hours and thats what it says:
![Uploading image.png…]()

**Comment by LeonMaster9415** [comment]
@Shinoow im having a problem while starting a world. i waited 2 hours and thats what it says:
![image](https://github.com/Shinoow/AbyssalCraft/assets/153620929/b23b705b-f353-4f2f-94be-41e909c0af92)

**Comment by Shinoow** [comment]
I can't really make out anything from that picture. If you send your logs I could look through that and see if I see anything.

**Comment by LeonMaster9415** [comment]
ill see if i find it 1s

**Comment by LeonMaster9415** [comment]
[Uploading 2023-11-26-6.log…]()
should be this

**Comment by LeonMaster9415** [comment]
[2023-11-26-6.log.gz](https://github.com/Shinoow/AbyssalCraft/files/13665419/2023-11-26-6.log.gz)

**Comment by Shinoow** [comment]
I need the latest log. One that's nearly 3 weeks old won't contain the log data from yesterday

**Comment by LeonMaster9415** [comment]
than what i have to send? the log i sended was for the crash of minecraft with abyssalcraft and said shutting down internal server

**Comment by Shinoow** [comment]
That log is from an instance running 1.19.2. I can't help you if you send the wrong log file. The file I want you to send is `latest.log`, AFTER trying to create a world in the 1.7.10 setup (assuming it fails the same way again).

**Comment by LeonMaster9415** [comment]
ok ill see again

**Comment by LeonMaster9415** [comment]
ok im trying to enter a new world in 10-20minutes ill send the log if it doesnt start

**Comment by LeonMaster9415** [comment]
[latest.log](https://github.com/Shinoow/AbyssalCraft/files/13675745/latest.log)
here

**Comment by Shinoow** [comment]
Hm... I can't really pin down anything. Erebus seems to track something, which in turn references optifine (probably just something that's overridden by OF). Failcraft is loading a billion dimensions, which might be part of the problem (could be something there that hangs up down the line). Honestly, this isn't related to AbyssalCraft anymore, unless there's a dimension id conflict, but that should've crashes during startup.
I can't help you with this. Might wanna join a modpack dev Discord server or another community and ask for help there.

**Comment by LeonMaster9415** [comment]
ok

**Comment by LeonMaster9415** [comment]
but what you mean "that's overridden by optifine"?

**Comment by LeonMaster9415** [comment]
or by the erebus mod?

**Comment by LeonMaster9415** [comment]
![image](https://github.com/Shinoow/AbyssalCraft/assets/153620929/47c0e460-3b1b-422d-91ac-9b9451e94e42)
look

**Comment by Shinoow** [comment]
Well, there you have it, you don't have enough memory allocated.
