### ISSUE TITLE
Materializer Fails to expend proper numbers of materials

### ISSUE THREAD

**Issue by Urbancase** [Shinoow/AbyssalCraft#515]
#### Description:

When using a Materializer, shift-clicking to make an item produces up to a stack of the selected item, but only consumes the crystals necessary to produce 1. The result of this is 64 Crystallized Gold ≠ 64 Gold Ingots, but 2080 Gold Ingots (Assuming only one stack is present, otherwise 4096 gold per stack of crystals). This is a serious bug that makes the Materializer unusable on servers for balance reasons.

#### Crash report:

N/A

----

#### Affected versions:
- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- AbyssalCraft: 1.10.5

#### Latest log file for when the issue was present:

https://pastebin.com/UpkcujYK

**Comment by Shinoow** [comment]
Yeah... That's not supposed to happen. Probably about time I rewrite the internals for the materializer, because something else breaks when something is fixed...
Will investigate if this was present with the last bug I applied a fix for prior to fixing that.
