### ISSUE TITLE
Exception from AbyssalCraft Integration with AbyssalCraft-1.12.2-2.0.0-ALPHA-7.1

### ISSUE THREAD

**Issue by Robolightning** [Shinoow/AbyssalCraft#517]
#### Intro:

Exception on launch game from AbyssalCraft Integration with AbyssalCraft-1.12.2-2.0.0-ALPHA-7.1
#### Description:

My own modepack

#### Crash report:

[https://mclo.gs/tdsSXmf](https://mclo.gs/tdsSXmf)

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- AbyssalCraft: 2.0.0-ALPHA-7.1

#### Latest log file for when the issue was present:

[launcher_log8.txt](https://github.com/user-attachments/files/15963334/launcher_log8.txt)
(845kb, more than 512 pastebin limit)

**Comment by Shinoow** [comment]
AbyssalCraft Integration isn't compatible with the 2.0 branch of AbyssalCraft.

**Comment by Robolightning** [comment]
> AbyssalCraft Integration isn't compatible with the 2.0 branch of AbyssalCraft.

Is support of AbyssalCraft Integration content planned at the future at 2.0 branch?

**Comment by Shinoow** [comment]
Yes! Once AbyssalCraft 2.0 is out of alpha, or beta (remains to be seen), AbyssalCraft Integration will be updated to support the 2.0 API.

**Comment by Oregano1963** [comment]
Is there a list of expected changes beyond the four year old issue
