### ISSUE TITLE
Altar Not Forming in Overworld

### ISSUE THREAD

**Issue by AlexTheGryphon** [Shinoow/AbyssalCraft#519]
#### Description:

I am trying to create a ritual circle/altar in the overworld. I have tried in different areas multiple times, but each time three cobblestone at the same points (southwest, south, southeast) pop up a barrier block over them, as if there's something wrong. I am playing multiplayer with friends.
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- AbyssalCraft: 1.12.2-1.10.6

#### Latest log file for when the issue was present:

![2024-08-08_01 49 21](https://github.com/user-attachments/assets/b8e29afb-c32e-4ad4-a7ed-af37c38d8bb6)

**Comment by Shinoow** [comment]
All of the blocks need to be within the same chunk. The barrier particle indicate which ones aren't.

**Comment by AlexTheGryphon** [comment]
I can't believe I did the same stupid thing three times, sorry for wasting your time with this, and thank you for the help!
