### ISSUE TITLE
JEI compatibility for non-crafting rituals

### ISSUE THREAD

**Issue by Wizzerinus** [Shinoow/AbyssalCraft#521]
**Is your feature request related to a problem? Please describe.**
The mod has many great rituals (i.e. level 10 enchanting, Sanctoth summoning, J'zahar respawn), and some of them are very important to the core of the mod (portal opening in 2.0 alphas). However, only the crafting rituals are shown in JEI. This can be pretty annoying for both players and mod developers alike, especially if they don't like reading books on every mod (source: I have reading issues)

**Describe the solution you'd like**
Show the rituals in JEI in some way.

**Describe alternatives you've considered**
I have a bit of modding experience and can make an additional mod that does just that. Figured it's something that belongs in the base mod though

**Comment by Shinoow** [comment]
That's something I didn't consider when setting up the initial JEI integration. Probably need to include an info-box with the ritual description as well, since that's pretty vital for some of the rituals.

**Comment by Wizzerinus** [comment]
The way Roots mod does it (they have Pyre that works similarly to ac rituals) is they have a separate category for these, and the outputs of those recipes are fake items (unobtainable) that have names like "Ritual: Transmutation" and have a link to open the mod book. I don't know how important putting the descriptions is in the recipes since I think the bigger problem is getting to know about the rituals existing in the first place (and then you need to have the book anyway to execute the ritual, and this mod has a knowledge system as well, so showing descriptions ahead of time may be bad for that reason), definitely can be discussed
