### ISSUE TITLE
rutiual thing not forming

### ISSUE THREAD

**Issue by memergod** [Shinoow/AbyssalCraft#523]
i have been trying to form the ritual alters and pedestal's, doing everything the book says even going to darklands to use their naturally generating alter setups and when i shift right-click with the book it just doesnt do anything, i am playing on a custom made modpack with friends on a server if it matters

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge:14.23.5.2859
- AbyssalCraft:1.10.6

https://www.kapwing.com/videos/66f6f3a1ea063a340380f348

**Comment by Shinoow** [comment]
Couldn't see the particles appear in the video (also looks like you left-clicked there), but anyways, all blocks need to be withing the same chunk. The notice for it is lacking in the 1.x branch of the mod, but if not all of the blocks are within the same chunk, the ones outside will be highlighted with the barrier particle showing up on top of the block.
