### ISSUE TITLE
AbyssalCraft 2.0.0-ALPHA-9 Version incompatibility Thaumcraft

### ISSUE THREAD

**Issue by frygttt** [Shinoow/AbyssalCraft#526]
[latest.log](https://github.com/user-attachments/files/17740833/latest.log)

**Comment by Shinoow** [comment]
I need the actually crash report. The log doesn't provide enough information.

**Comment by Shinoow** [comment]
Started digging into this, and it seems some change I made in 2.0.0-ALPHA-6 broke something. Yet to find what at the time of writing.
