### ISSUE TITLE
Branch Version Release Request - 1.8.9

### ISSUE THREAD

**Issue by DPxKnightxZero** [Shinoow/AbyssalCraft#55]
I have been helping you test your mod for a while and now I am wondering if you could do me a huge solid and create a 1.8.9 release! I love this mod infact its a spotlight in my minecraft expirence is this possible @Shinoow

**Comment by Shinoow** [comment]
I'm currently working on a 1.8.9 port. Can't really give a date for when it will be released, but it should at least be this month.

**Comment by DPxKnightxZero** [comment]
<3 Thanks bro : D
