### ISSUE TITLE
Crash in combination with Blood Magic

### ISSUE THREAD

**Issue by Zieg777** [Shinoow/AbyssalCraft#59]
Having died numerous times after entering the abyssal wasteland due to dragons swarming my gate (World doesn't even load, I just die), I decided to try to hold them at bay with a blood magic ritual of interdiction.

I will attempt to get the crashlog from the server admin, but right now the server crashes as soon as I log in. 

Since this ritual doesn't play nice with the dragons, is there any way to prevent them from killing you before the world loads?

**Comment by Shinoow** [comment]
Not really. The part I find odd is there being a swarm of them by the portal (the dragons are supposed to be quite rare, not spawning very often, but never more than a single one at times). If you were to regenerate the dimension, there shouldn't be a whole bunch of them grouping up at a single spot. Any other way I could think of would be to go in there and kill them (but that would either require you to be in creative or have good armor and a whole bunch of buffs).

**Comment by Zieg777** [comment]
Good to know that fighting more than one at once is not intended. It's impossible to enter if you're not in creative mode, you die before the world can actually load. I think we need to regenerate the dimension anyway since I crash the server when I log in due to the ritual.

How is it supposed to prevent there from being multiple dragons at once? I can't hang out in the dimension for more than a few minutes without more spawning. I'm trying to use the stone there as a building material, but I can't dig underground without a couple dragons coming through the walls. If I was only fighting one at a time it'd be manageable, but two or more guys that ignore walls, and are immune to many types of damage (explosions, Botania Terra blade beams, and lightning focus from TC at least) gets hard to handle and goes straight through most armor.

**Comment by Shinoow** [comment]
There's nothing built-in to prevent there from being more than a single dragon. Not killing them is a pretty simple method for increasing the number of dragons in the area. If there's a set number of them the first time you enter through the portal, then it's somewhat likely there's a mod installed that tweaks spawn rates, but if there's just a single dragon it doesn't mean more can't spawn, they're mobs after all.
It has come to my attention that the spawn rate isn't set to the absolute minimum, and there has been occasions where a duo spawns (eventhough it's set to specifically only spawn a single dragon when the mob is spawned), but that should stop happening with some alterations I've made.

**Comment by Shinoow** [comment]
Closing this issue now. If it's still something that occurs, please re-open it.
