### ISSUE TITLE
[1.8] Hopper Interaction

### ISSUE THREAD

**Issue by Nagshell** [Shinoow/AbyssalCraft#60]
Due to high amount of crystals that are produced in Crystalizer I decided to pump them out to chest. Sadly hopper pulls out items from fuel slot. Could this get changed?

**Comment by Shinoow** [comment]
Yeah, sounds like something that might've started happening after the 1.8.9 port. I'll be sure to patch that.

**Comment by Shinoow** [comment]
Seems to be the same case with the Transmutator. Both will be fixed.
