### ISSUE TITLE
Serious lag

### ISSUE THREAD

**Issue by kotoroshinoto** [Shinoow/AbyssalCraft#63]
With abysalcraft installed, it gets particularly bad when entering the nether, but it was persistent and annoying even outside in the overworld. It could be from a mod interaction, but we're not quite certain.

**Comment by Shinoow** [comment]
That is a big too vague for me to have anything I can go from. I'm gonna need with Minecraft version you're using, AbyssalCraft version, Forge version, other mods (make notes if they can have a part in this), if this persists when AbyssalCraft is removed from the instance and if this still happens when you switch difficulty to peaceful.

**Comment by kotoroshinoto** [comment]
MC 1.8.9
Forge 11.15.1.1755

list of jar files in mod directory (a very small number are disabled currently due to issues)

1.8.9 - Thaumaturgical Knowledge-0.2.jar
1.8.9-chunkedgeindicator-1.0.jar
AbyssalCraft-1.8.9-1.9.0-pre-3.jar.disabled
ArchitectureCraft-1.3.1-mc1.8.9.jar
AutoSapling 1.2 MC1.8.9.jar
BaseMetals-1.6.4.jar
BaublesHud-2.2.1.jar
BetterFoliage-MC1.8.x-2.0.4.jar
BloodMagic-1.8.9-2.0.0-19.jar
Botania.r1.8-248-MC1.8-0.6.1.jar
buildcraft-7.2.0-pre12-builders.jar
buildcraft-7.2.0-pre12-compat1.jar
buildcraft-7.2.0-pre12-core.jar
buildcraft-7.2.0-pre12-energy.jar
buildcraft-7.2.0-pre12-factory.jar
buildcraft-7.2.0-pre12-robotics.jar
buildcraft-7.2.0-pre12-silicon.jar
buildcraft-7.2.0-pre12-transport.jar
ChunkLoaderZ-1.8.9-1.0.3.jar
ClayWorldGen-1.0.1.jar
coroutil-1.8.9-1.1.4.jar.disabled
craftingcraft-mc1.8.9-2.0.11.jar
craftingtweaks-mc1.8.9-3.0.52.jar
craftingtweaksaddons-mc1.8.9-3.0.8.jar
CraftTweaker-Customized-1.8.8-3.0.1.jar
Fancy Fluid Storage-1.8.9-1.4.5.7.91.jar
graves-1.8.9-b37-universal.jar
hopperducts-mc1.8.8-1.4.6.jar
IGW-Mod-1.8.9-1.2.4-4-universal.jar
intangible-1.8.9-0.0.23.jar
inventorysorter-1.8.9-0.7.4+26.jar
ironchest-1.8.9-6.0.125.770.jar
JEIAddons_1.8.9-0.12.0.57.jar
jei_1.8.9-2.28.3.167.jar
LLOverlayReloaded-1.0.5-mc1.8.9.jar
Mantle-1.8.9-0.8.2.jar
MapWriter-1.8.9-2.3.13.jar
MCA-1.8.9-5.1.1.2-universal.jar
mcjtylib-1.8.9-1.8.1beta7.jar
ModTweaker2-1.0.0.jar
morefoods-1.0b.jar
MoreFurnaces-1.5.0-MC1.8.9.jar
Morpheus-1.8.9-2.0.58.jar
netherportalfix-mc1.8.9-2.1.6.jar
NoMoreRecipeConflict-0.3(1.8.X).jar
OpenComputers-MC1.8.9-1.5.22.6.jar
OptiFine_1.8.9_HD_U_H3.jar.disabled
PneumaticCraft-1.8.9-1.13.7-11-universal.jar
preview-OptiFine_1.8.9_HD_U_H4_pre.jar
RadixCore-1.8.9-2.1.0-universal.jar
redstonepaste-mc1.8.8-1.7.2.jar
rftools-1.8.9-4.22beta28.jar
rftoolsdim-1.8.9-4.22beta25.jar
SGCraft-1.10.1-mc1.8.9.jar
Skype4MC-1.4.jar.disabled
Super Ores V1.1 mc1.8.9.jar
TConstruct-1.8.9-2.1.0.jar
Thaumcraft-1.8.9-5.1.6.jar
weather2-1.8.9-2.3.11.jar.disabled
WIT-1.8.9-1.0.7-19.jar
worldedit-forge-mc1.8.9-6.1.1.jar
[1.8.8] SecurityCraft v1.8.1.jar.disabled

**Comment by kotoroshinoto** [comment]
I will try enabling abyssalcraft again and see if switching to peaceful does anything to the lag.

**Comment by Shinoow** [comment]
Seems like this has to do with the demon animals way of generating fire wherever they walk, so it is being worked on.
