### ISSUE TITLE
crash while booting AbyssalCraft-1.8.9-1.9.0

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#64]
http://pastebin.com/idHvkgUi

**Comment by Shinoow** [comment]
Thanks for reporting this on such short notice! It could've really turned into a horrible mess.

**Comment by Divineaspect** [comment]
did this get a stealth update?

**Comment by Shinoow** [comment]
Pretty much. Did a re-release on 1.8.9-1.9.0.

**Comment by Divineaspect** [comment]
rereleases without version changes are hell on pack devs, and screwup auto updaters such as those used by ATL, FYI.

**Comment by Shinoow** [comment]
If the stealth update is released 5 hours after the original one (which at the time has received 20 downloads), there should be next to no impact. Besides, I hardly do stealth updates, only when the new version breaks at startup (and was released less than 8 hours ago).

**Comment by Divineaspect** [comment]
my auto updater, through ATL, tracks by version number. 

It DLs automatically when there's an update, and that file is  what gets referenced by a pack who uses their auto update feature. Meaning as far as they can tell they have the most up to date version, because, you know, that's what version numbers mean.

In the event of a stealth update, while no one knows you needed to fix anything, no one knows anything they see breaking is fixed. Then they think your mod is buggy, and not how cool it is. Making mistakes and fixing them, makes you look more reliable / less wrong in the long run.
