### ISSUE TITLE
Omothol structure generation

### ISSUE THREAD

**Issue by Shinoow** [Shinoow/AbyssalCraft#70]
Since the structures generating around the temple are randomized, one way to secure that there will at least be something around every side of the temple would be to have the road generator start at appropriate distances on the left and right side of the temple (since it's approx 90 blocks wide, might do one at Z + 30, then Z + 60).
Another idea that popped into my head the other day was if there should be separate "villages" generating throughout the dimension (the way it currently looks, there's not a large chance that the main area of buildings will be able to expand a very large distance, but I might be able to find where that specific part can be tweaked at some point). These little areas (if implemented) would be like vanilla villages (well, apart from all things ethaxium), with the well replaced by something else. They would likely generate a lot more frequently (to cover up as much area of the dimension as possible), and hopefully make it easier to travel between islands in cases where roads spread their way over the void.

**Comment by Efimero** [comment]
maybe you could add some random floating rocks that fill the space between buildings
something like the vanilla dirt patches undergroung, but made of dark stone and in the air

**Comment by ravensourcious** [comment]
I love this idea, I felt Omothol needed more to wander around and do. It felt like a barren version of the end until I got to the city, which was small, I would love to do city structures, or strongholds/fortresses/end city like structures surrounding the city proper
