### ISSUE TITLE
Crash at startup with forge 1809

### ISSUE THREAD

**Issue by kwpugh** [Shinoow/AbyssalCraft#72]
Crash report:   http://pastebin.com/raw/AaH6M03z

**Comment by Shinoow** [comment]
Forge did a pretty big refactor on internal things in 1805, breaking a lot of mods (including this one) in situations where events are involved. Until I release an update bumping the Forge version, 1804 is the version that you can run 1.9.1-pre-1 on.

**Comment by kwpugh** [comment]
ok, thank you.
