### ISSUE TITLE
[1.9] Stick Recipe Broken

### ISSUE THREAD

**Issue by squirrelkiller** [Shinoow/AbyssalCraft#74]
So this mod is causing an issue with sticks, namely it is making only your woods and oak wood valid for stick creation. It seems to be related to you removing them from the ore dictionary.

Version Mod Version: AbyssalCraft-1.9-1.9.1-pre-2
Forge Version: 12.16.0.1832

I found this by systematically removing and replacing each mod in the pack until the offending mod was found, which was you, so I do not think this was a result of another mod. I looked at your code for entries related to "plankWood" and "Items.stick" and I honestly do not see what you did wrong, but something weird is happening. All I know is the issue comes and goes with your mod.

**Comment by Shinoow** [comment]
Yeah... this is rather strange...
The last time I did anything to the stick recipe was when I implemented the Darklands Oak, but that was roughly 2 and a half years ago, and said additional stick recipe was removed when I added my wood types to the OreDictionary, which was also around 2 years ago.

**Comment by Shinoow** [comment]
This appears to be the case with any crafting recipe involving planks. Still clueless as to why this is happening in the first place.

**Comment by Shinoow** [comment]
Well, the issue has been located! It appears that I accidentally manipulated crafting recipe components when my CraftingStack utility class autogenerated crafting recipes involving OreDictionary components (in this case it set all the different types of wooden planks to the oak metadata, since they all share the same field).
