### ISSUE TITLE
Crash with Cave Control (Abyssalcraft V1.9.1.1-FINAL 1.7.10)

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Shinoow/AbyssalCraft#76]
http://paste.feed-the-beast.com/view/d6afd0fc
Issue between mineshaft generation. Crash is on world creation with Cave Control installed.

**Comment by Shinoow** [comment]
Last time I saw a crash like that was a bit over 2 years ago with Oceancraft (and the devs for that mod did something on their end to fix it). At least I'm more aware of the cause this time, so a fix for this will come out at some point in the near future.
