### ISSUE TITLE
[1.9] Crash on world load.

### ISSUE THREAD

**Issue by squirrelkiller** [Shinoow/AbyssalCraft#77]
Here just take this. It has been a massive hunt to find the cause of this crash which happens upon world load:

[crash-2016-04-25_19.02.07-server.txt](https://github.com/Shinoow/AbyssalCraft/files/235681/crash-2016-04-25_19.02.07-server.txt)
[crash-2016-04-25_19.06.55-server.txt](https://github.com/Shinoow/AbyssalCraft/files/235682/crash-2016-04-25_19.06.55-server.txt)
[crash-2016-04-25_19.55.05-server.txt](https://github.com/Shinoow/AbyssalCraft/files/235683/crash-2016-04-25_19.55.05-server.txt)

Here is the modpack I use:

http://minecraft.curseforge.com/projects/sk-lets-play-season-1-pack

Or use my personal instance of it (removing optifine does not fix it I tried): https://www.dropbox.com/s/iopksy0vj5jpias/Instance%20Sample%20For%20BoP%20Team-1.0.zip?dl=0

I was going to add your own mod to the pack upon the next update, but upon adding it crashes. To get the exact case also add Evilcraft and go down the list updating the pack to latest releases of each mod.

**Comment by Shinoow** [comment]
From looking at the first two crash reports, the part being referenced in BiomeGenBase is code that my mod doesn't alter a single bit, then there's the fact that BoP code is referenced as well.

**Comment by Shinoow** [comment]
Yeah, this has nothing to do with AbyssalCraft. I loaded up your instance, updated all mods and added AbyssalCraft, then created a new world and got the same crash as the first and second report. After that I removed AbyssalCraft, created yet again a new world and got the same crash.
