### ISSUE TITLE
AbyssalCraft biomes are not registered through Forge

### ISSUE THREAD

**Issue by Funwayguy** [Shinoow/AbyssalCraft#80]
I was unable to find any use of Forge's biome registration method (net.minecraft.world.biome.BiomeGenBase.registerBiome()) for AbyssalCraft biomes.

The purpose of this is so I can allow Darkosto to choose which blocks spawn in specific biomes within SkyGrid however the above issue prevents configs from referencing them. It may be relevant to your other related issue but if they were registered, mods could easily refer to them via a resource location name such as "abyssalcraft:darkrealm"

**Comment by Shinoow** [comment]
I think it was around build 1832 that Lex did a huge overhaul on registrys and implemented an entire new system. So the biomes are registered, but they are registered through `GameRegistry`, and not inside `BiomeGenBase` (as only vanilla biomes should be registered there now). Although, I am going to go through with #79 soon enough, which will make all biome references part of the API.

**Comment by Shinoow** [comment]
It appears our dear friend @Darkosto wrote the resource locations wrongly, thus failing to find the biomes :P
