### ISSUE TITLE
MimicFire cannot be punched to remove it

### ISSUE THREAD

**Issue by Mach12** [Shinoow/AbyssalCraft#82]
The fire Demon animals spray (seemingly the MimicFire class) cannot be punched into exctinction like regular fire.

On a normal game this is no issue, but if you play with doFireTick off it stays indefinitely if you don't replace it with a block or break all supporting blocks.

**Comment by Shinoow** [comment]
This has been looked over, and currently you will be able to destroy the block by punching it, but the sounds effects and particles that normally display when doing so aren't displaying (since I need to write some additional code to mimic that behavior).
