### ISSUE TITLE
Client Crash on a new world at com.shinoow.abyssalcraft.client.handlers.AbyssalCraftClientEventHooks.extinguishFire

### ISSUE THREAD

**Issue by ProsperCraft** [Shinoow/AbyssalCraft#83]
http://pastebin.com/recfpJka

I had just created a new world and was hitting a chicken with a wood axe.

**Comment by ProsperCraft** [comment]
http://pastebin.com/L5yv9GL2

Reproduced here while killing other mobs.

**Comment by Shinoow** [comment]
Oh yeah, that's more or less a beginners mistake I managed to make there. The reason you're crashing is because of a missing null check (hence the NPE). For now I would advice you downgrade to 1.9.1.1 until I have something out that corrects this error.

**Comment by Shinoow** [comment]
I was able to reproduce it; went on a rampage against a bunch of chickens, swinging a wooden axe all over the place. I do believe I've found a solution, but I might conduct some more testing before reaching that conclusion.
