### ISSUE TITLE
[1.9] Server crash at startup

### ISSUE THREAD

**Issue by kwpugh** [Shinoow/AbyssalCraft#85]
Forge 1865
Mod: AbyssalCraft-1.9-1.9.1.3.jar

Crash report: http://pastebin.com/raw/u0J6G11K

**Comment by Shinoow** [comment]
Yeah, gonna do 1.9.1.4 in a bit, know exactly where this is triggered.

**Comment by kwpugh** [comment]
Would this error interact with WAILA adversely?   Starting to get wails crashes, but haven't updated it in a long time.

**Comment by Shinoow** [comment]
No, this is a case of client code being ran serverside. I got some help with fixing my leaf code in 1.8.9/1.9, but one part of that ended up as client code being called on both sides (and the server hates it when you try to run client code through it). I've uploaded 1.9.1.4 to curse, so it should be available soon.

**Comment by kwpugh** [comment]
Thanks for the update.  I will give it a try.

**Comment by Shinoow** [comment]
I did a test run in my 1.8.9 workspace (since the server in the 1.9 refused to start for some reason) and it went through the boot cycle without any crashes, so it should be fine.

**Comment by kwpugh** [comment]
ok, the server started fine, I let you know if any crashes are encountered.
