### ISSUE TITLE
Are the AbyssalCraft side projects: Heads, and Integration, supposed to have different licences?

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#87]
Doing permissions for ATL, and curious about the discontinuity.

**Comment by Shinoow** [comment]
No mod is being discontinued (apart from the 1.7.10 branch of AbyssalCraft and AbyssalCraft Heads, but that's simply just a Minecraft version no longer being supported). If the modpack clauses on the mod pages aren't making it clear, permission is granted if you provide credits to me along with a link back to the mod's page.
I might need to redraft them a slight bit, pitching in the part about no monetization and permissions being revoked if any terms are violated (then likely adjust how it's paraphrased to put more emphasis on the terms).

**Comment by Shadows-of-Fire** [comment]
It would be easier to just apply those to the license section of Curseforge under a custom license instead of in a subheading, just for clarity reasons.  Having the base Abyssalcraft under a GPL and most of the others under ARR with the modpack clause is a bit confusing for certain users.

**Comment by Shinoow** [comment]
That seems to be the new thing people do with their mods (I've always seen the info about modpack perms as a subheading in the OP, usually around the bottom, but that seems to have changed since some time ago). I might just do the same thing for my projects.

**Comment by Shinoow** [comment]
The modpack terms for the side projects have been clarified (along with a custom license referencing it as well).
