### ISSUE TITLE
The trees aren't recognized by Better Foliage

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#89]
I already posted this issue on CurseForge, but I repost it here for being sure. I finded a very strange bug with your mod. The two trees added by your mod aren't recognized by the mod Better Foliage. It has for result that the dense foliage and falling leaves effects don't applicate them to your two trees.

**Comment by Shinoow** [comment]
Well, the reason for that is that Better Foliage doesn't have native support for AbyssalCraft. If you want to have the same effect on my leaf/log/grass types, you have to manually add them to the various lists in the Better Foliage config.
I might as well list all of them here:

Grass Blocks:
`com.shinoow.abyssalcraft.common.blocks.BlockDarklandsgrass`
`com.shinoow.abyssalcraft.common.blocks.BlockDreadGrass`

Leaf Blocks:
`com.shinoow.abyssalcraft.common.blocks.BlockDLTLeaves`
`com.shinoow.abyssalcraft.common.blocks.BlockDreadLeaves`

Log Blocks:
`com.shinoow.abyssalcraft.common.blocks.BlockDLTLog`
`com.shinoow.abyssalcraft.common.blocks.BlockDreadLog`

**Comment by Shinoow** [comment]
As I've provided the needed information on my end, you can reference the above reply to the Better Foliage developer if you wish for that mod to add native support for AbyssalCraft. This issue will be closed until further notice.
