### ISSUE TITLE
Biomes o plenty conflict with Abyssal Craft 1.8.9

### ISSUE THREAD

**Issue by DanTheColoradan** [Shinoow/AbyssalCraft#90]
MC 1.8.9
Forge 1.8.9-11.15.1.1890
BiomesOPlenty 1.8.9-3.0.0.2004
AbyssalCraft 1.8.9-1.9.1.5

I'm trying hastebin for the crash report. Let me know if it doesn't work.

http://hastebin.com/raw/kopapodahi

**Comment by Shinoow** [comment]
That's a biome ID conflict. Either change the conflicting ID in the AbyssalCraft config file or the BoP one.
