### ISSUE TITLE
[1.9] Client crash when right-clicking with Blood Magic's Bound Blade.

### ISSUE THREAD

**Issue by Limitrophic-Researcher** [Shinoow/AbyssalCraft#94]
Current latest version of AbyssalCraft, one version behind on Blood Magic (playing on a private server, so I'll need to talk with the other players before updating the pack). It seems to only be the bound blade, but the stacktrace points to a modification of FOV on AbyssalCraft's end? It happens with or without NoFOV.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  LoadingPluginHardModeTweaks (HardModeTweaks-1.9-1.2.1.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/14/16 4:53 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.shinoow.abyssalcraft.client.handlers.AbyssalCraftClientEventHooks.onUpdateFOV(AbyssalCraftClientEventHooks.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_AbyssalCraftClientEventHooks_onUpdateFOV_FOVUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.getOffsetFOV(ForgeHooksClient.java:211)
	at net.minecraft.client.entity.AbstractClientPlayer.func_175156_o(AbstractClientPlayer.java:151)
	at net.minecraft.client.renderer.EntityRenderer.func_78477_e(EntityRenderer.java:448)
	at net.minecraft.client.renderer.EntityRenderer.func_78464_a(EntityRenderer.java:262)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.shinoow.abyssalcraft.client.handlers.AbyssalCraftClientEventHooks.onUpdateFOV(AbyssalCraftClientEventHooks.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_AbyssalCraftClientEventHooks_onUpdateFOV_FOVUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.getOffsetFOV(ForgeHooksClient.java:211)
	at net.minecraft.client.entity.AbstractClientPlayer.func_175156_o(AbstractClientPlayer.java:151)
	at net.minecraft.client.renderer.EntityRenderer.func_78477_e(EntityRenderer.java:448)
	at net.minecraft.client.renderer.EntityRenderer.func_78464_a(EntityRenderer.java:262)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LimitResearcher'/300, l='MpServer', x=-189.54, y=62.00, z=719.75]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-133,64,601), Chunk: (at 11,4,9 in -9,37; contains blocks -144,0,592 to -129,255,607), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 5824541 game time, 6072025 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 59 total; [EntityZombie['Zombie'/516, l='MpServer', x=-152.50, y=42.00, z=792.50], EntityCreeper['Creeper'/393, l='MpServer', x=-180.50, y=75.00, z=781.50], EntityBat['Bat'/394, l='MpServer', x=-168.93, y=17.22, z=747.36], EntityBat['Bat'/528, l='MpServer', x=-131.25, y=37.00, z=788.48], EntitySkeleton['Skeleton'/280, l='MpServer', x=-180.50, y=7.00, z=645.31], EntitySquid['Squid'/411, l='MpServer', x=-156.70, y=59.97, z=736.47], EntityMinecartChest['container.minecart'/412, l='MpServer', x=-127.50, y=24.06, z=779.50], EntityCreeper['Creeper'/414, l='MpServer', x=-122.50, y=17.00, z=796.50], EntitySkeleton['Skeleton'/801, l='MpServer', x=-199.50, y=37.00, z=689.50], EntitySkeleton['Skeleton'/684, l='MpServer', x=-240.50, y=31.00, z=733.50], EntityBat['Bat'/303, l='MpServer', x=-205.17, y=55.10, z=798.48], EntityZombie['Zombie'/49, l='MpServer', x=-230.19, y=36.00, z=663.50], EntityZombie['Zombie'/306, l='MpServer', x=-213.74, y=75.00, z=779.53], EntityPlayerSP['LimitResearcher'/300, l='MpServer', x=-189.54, y=62.00, z=719.75], EntityAntiCow['Anti-Cow'/307, l='MpServer', x=-194.15, y=76.00, z=768.71], EntityCreeper['Creeper'/312, l='MpServer', x=-226.50, y=37.00, z=799.50], EntityCow['Cow'/313, l='MpServer', x=-237.84, y=75.00, z=796.51], EntityCow['Cow'/59, l='MpServer', x=-218.41, y=66.00, z=659.22], EntityCow['Cow'/316, l='MpServer', x=-252.55, y=80.00, z=773.45], EntityZombie['Zombie'/317, l='MpServer', x=-231.29, y=33.00, z=732.51], EntityZombie['Zombie'/62, l='MpServer', x=-210.22, y=41.00, z=728.54], EntityBat['Bat'/318, l='MpServer', x=-220.07, y=27.35, z=739.30], EntityZombie['Zombie'/63, l='MpServer', x=-212.27, y=45.00, z=721.54], EntityCow['Cow'/320, l='MpServer', x=-224.51, y=74.00, z=768.14], EntityCreeper['Creeper'/69, l='MpServer', x=-202.50, y=29.00, z=693.50], EntityCow['Cow'/326, l='MpServer', x=-253.80, y=80.00, z=755.86], EntityCow['Cow'/327, l='MpServer', x=-256.15, y=80.00, z=760.95], EntityZombie['Zombie'/76, l='MpServer', x=-186.50, y=54.00, z=681.50], EntityCreeper['Creeper'/77, l='MpServer', x=-187.47, y=54.00, z=693.18], EntityBat['Bat'/78, l='MpServer', x=-186.25, y=18.70, z=722.49], EntityCow['Cow'/79, l='MpServer', x=-176.21, y=66.00, z=707.82], EntityCow['Cow'/80, l='MpServer', x=-177.16, y=66.00, z=706.89], EntityCow['Cow'/81, l='MpServer', x=-176.08, y=66.00, z=706.07], EntityCow['Cow'/82, l='MpServer', x=-180.66, y=66.00, z=710.92], EntityCow['Cow'/83, l='MpServer', x=-181.18, y=66.00, z=709.72], EntityCreeper['Creeper'/339, l='MpServer', x=-267.15, y=33.00, z=709.42], EntityCow['Cow'/84, l='MpServer', x=-181.93, y=66.00, z=710.92], EntityCow['Cow'/85, l='MpServer', x=-181.23, y=66.00, z=708.52], EntityCow['Cow'/86, l='MpServer', x=-176.08, y=66.00, z=710.92], EntityCow['Cow'/87, l='MpServer', x=-178.09, y=66.00, z=706.64], EntityBoat['Boat'/90, l='MpServer', x=-164.10, y=62.52, z=731.31], EntityZombie['Zombie'/475, l='MpServer', x=-248.50, y=28.00, z=694.50], EntityCreeper['Creeper'/353, l='MpServer', x=-142.50, y=40.00, z=792.50], EntitySkeleton['Skeleton'/481, l='MpServer', x=-243.50, y=4.00, z=654.50], EntitySkeleton['Skeleton'/354, l='MpServer', x=-134.50, y=46.00, z=792.50], EntityBat['Bat'/355, l='MpServer', x=-141.45, y=47.96, z=782.40], EntitySkeleton['Skeleton'/869, l='MpServer', x=-119.50, y=13.00, z=753.50], EntityZombie['Zombie'/364, l='MpServer', x=-133.50, y=5.00, z=758.50], EntityCow['Cow'/365, l='MpServer', x=-121.80, y=62.06, z=736.65], EntityMinecartChest['container.minecart'/111, l='MpServer', x=-133.50, y=23.06, z=725.49], EntityCreeper['Creeper'/752, l='MpServer', x=-224.50, y=37.00, z=669.50], EntityCow['Cow'/369, l='MpServer', x=-159.70, y=75.00, z=773.54], EntityBat['Bat'/242, l='MpServer', x=-173.25, y=25.10, z=721.75], EntityZombie['Zombie'/628, l='MpServer', x=-233.50, y=29.00, z=741.50], EntityBat['Bat'/505, l='MpServer', x=-250.25, y=43.03, z=720.86], EntitySkeleton['Skeleton'/379, l='MpServer', x=-173.50, y=14.00, z=739.50], EntityMinecartChest['container.minecart'/124, l='MpServer', x=-123.50, y=23.06, z=730.50], EntityZombie['Zombie'/380, l='MpServer', x=-173.50, y=45.00, z=750.50], EntityBat['Bat'/383, l='MpServer', x=-250.75, y=40.13, z=715.58]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 667047944 bytes (636 MB) / 2047344640 bytes (1952 MB) up to 2047344640 bytes (1952 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.23 Powered by Forge 12.16.1.1897 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	Forge{12.16.1.1897} [Minecraft Forge] (modpack.jar) 
	UCHIJA	CodeChickenCore{2.0.1.53} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	hardmodetweakscore{1.0.0} [Hard Mode Tweaks Core] (minecraft.jar) 
	UCHIJA	JEI{3.3.3.199} [Just Enough Items] (jei_1.9-3.3.3.199.jar) 
	UCHIJA	abyssalcraft{1.9.1.6} [AbyssalCraft] (AbyssalCraft-1.9-1.9.1.6.jar) 
	UCHIJA	acblocks{1.0.0} [AbyssalBlocks] (AbyssalBlocks-1.9-1.0.0.jar) 
	UCHIJA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCHIJA	acintegration{1.4.2.1} [AbyssalCraft Integration] (AbyssalCraft Integration-1.9-1.4.2.1.jar) 
	UCHIJA	AutoSapling{1.3} [AutoSapling] (AutoSapling-1.3.1 MC1.9.jar) 
	UCHIJA	backlytra{1.9-0.0.1} [Backlytra] (backlytra-1.9-0.0.1.jar) 
	UCHIJA	bagginses{2.3.0b} [Bagginses] (Bagginses-1.9-2.3.0b.jar) 
	UCHIJA	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCHIJA	bdlib{1.11.0.14} [BD Lib] (bdlib-1.11.0.14-mc1.9.jar) 
	UCHIJA	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCHIJA	BloodMagic{1.9-2.0.0-36} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-36.jar) 
	UCHIJA	bookshelf{1.2.0.226} [Bookshelf] (Bookshelf-1.9-1.2.0.237.jar) 
	UCHIJA	bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar) 
	UCHIJA	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCHIJA	chancecubes{1.9-2.1.1.98} [Chance Cubes] (ChanceCubes-1.9-2.1.1.98.jar) 
	UCHIJA	ChestTransporter{2.3.0} [Chest Transporter] (ChestTransporter-2.3.0-MC1.9.jar) 
	UCHIJA	ChickenChunks{2.0.1.26} [ChickenChunks] (ChickenChunks-1.9-2.0.1.26-universal.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCHIJA	mcmultipart{1.1.1} [MCMultiPart] (MCMultiPart-1.1.1-universal.jar) 
	UCHIJA	chiselsandbits{9.15} [Chisels & Bits] (chiselsandbits-9.15.jar) 
	UCHIJA	claybucket{1.0} [Clay Bucket] (ClayBucket-1.9-1.0.jar) 
	UCHIJA	cookingforblockheads{2.0.9} [Cooking for Blockheads] (CookingForBlockheads-mc1.9-2.0.9.jar) 
	UCHIJA	craftingcraft{3.0.3} [CraftingCraft] (craftingcraft-mc1.9-3.0.3.jar) 
	UCHIJA	craftingtweaks{4.0.10} [Crafting Tweaks] (craftingtweaks-mc1.9-4.0.10.jar) 
	UCHIJA	ElecCore{1.4.270} [ElecCore] (ElecCore-1.9-1.4.270.jar) 
	UCHIJA	deepresonance{1.1.4beta30} [DeepResonance] (deepresonance-1.9.0-1.1.4beta30.jar) 
	UCHIJA	eplus{4.1.0.86} [Enchanting Plus] (EnchantingPlus-1.9-4.1.0.97.jar) 
	UCHIJA	endercompass{1.2.3} [Ender Compass] (EnderCompass-1.9-1.2.3.jar) 
	UCHIJA	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.1.3.jar) 
	UCHIJA	shetiphiancore{3.2.2} [ShetiPhian-Core] (shetiphiancore-1.9.0-3.2.2.jar) 
	UCHIJA	endertanks{1.3.3} [EnderTanks] (endertanks-1.9.0-1.3.3.jar) 
	UCHIJA	FFS{1.9-1.5.1.1.2} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9-1.5.1.1.2.jar) 
	UCHIJA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJA	FlatBedrockx{1.2.0} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.2.0_1.9.jar) 
	UCHIJA	flatcoloredblocks{mc1.9-v2.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.9-v2.2.jar) 
	UCHIJA	fluxducts{1.0.3} [Flux Ducts] (fluxducts-mc1.9-1.0.3.jar) 
	UCHIJA	foxlib{@VERSION@} [FoxLib] (FoxLib-1.9-0.9.0.jar) 
	UCHIJA	pressure{1.3.1.13} [Pressure Pipes] (pressure-1.3.1.13-mc1.9.jar) 
	UCHIJA	advgenerators{0.9.20.8} [Advanced Generators] (generators-0.9.20.8-mc1.9.jar) 
	UCHIJA	graves{1.9-b10-universal} [Graves Mod] (graves-1.9-b10-universal.jar) 
	UCHIJA	hardmodetweaks{@1.9-1.2.1@} [Hard Mode Tweaks] (HardModeTweaks-1.9-1.2.1.jar) 
	UCHIJA	Harvest{1.9-1.0.1-3} [Harvest] (Harvest-1.9-1.0.1-3.jar) 
	UCHIJA	HelpFixer{1.3.13} [HelpFixer] (HelpFixer-1.9-1.3.13.jar) 
	UCHIJA	hgp{Release} [Horizontal Glass Panes] (hgp-1.9-1.0.2.jar) 
	UCHIJA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCHIJA	inventorytweaks{1.61-dev-49-c5b6395} [Inventory Tweaks] (InventoryTweaks-1.61-dev-49.jar) 
	UCHIJA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJA	itemscroller{0.4.2} [Item Scroller] (itemscroller-1.9-0.4.2.jar) 
	UCHIJA	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCHIJA	jeresources{0.4.5.27} [Just Enough Resources] (JustEnoughResources-1.9-0.4.5.27.jar) 
	UCHIJA	jet_packs{1.0.0} [Just JetPacks] (JustJetpacks-1.0.0.jar) 
	UCHIJA	Login_Shield_MC1.9{1.2-21-g08fa29a} [Login Shield] (Login_Shield_MC1.9-1.2-21-g08fa29a.jar) 
	UCHIJA	LunatriusCore{1.1.2.34} [LunatriusCore] (LunatriusCore-1.9-1.1.2.34-universal.jar) 
	UCHIJA	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.jar) 
	UCHIJA	modularsystems{3.0.2} [Modular Systems] (ModularSystems-1.9-3.0.2.jar) 
	UCHIJA	morematerials{1.0.20150301.0} [More Materials] (morematerials-1.9.20160320.0.jar) 
	UCHIJA	moreoverlays{1.3.1} [MoreOverlays] (moreoverlays-1.3.1-mc1.9.jar) 
	UCHIJA	moreplayermodels{1.9.0} [MorePlayerModels] (MorePlayerModels_1.9.0beta(01apr16).jar) 
	UCHIJA	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCHIJA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-5.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9-3.0.6.jar) 
	UCHIJA	NoFov{1.0.1} [No Fov] (NoFov-MC1.9-1.0.1.jar) 
	UCHIJA	notenoughwands{1.3.2} [Not Enough Wands] (notenoughwands-1.9.0-1.3.2.jar) 
	UCHIJA	samsocean{1.0.0} [Classic Oceans] (OceanFloor-1.9-1.0.1.jar) 
	UCHIJA	fodc{1.8.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.1.jar) 
	UCHIJA	packingtape{0.5.1} [Packing Tape] (Packing Tape-0.5.1.jar) 
	UCHIJA	harvestcraft{1.9a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9a.jar) 
	UCHIJA	parachutemod{1.4.1} [Parachute Mod] (parachutemod-ng-1.9-1.4.1-396.jar) 
	UCHIJA	progressiveautomation{1.6.42} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.42.jar) 
	UCHIJA	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCHIJA	quantumflux{2.0.6} [QuantumFlux] (quantumflux-1.9-2.0.6.jar) 
	UCHIJA	Quark{beta-18} [Quark] (Quark-beta-18.jar) 
	UCHIJA	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UCHIJA	xreliquary{1.9-1.3.1.338} [Reliquary] (Reliquary-1.9-1.3.1.338.jar) 
	UCHIJA	rftools{4.46} [RFTools] (rftools-1.9.0-4.46.jar) 
	UCHIJA	rftoolsdim{4.23beta37} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta37.jar) 
	UCHIJA	SimilsaxTranstructors{1.9.0.17} [Similsax Transtructors] (SimilsaxTranstructors-1.9.0.17.jar) 
	UCHIJA	simpleretrogen{2.2.3+4} [Simple Retrogen] (simpleretrogen-1.9-2.2.3+4.jar) 
	UCHIJA	Stackie{1.6.0.41} [Stackie] (Stackie-1.9-1.6.0.41-universal.jar) 
	UCHIJA	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UCHIJA	substratum{1.3.0.0} [Substratum] (Substratum-1.9-1.3.0.0.jar) 
	UCHIJA	Tails{1.9-1.6.1} [Tails] (Tails-1.9-1.6.1.jar) 
	UCHIJA	trashslot{3.0.4} [TrashSlot] (trashslot-mc1.9-3.0.4.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	UCHIJA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UCHIJA	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9-2.2.0.186.jar) 
	UCHIJA	wawla{2.2.0.178} [What Are We Looking At] (Wawla-1.9-2.2.0.186.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
LoadingPluginHardModeTweaks (HardModeTweaks-1.9-1.2.1.jar)
  com.hea3ven.hardmodetweaks.core.ClassTransformerHardModeTweaks
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
CCCDeobfPlugin (unknown)
  
FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 640/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AbyssalBlocksAPI (1.0.0) from AbyssalBlocks-1.9-1.0.0.jar
		* AbyssalCraftAPI (1.7.1) from AbyssalCraft-1.9-1.9.1.6.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-36.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.15.jar
		* CoFHAPI (1.8.9R1.2.0B1) from quantumflux-1.9-2.0.6.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Fancy Fluid Storage-1.9-1.5.1.1.2.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CraftingTweaks|API (4.1) from craftingtweaks-mc1.9-4.0.10.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta30.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.270.jar
		* jeresources|API (0.4.5.27) from JustEnoughResources-1.9-0.4.5.27.jar
		* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.199.jar
		* McJtyLib (1.9.0-1.8.3) from mcjtylib-1.9.0-1.8.3.jar
		* pressureAPI (1.3.1.13) from pressure-1.3.1.13-mc1.9.jar
		* PsiAPI (2) from Psi-beta-31.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* TailsAPI (1.1.1) from Tails-1.9-1.6.1.jar
		* WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
	Launched Version: 1.9-forge1.9-12.16.1.1897
	LWJGL: 2.9.4
	OpenGL: GeForce GT 640/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD Athlon(tm) 64 X2 Dual Core Processor 5200+

**Comment by Shinoow** [comment]
The only FOV modification I do is mimicking the vanilla bow's FOV alteration for my own bow. However, judging by how that code looks, there's probably a few things that could use some changing there (didn't put too much thought into how that code looked when I ported to 1.9).
