### ISSUE TITLE
Use maven for API distribution

### ISSUE THREAD

**Issue by topisani** [Shinoow/AbyssalCraft#96]
Hi, im Topisani, an RTG dev.
Currently we include your source in the RTG repo, but it would be great to be able to access it in other ways. Have you ever considered using something like https://bintray.com/ for a maven repo? it would give us, and probably other people a way more convenient way to access the api.

Keep up the good work

**Comment by Shinoow** [comment]
I've been meaning to set up a maven for all the things. Might as well go through with it!

**Comment by topisani** [comment]
awesome! we will do the same once our api is ready too then ;)
