### ISSUE TITLE
Should Dread Spawn be spawning on the overworld?

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#97]

**Comment by Shinoow** [comment]
No, but it possible for them to spawn through entities being killed by a weapon that has the Dread enchantment (as enchantments can't be locked to certain dimensions, making it possible for the Dread enchantment to be applied to any weapon, thus allowing Dread Spawns to spawn from entities killed by the Dread Plague).

**Comment by Divineaspect** [comment]
I think this is related to #95, as "dread" seems to be the common descriptor for the mobs.
