### ISSUE TITLE
AByssalCraft causes crash when join of new world

### ISSUE THREAD

**Issue by Morpheus1101** [Shinoow/AbyssalCraft#98]
Crash Report @ http://pastebin.com/ZmcmvgaB

When creating a new world, when going to actually joining it, everything works aok untill AbyssalCraft is added in then the above crash occurs when trying to join the actual world.

**Comment by Shinoow** [comment]
That's caused by a mod failing to register their EnumCreatureType(s) correctly (same as #81 and #88).
I recommend you take out mods until it stops crashing, then show the author of the culprit mod this: https://github.com/TeamLapen/Vampirism/issues/64#issuecomment-215508278
